import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {ROOT,readTerms,readOrientationCapsule,sha256} from '../src/contract.mjs';
import {runtimePaths} from '../src/state.mjs';
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const withReceipt=x=>({...x,receipt_sha256:digest(x)});
export function bootstrapHandoff(pending='inizializza',sourceHead='a'.repeat(40)){const terms=readTerms(),c=readOrientationCapsule();return{schema:'ikant-le-preaccept-handoff/v1',repository:'Luke883i/iKant_LE',source_head:sourceHead,terms_presented:true,terms_digest:terms.digest,frozen:true,breached:false,pending_intent:pending,pending_intent_sha256:sha256(Buffer.from(pending)),orientation_digests:Object.fromEntries(c.paths.map(rel=>[rel,sha256(fs.readFileSync(path.join(ROOT,rel)))])),runtime_observed_terms_presentation:false,host_attested_terms_presentation:true,authority:0};}
export function bootstrapEvidence({sourceHead='a'.repeat(40),elapsedBeforeRuntimeMs=10,mode='COLD_API',transferSchema='v1',flexMode='PINNED_GITHUB_ZIP'}={}){const b=JSON.parse(fs.readFileSync(path.join(ROOT,'BOOTSTRAP.json'),'utf8')),d=b.post_accept_fastboot.runtime_root;let transfer;if(transferSchema==='v2'){const objects=[{path:d.loader.path,blob_sha1:d.loader.blob_sha1},...d.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))];const warm=flexMode==='WARM_CACHE_EXACT',host=flexMode==='HOST_FILE_BRIDGE',zip=flexMode==='PINNED_GITHUB_ZIP';transfer=withReceipt({schema:'ikant-le-source-bound-transfer/v2',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,mode:flexMode,transport_authority:0,identity_authority:'CONTENT_ADDRESSING',exact_ref:true,bridge_observed:true,model_mediated_bytes:false,complete:true,bytes_exact:true,remote_objects:objects.map((x,i)=>({...x,sha256:(i%2?'b':'c').repeat(64),bytes:100+i})),remote_rounds:warm||host?0:1,remote_reads:warm||host?0:zip?1:objects.length,locator_pinned:['PINNED_PERMALINK','PINNED_GITHUB_ZIP'].includes(flexMode),archive_policy:zip?{selective_extract:true,path_safe:true,special_entries_rejected:true,duplicates_rejected:true,encrypted_entries_rejected:true}:null,host_readback_verified:host,cache_reopen_verified:warm,elapsed_ms:Math.max(0,elapsedBeforeRuntimeMs-1),authority:0});}else transfer=withReceipt({schema:'ikant-le-source-bound-transfer/v1',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,mode,transport:'GITHUB_API',exact_ref:true,bridge_observed:true,model_mediated_bytes:false,fallback_used:false,complete:true,bytes_exact:true,remote_rounds:mode==='WARM_CACHE_EXACT'?0:1,remote_reads:mode==='WARM_CACHE_EXACT'?0:b.post_accept_fastboot.remote_paths.length,cache_reopen_verified:mode==='WARM_CACHE_EXACT',elapsed_ms:Math.max(0,elapsedBeforeRuntimeMs-1),authority:0});const materialization=withReceipt({schema:'ikant-le-runtime-root-materialization/v1',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,loader_blob_sha1:d.loader.blob_sha1,transfer_receipt_sha256:transfer.receipt_sha256,member_count:d.member_count,source_bytes:d.source_bytes,shard_count:d.shards.length,reused_orientation_paths:[...b.post_accept_fastboot.reuse_preaccept_paths],atomic_publish:true,reopen_verified:true,authority:0});fs.mkdirSync(runtimePaths().dir,{recursive:true});fs.writeFileSync(path.join(runtimePaths().dir,'materialization.json'),JSON.stringify(materialization,null,2)+'\n',{mode:0o600});return withReceipt({schema:'ikant-le-chat-bootstrap-evidence/v1',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,deadline_origin:'I_ACCEPT',clock:'MONOTONIC',elapsed_before_runtime_ms:elapsedBeforeRuntimeMs,transfer_receipt_sha256:transfer.receipt_sha256,materialization_receipt_sha256:materialization.receipt_sha256,transfer,authority:0});}
export function bootstrapArgs(pending='inizializza',opts={}){const sourceHead=opts.sourceHead||'a'.repeat(40);return{preacceptHandoff:bootstrapHandoff(pending,sourceHead),postAcceptBootstrapEvidence:bootstrapEvidence({...opts,sourceHead})};}
