import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {readTerms} from '../src/contract.mjs';
import {runtimePaths,readLedger} from '../src/state.mjs';
import {runCommand,resumeActivation,validateTransferRemoteHistory} from '../src/runtime.mjs';
import {runtimeRootDescriptor} from '../src/runtime-root-verified.mjs';
import {bootstrapEvidence,bootstrapHandoff} from './bootstrap-fixture.mjs';
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
function resign(x){const y=structuredClone(x);delete y.receipt_sha256;return{...y,receipt_sha256:digest(y)}}
function reset(){fs.rmSync(runtimePaths().dir,{recursive:true,force:true})}
function bridgeGap(source){let e=bootstrapEvidence({sourceHead:source,elapsedBeforeRuntimeMs:10,transferSchema:'v2',flexMode:'GITHUB_API_BASE64'});fs.rmSync(path.join(runtimePaths().dir,'materialization.json'),{force:true});e.transfer.bridge_observed=false;e.transfer=resign(e.transfer);e.transfer_receipt_sha256=e.transfer.receipt_sha256;return resign(e)}
function continuationEvidence(source,state,elapsed=20000){let e=bootstrapEvidence({sourceHead:source,elapsedBeforeRuntimeMs:10,transferSchema:'v2',flexMode:'GITHUB_API_BASE64'});let c={schema:'ikant-le-activation-continuation/v1',acceptance_event_id:state.admission.acceptance_event_id,acceptance_origin_receipt_sha256:state.bootstrap.deadline_origin_receipt_sha256,source_head:source,terms_digest:readTerms().digest,remote_history_sha256:state.bootstrap.remote_history_sha256,clock:'MONOTONIC',observed_at_resume:true,no_new_remote_acquisition:true,elapsed_since_accept_ms:elapsed,authority:0};e.activation_continuation=resign(c);return resign(e)}
const probe=()=>({ok:true,node:'22.16.0',fs:'crud+append+readback+delete',crypto:'sha256',clock:'Date.now',artifact_sink:true,warm:false});
test('C18 bridge-only failure is DEGRADED and preserves remote history',{concurrency:false},()=>{reset();const source='a'.repeat(40),e=bridgeGap(source),root=runtimeRootDescriptor();const h=validateTransferRemoteHistory(e.transfer,{sourceHead:source,runtimeRootSha256:root.runtime_root_sha256,runtimeRootDescriptor:root});assert.equal(h.ok,true);assert.equal(runCommand('I ACCEPT',{preacceptHandoff:bootstrapHandoff('inizializza',source),postAcceptBootstrapEvidence:e,hostEngine:'GPT-TEST'}).code,1);const s=readLedger().at(-1).state_after;assert.equal(s.status,'DEGRADED');assert.equal(s.admission.acceptance_consumed,true);assert.equal(s.admission.new_chat_required,false);assert.equal(s.bootstrap.remote_history_sha256,h.remote_history_sha256);assert.equal(s.bootstrap.deadline_elapsed_ms,10);reset()});
test('C18 valid continuation reaches ACTIVE without resetting epoch/event/history',{concurrency:false},()=>{reset();const source='a'.repeat(40);runCommand('I ACCEPT',{preacceptHandoff:bootstrapHandoff('inizializza',source),postAcceptBootstrapEvidence:bridgeGap(source),hostEngine:'GPT-TEST'});const before=readLedger().at(-1).state_after,epoch=before.epoch,event=before.admission.acceptance_event_id,history=before.bootstrap.remote_history_sha256;let ticks=[100,105,110];const out=resumeActivation({postAcceptBootstrapEvidence:continuationEvidence(source,before,20000),probeRunner:probe,hostEngine:'GPT-TEST',monotonicNow:()=>ticks.shift()??110});assert.equal(out.code,0);const after=readLedger().at(-1).state_after;assert.equal(after.status,'ACTIVE');assert.equal(after.epoch,epoch);assert.equal(after.admission.acceptance_event_id,event);assert.equal(after.bootstrap.remote_history_sha256,history);assert.equal(after.admission.acceptance_consumed,true);assert.equal(after.bootstrap.deadline_result,'DEADLINE_PASS');reset()});
test('C18 second remote round is rejected without epoch reset',{concurrency:false},()=>{reset();const source='a'.repeat(40);runCommand('I ACCEPT',{preacceptHandoff:bootstrapHandoff('inizializza',source),postAcceptBootstrapEvidence:bridgeGap(source),hostEngine:'GPT-TEST'});const before=readLedger().at(-1).state_after,epoch=before.epoch;let e=continuationEvidence(source,before,20000);e.transfer.remote_rounds=2;e.transfer=resign(e.transfer);e.transfer_receipt_sha256=e.transfer.receipt_sha256;e=resign(e);assert.equal(resumeActivation({postAcceptBootstrapEvidence:e,probeRunner:probe,hostEngine:'GPT-TEST'}).code,1);const after=readLedger().at(-1).state_after;assert.equal(after.epoch,epoch);assert.notEqual(after.status,'ACTIVE');reset()});
test('C18 exceeded continuation deadline becomes sticky',{concurrency:false},()=>{reset();const source='a'.repeat(40);runCommand('I ACCEPT',{preacceptHandoff:bootstrapHandoff('inizializza',source),postAcceptBootstrapEvidence:bridgeGap(source),hostEngine:'GPT-TEST'});const before=readLedger().at(-1).state_after;assert.equal(resumeActivation({postAcceptBootstrapEvidence:continuationEvidence(source,before,120001),probeRunner:probe,hostEngine:'GPT-TEST'}).code,1);const after=readLedger().at(-1).state_after;assert.equal(after.status,'ADMISSION_EPOCH_UNRECOVERABLE');assert.equal(after.bootstrap.deadline_terminal,'DEADLINE_EXCEEDED');assert.equal(after.admission.new_chat_required,true);reset()});
test('C18 missing materialization remains non-ACTIVE in same epoch',{concurrency:false},()=>{reset();const source='a'.repeat(40);runCommand('I ACCEPT',{preacceptHandoff:bootstrapHandoff('inizializza',source),postAcceptBootstrapEvidence:bridgeGap(source),hostEngine:'GPT-TEST'});const before=readLedger().at(-1).state_after,epoch=before.epoch,e=continuationEvidence(source,before,20000);fs.rmSync(path.join(runtimePaths().dir,'materialization.json'),{force:true});assert.equal(resumeActivation({postAcceptBootstrapEvidence:e,probeRunner:probe,hostEngine:'GPT-TEST'}).code,1);const after=readLedger().at(-1).state_after;assert.equal(after.status,'DEGRADED');assert.equal(after.epoch,epoch);assert.equal(after.admission.new_chat_required,false);reset()});
