import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {deploySessionChatRuntime,openDeployedSession,acceptDeployedLimitedSession,runDeployedLimitedSessionTurn} from '../src/session-chat-deployment.mjs';
import {nodeDispatchReceiptPure,validateNodeDispatchReceipt} from '../src/runtime-dispatch.mjs';
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'ikant-le-c31-'));
const candidate=('Questa risposta appartiene al servizio runtime limitato e rimane esplicitamente non ACTIVE. '+'La capability e legata alla stessa sorgente, al runtime root materializzato, alla provenienza del codice eseguito e alla acceptance origin osservata. '+'Il dispatch Node viene generato dal runtime sul medesimo input, l output viene sigillato e il backlog DOCX viene pubblicato atomicamente e riletto. '+'La telemetria e calcolata da check effettivi, non modifica il ledger canonico e non dichiara alcun acknowledgement della piattaforma. '+'La sola promozione possibile resta il normale ACTIVE_READBACK del lifecycle canonico.');
test('C31 source-bound limited acceptance and turn close without canonical ledger',{concurrency:false},async()=>{
 const input0='input limitato',dispatch=nodeDispatchReceiptPure(input0,{epoch:'acceptance-event-x',status:'RUNTIME_BOUND_LIMITED'},{nodeVersion:'20.11.1',hostSurface:'TEST'});assert.deepEqual(validateNodeDispatchReceipt(dispatch,{input:input0,epoch:'acceptance-event-x',statusBefore:'RUNTIME_BOUND_LIMITED',hostSurface:'TEST'}),{ok:true,errors:[]});assert.equal(validateNodeDispatchReceipt({...dispatch,epoch:'acceptance-event-y'},{input:input0,epoch:'acceptance-event-x',statusBefore:'RUNTIME_BOUND_LIMITED',hostSurface:'TEST'}).ok,false);
 const d=temp(),deployment=path.join(d,'deploy');try{deploySessionChatRuntime({deploymentRoot:deployment,deploymentId:'D-C31'});assert.equal(openDeployedSession({deploymentRoot:deployment,sessionId:'CHAT-L'}).acceptance_required,true);const limited=await acceptDeployedLimitedSession({deploymentRoot:deployment,sessionId:'CHAT-L',humanInput:'I ACCEPT'});assert.equal(limited.state,'RUNTIME_BOUND_LIMITED');assert.equal(limited.active,false);assert.equal(limited.first_unclosed_edge,'ACTIVE_READBACK');const sessionDir=path.join(deployment,'sessions',fs.readdirSync(path.join(deployment,'sessions'))[0]),runtimeDir=path.join(sessionDir,'runtime');assert.equal(fs.existsSync(path.join(runtimeDir,'.ikant','ledger.jsonl')),false);const after=openDeployedSession({deploymentRoot:deployment,sessionId:'CHAT-L'});assert.equal(after.limited,true);assert.equal(after.acceptance_required,false);const turn=await runDeployedLimitedSessionTurn({deploymentRoot:deployment,sessionId:'CHAT-L',input:'Produci una risposta runtime limitata con backlog e telemetria verificabili.',candidate});assert.equal(turn.state,'RUNTIME_BOUND_LIMITED');assert.equal(turn.active,false);assert.equal(turn.canonical_state_mutation,false);assert.equal(turn.platform_ack_required,false);assert.equal(turn.artifacts.length,1);const a=turn.artifacts[0];assert.equal(a.atomic_publish,true);assert.equal(a.readback_verified,true);assert.match(a.name,/^iKant_LE_Limited_[a-f0-9]{64}\.docx$/);assert.ok(fs.existsSync(a.local_path));assert.equal(fs.existsSync(path.join(runtimeDir,'.ikant','ledger.jsonl')),false);}finally{fs.rmSync(d,{recursive:true,force:true});}
});
