import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {ROOT,sha256} from '../src/contract.mjs';
import {runtimeRootDescriptor,preRuntimeSelfCheck,executePreRuntimeBootstrap} from '../src/runtime-root-verified.mjs';
import {deriveActivationServiceTier} from '../src/runtime-availability.mjs';
import {buildSessionShell,validateSessionShell} from '../src/session-shell.mjs';
import {bootstrapHandoffV2} from './bootstrap-fixture.mjs';

function gitBlobSha1(bytes){const b=Buffer.isBuffer(bytes)?bytes:Buffer.from(bytes);return crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex');}
function executorReceipt(sourceHead,orientation){const d=runtimeRootDescriptor(),runtimeObjects=[{path:d.loader.path,blob_sha1:d.loader.blob_sha1},...d.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>{const b=fs.readFileSync(path.join(ROOT,x.path));return{...x,bytes:b.length};});const material={schema:'ikant-le-activation-executor/v1',repository:'Luke883i/iKant_LE',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,execution_plane:'SESSION_LOCAL_NODE',capability_probe_passed:true,capability_probe_before_acquisition:true,content_addressed:true,byte_path:'LOCAL_DIRECT',model_mediated_bytes:false,model_role:'NONE',model_rewrite_allowed:false,semantic_equivalence_allowed:false,source_arrival_samehash_required:true,source_arrival_samehash_verified:true,opaque_relay_roundtrip_verified:false,retry_semantics:'IDEMPOTENT_BY_OBJECT_IDENTITY',retry_count:0,acquisition_complete:true,orientation_objects:orientation.map(x=>({path:x.path,blob_sha1:x.blob_sha1,bytes:x.bytes})),runtime_objects:runtimeObjects,slo_elapsed_ms:5,authority:0};return{...material,receipt_sha256:sha256(Buffer.from(JSON.stringify(material)))};}

test('C33 strongest valid prefix survives orthogonal integrity fault while effective service fails closed',()=>{const x=deriveActivationServiceTier({accepted:true,source_snapshot:true,local_ingress:true,materialized_reopened:true,executed_provenance:true,runtime_bound:true,limited_writer:true,blocked_integrity:true});assert.equal(x.tier,null);assert.equal(x.strongest_valid_prefix,'RUNTIME_BOUND_LIMITED');assert.equal(x.active,false);assert.equal(x.fault_overlay,'BLOCKED_INTEGRITY');assert.equal(x.first_unclosed_edge,'ACTIVE_READBACK');});

test('C33 session shell cannot manufacture an intermediate tier from raw state booleans',()=>{const state={status:'DEGRADED',accepted:true,probed:true,admission:{terms_presented:true,source_head:'a'.repeat(40),source_head_locked:true,orientation_objects:Array(5).fill({})},bootstrap:{terminal:'DEGRADED',activation_executor_receipt_sha256:'b'.repeat(64),materialization_receipt_sha256:'c'.repeat(64),probe:{ok:true,fs:true,executed_provenance_receipt_sha256:'d'.repeat(64)}},experience:{turns:0,maturity_mode:'ORIENTING'},psyche:{last_runtime_outcome:'NONE'}};const shell=buildSessionShell({surfaceText:'Control',state});assert.equal(shell.status.tier,null);assert.equal(shell.status.display_status,'ACTIVATING');assert.equal(shell.voice_surface.voice_owner,'HOST_ADAPTER');assert.equal(validateSessionShell(shell).ok,true);});

test('C33 existing loader is the self-checked pre-runtime executable owner',()=>{const x=preRuntimeSelfCheck();assert.equal(x.ok,true);assert.equal(x.receipt.kernel_path,'src/runtime-root-verified.mjs');assert.equal(x.receipt.node20_plus,true);assert.equal(x.receipt.local_fs_write_reopen,true);assert.equal(x.receipt.local_exec,true);});

test('C33 exact I ACCEPT reaches materialized canonical local ingress and a real limited turn without ledger mutation',async()=>{const sourceHead='a'.repeat(40),handoff=bootstrapHandoffV2('inizializza iKant_LE',sourceHead),executor=executorReceipt(sourceHead,handoff.orientation_objects),parent=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c33-')),sink=path.join(parent,'runtime');try{const accepted=await executePreRuntimeBootstrap({workspace:ROOT,sink,sourceHead,preacceptHandoff:handoff,activationExecutor:executor,humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:performance.now()});assert.equal(accepted.runtime_state,'RUNTIME_BOUND_LIMITED');assert.equal(accepted.active,false);assert.equal(accepted.kernel_retired,true);assert.equal(fs.existsSync(path.join(sink,'.ikant','ledger.jsonl')),false);assert.equal(fs.existsSync(path.join(sink,'.ikant','limited-capability.json')),true);
 const svc=await import(pathToFileURL(path.join(sink,'src/session-local-service.mjs')).href+'?turn='+crypto.randomUUID());const candidate=('Questo output appartiene al runtime limitato verificato e conserva esplicitamente il confine con ACTIVE. '.repeat(8)).trim();const turn=await svc.runLocalLimitedTurn({input:'Spiega il confine operativo di questo tier.',candidate});assert.equal(turn.state,'RUNTIME_BOUND_LIMITED');assert.equal(turn.active,false);assert.equal(turn.canonical_state_mutation,false);assert.equal(turn.platform_ack_required,false);assert.equal(turn.session_shell.status.tier,'RUNTIME_BOUND_LIMITED');assert.equal(turn.session_shell.voice_surface.voice_owner,'IKANT_RUNTIME_LIMITED');assert.equal(turn.artifacts.length,1);assert.equal(turn.artifacts[0].readback_verified,true);assert.equal(turn.artifacts[0].atomic_publish,true);assert.equal(fs.existsSync(path.join(sink,'.ikant','ledger.jsonl')),false);
 }finally{fs.rmSync(parent,{recursive:true,force:true});}});

test('C33 kernel rejects tampered executor evidence and non-exact acceptance before runtime ownership',async()=>{const sourceHead='a'.repeat(40),handoff=bootstrapHandoffV2('inizializza',sourceHead),good=executorReceipt(sourceHead,handoff.orientation_objects),bad={...good,source_arrival_samehash_verified:false};delete bad.receipt_sha256;bad.receipt_sha256=sha256(Buffer.from(JSON.stringify(bad)));const p1=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c33-bad-')),p2=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c33-accept-'));try{await assert.rejects(()=>executePreRuntimeBootstrap({workspace:ROOT,sink:path.join(p1,'runtime'),sourceHead,preacceptHandoff:handoff,activationExecutor:bad,humanInput:'I ACCEPT'}),/activation executor receipt invalid/);await assert.rejects(()=>executePreRuntimeBootstrap({workspace:ROOT,sink:path.join(p2,'runtime'),sourceHead,preacceptHandoff:handoff,activationExecutor:good,humanInput:'I accept'}),/exact I ACCEPT/);}finally{fs.rmSync(p1,{recursive:true,force:true});fs.rmSync(p2,{recursive:true,force:true});}});

test('C33 compatibility deployment ingress remains explicitly noncanonical',()=>{const legacy=fs.readFileSync(new URL('../src/session-chat-deployment.mjs',import.meta.url),'utf8'),contract=JSON.parse(fs.readFileSync(new URL('../contracts/runtime-availability-dod.json',import.meta.url),'utf8'));assert.match(legacy,/LEGACY_C20_COMPATIBILITY_ONLY/);assert.equal(contract.limited_runtime_supply_chain.compatibility_ingress_is_canonical,false);assert.equal(contract.limited_runtime_supply_chain.canonical_local_ingress.runtime_owner,'src/session-local-service.mjs');});

test('C33 checked-in 1m receipt proves unique four-action minimum',()=>{const x=JSON.parse(fs.readFileSync(new URL('../artifacts/qualification/c33-post-187-closure-1m.json',import.meta.url),'utf8'));assert.equal(x.cases,1000000);assert.equal(x.winner_mask,15);assert.equal(x.winner_mismatch,0);assert.equal(x.winner_unsafe,0);assert.equal(x.winner_cost_ties,1);assert.equal(x.all_action_deletion_mutants_killed,true);assert.equal(x.status,'PASS');assert.equal(x.receipt_sha256,'6016498973002b21189704ecb386e02cc6e7a74ec8a665e9184818c037545ccb');});
