import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {ROOT,sha256} from '../src/contract.mjs';
import {runtimeRootDescriptor,materializeRuntimeRoot,preRuntimeSelfCheck} from '../src/runtime-root-verified.mjs';
import {bootstrapHandoffV2} from './bootstrap-fixture.mjs';

function executorReceipt(sourceHead,orientation){const d=runtimeRootDescriptor(),runtimeObjects=[{path:d.loader.path,blob_sha1:d.loader.blob_sha1},...d.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>{const b=fs.readFileSync(path.join(ROOT,x.path));return{...x,bytes:b.length};});const material={schema:'ikant-le-activation-executor/v1',repository:'Luke883i/iKant_LE',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,execution_plane:'SESSION_LOCAL_NODE',capability_probe_passed:true,capability_probe_before_acquisition:true,content_addressed:true,byte_path:'LOCAL_DIRECT',model_mediated_bytes:false,model_role:'NONE',model_rewrite_allowed:false,semantic_equivalence_allowed:false,source_arrival_samehash_required:true,source_arrival_samehash_verified:true,opaque_relay_roundtrip_verified:false,retry_semantics:'IDEMPOTENT_BY_OBJECT_IDENTITY',retry_count:0,acquisition_complete:true,orientation_objects:orientation.map(x=>({path:x.path,blob_sha1:x.blob_sha1,bytes:x.bytes})),runtime_objects:runtimeObjects,slo_elapsed_ms:5,authority:0};return{...material,receipt_sha256:sha256(Buffer.from(JSON.stringify(material)))};}
function sign(x){const y=structuredClone(x);delete y.receipt_sha256;return{...y,receipt_sha256:sha256(Buffer.from(JSON.stringify(y)))};}
function handoff({sourceHead,preaccept,executor,materialization,self}){const material={schema:'ikant-le-pre-runtime-handoff/v2',source_head:sourceHead,runtime_root_sha256:runtimeRootDescriptor().runtime_root_sha256,materialization_receipt_sha256:materialization.receipt_sha256,activation_executor_receipt_sha256:executor.receipt_sha256,kernel_self_check_receipt_sha256:self.receipt_sha256,preaccept_handoff_sha256:sha256(Buffer.from(JSON.stringify(preaccept))),preaccept_handoff:preaccept,activation_executor:executor,kernel_self_check:self,terms_object:preaccept.terms_object,acceptance_ingress:{human_input:'I ACCEPT',observed_monotonic_ms:performance.now(),authority:0},runtime_owner:'src/session-local-service.mjs',first_unclosed_edge:'ACTIVE_READBACK',active:false,authority:0};return sign(material);}

test('C34 runtime owner independently revalidates complete pre-runtime evidence before limited capability',async()=>{const sourceHead='a'.repeat(40),preaccept=bootstrapHandoffV2('inizializza iKant_LE',sourceHead),executor=executorReceipt(sourceHead,preaccept.orientation_objects),parent=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c34-')),sink=path.join(parent,'runtime');try{const mat=materializeRuntimeRoot({workspace:ROOT,sink,sourceHead,orientationObjects:preaccept.orientation_objects,preacceptHandoff:preaccept,activationExecutorReceiptSha256:executor.receipt_sha256}),self=preRuntimeSelfCheck({workspace:ROOT}).receipt,valid=handoff({sourceHead,preaccept,executor,materialization:mat,self}),svc=await import(pathToFileURL(path.join(sink,'src/session-local-service.mjs')).href+'?c34='+crypto.randomUUID());assert.equal(svc.validatePreRuntimeHandoff(valid).ok,true);
 const old=sign({...valid,schema:'ikant-le-pre-runtime-handoff/v1',preaccept_handoff:undefined,activation_executor:undefined,kernel_self_check:undefined});assert.equal(svc.validatePreRuntimeHandoff(old).ok,false);
 const badPre={...preaccept,frozen:false},preForged=sign({...valid,preaccept_handoff:badPre,preaccept_handoff_sha256:sha256(Buffer.from(JSON.stringify(badPre)))});assert.equal(svc.validatePreRuntimeHandoff(preForged).ok,false);
 const altExec=sign({...executor,retry_count:1}),execForged=sign({...valid,activation_executor:altExec,activation_executor_receipt_sha256:altExec.receipt_sha256});const ev=svc.validatePreRuntimeHandoff(execForged);assert.equal(ev.ok,false);assert.ok(ev.errors.includes('materialization_executor_binding'));
 const fakeSelf=sign({...self,local_exec:false}),selfForged=sign({...valid,kernel_self_check:fakeSelf,kernel_self_check_receipt_sha256:fakeSelf.receipt_sha256});assert.equal(svc.validatePreRuntimeHandoff(selfForged).ok,false);
 await assert.rejects(()=>svc.acceptLocalLimitedSession({handoff:execForged}),/pre-runtime handoff invalid/);assert.equal(fs.existsSync(path.join(sink,'.ikant','limited-capability.json')),false);assert.equal(fs.existsSync(path.join(sink,'.ikant','ledger.jsonl')),false);
 const accepted=await svc.acceptLocalLimitedSession({handoff:valid});assert.equal(accepted.state,'RUNTIME_BOUND_LIMITED');assert.equal(accepted.active,false);assert.equal(fs.existsSync(path.join(sink,'.ikant','limited-capability.json')),true);assert.equal(fs.existsSync(path.join(sink,'.ikant','ledger.jsonl')),false);
 }finally{fs.rmSync(parent,{recursive:true,force:true});}});

test('C34 checked-in 1m saturation requires all four independent handoff checks',()=>{const x=JSON.parse(fs.readFileSync(new URL('../artifacts/qualification/c34-pre-runtime-handoff-1m.json',import.meta.url),'utf8'));assert.equal(x.cases,1000000);assert.equal(x.winner_mask,15);assert.equal(x.winner_mismatch,0);assert.equal(x.winner_unsafe,0);assert.equal(x.winner_false_reject,0);assert.equal(x.winner_cost_ties,1);assert.equal(x.all_requirement_deletion_mutants_killed,true);assert.equal(x.status,'PASS');assert.equal(x.receipt_sha256,'d9c692419f3b0488402d672d5a8e7401f1981b41a741064f2a29ced7c59dcb67');});
