import test from 'node:test';
import assert from 'node:assert/strict';
import {buildFastbootChannelLedger,deriveFastbootStep,recordFastbootFailure} from '../src/fastboot-convergence.mjs';
import {buildSessionShell,renderSessionShell,validateSessionShell} from '../src/session-shell.mjs';
const sourceHead='a'.repeat(40),runtimeRoot='b'.repeat(64);
const preState=()=>({status:'DISCOVERED',accepted:true,admission:{terms_presented:true},bootstrap:{terminal:'ACTIVATING'},experience:{turns:0,maturity_mode:'ORIENTING'},psyche:{last_runtime_outcome:'NONE'}});
test('C39 pre-active shell renders canonical NEXT only from step recomputed against bound ledger',()=>{const ledger=buildFastbootChannelLedger({sourceHead,receipts:[]}),step=deriveFastbootStep({ledger,runtimeRootSha256:runtimeRoot}),shell=buildSessionShell({surfaceText:'Bootstrap control surface.',state:preState(),bootstrapStep:step,bootstrapLedger:ledger});assert.equal(shell.status.runtime_guidance.next_action,step.canonical_next);assert.equal(shell.status.runtime_guidance.first_unclosed_edge,'LOCAL_INGRESS');assert.equal(shell.status.runtime_guidance.retry_disposition,'EXECUTE_OR_PROBE_ONCE');assert.equal(validateSessionShell(shell).ok,true);const rendered=renderSessionShell(shell);assert.match(rendered,/Next: /);assert.match(rendered,/Edge: LOCAL_INGRESS/);assert.match(rendered,/Retry: EXECUTE_OR_PROBE_ONCE/);});
test('C39 unchanged failed decision becomes visible WAIT state rather than model retry',()=>{const ledger=buildFastbootChannelLedger({sourceHead,receipts:[]}),step=deriveFastbootStep({ledger,runtimeRootSha256:runtimeRoot}),failed=recordFastbootFailure(ledger,step),wait=deriveFastbootStep({ledger:failed,runtimeRootSha256:runtimeRoot}),shell=buildSessionShell({surfaceText:'Bootstrap control surface.',state:preState(),bootstrapStep:wait,bootstrapLedger:failed});assert.equal(wait.action,'WAIT_CHANGED_EVIDENCE');assert.equal(shell.status.runtime_guidance.retry_disposition,'WAIT_FOR_CHANGED_EVIDENCE');assert.match(renderSessionShell(shell),/Blocker: UNCHANGED_DECISION_EVIDENCE_DO_NOT_RETRY/);});
test('C39 shell rejects forged NEXT and hides stale bootstrap guidance after ACTIVE ownership',()=>{const ledger=buildFastbootChannelLedger({sourceHead,receipts:[]}),step=deriveFastbootStep({ledger,runtimeRootSha256:runtimeRoot}),forged={...step,canonical_next:'EXECUTE:FORGED'};assert.throws(()=>buildSessionShell({surfaceText:'x',state:preState(),bootstrapStep:forged,bootstrapLedger:ledger}),/bootstrap guidance evidence invalid/);const activeState={status:'ACTIVE',accepted:true,probed:true,bootstrap:{terminal:'ACTIVE'},experience:{turns:0,maturity_mode:'ORIENTING'},psyche:{last_runtime_outcome:'NONE'}},active=buildSessionShell({surfaceText:'Runtime surface.',state:activeState,bootstrapStep:step,bootstrapLedger:ledger});assert.equal(active.status.active,true);assert.equal(active.status.runtime_guidance,null);assert.doesNotMatch(renderSessionShell(active),/Next: /);});
