import test from 'node:test';
import assert from 'node:assert/strict';
import {FASTBOOT_ATTEMPT_SCHEMA,FASTBOOT_CAPABILITY_FIELDS,FASTBOOT_OBSERVATION_TRANSITION_SCHEMA,advanceFastbootObservation,buildFastbootChannelLedger,deriveFastbootStep,fastbootReceiptDigest,issueFastbootCapabilityReceipt,recordFastbootFailure,validateFastbootObservationTransition} from '../src/fastboot-convergence.mjs';
import {runtimeRootDescriptor} from '../src/runtime-root-verified.mjs';
import {for_ai_agent_first_entrypoint} from '../src/local-host-meta-prompt.mjs';
const HEAD='a'.repeat(40),EVENT='evt-c40',D=runtimeRootDescriptor(),ROOT=D.runtime_root_sha256,proven=()=>Object.fromEntries(FASTBOOT_CAPABILITY_FIELDS.map(k=>[k,true]));
const sign=x=>{const y=structuredClone(x);delete y.receipt_sha256;return{...y,receipt_sha256:fastbootReceiptDigest(y)}};
function failedAttempt(step,result='FAILED'){return sign({schema:FASTBOOT_ATTEMPT_SCHEMA,attempt_id:'c40-'+result.toLowerCase(),carrier:step.canonical_carrier,acceptance_event_id:EVENT,source_head:HEAD,runtime_root_sha256:ROOT,result,source_object_identity:result==='PARTIAL'?'partial-source':null,runtime_sink_object_id:result==='PARTIAL'?'partial-sink':null,remote_objects:result==='PARTIAL'?[{path:D.loader.path,blob_sha1:D.loader.blob_sha1,sha256:'c'.repeat(64),bytes:1}]:[],remote_reads:result==='PARTIAL'?1:0,bytes_observed:result==='PARTIAL'?1:0,source_fetch_observed:result==='PARTIAL',byte_preserving_runtime_sink_observed:result==='PARTIAL',runtime_materializer_bound:true,runtime_executor_bound:true,model_mediated_bytes:false,authoritative_remote_history:false,committed_remote_rounds:0,transfer_receipt_sha256:null,authority:0})}
function completeAttempt(step){const objects=[{path:D.loader.path,blob_sha1:D.loader.blob_sha1},...D.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>({...x,sha256:'d'.repeat(64),bytes:1}));return sign({schema:FASTBOOT_ATTEMPT_SCHEMA,attempt_id:'c40-complete',carrier:step.canonical_carrier,acceptance_event_id:EVENT,source_head:HEAD,runtime_root_sha256:ROOT,result:'COMPLETE',source_object_identity:'source-complete',runtime_sink_object_id:'sink-complete',remote_objects:objects,remote_reads:objects.length,bytes_observed:objects.length,source_fetch_observed:true,byte_preserving_runtime_sink_observed:true,runtime_materializer_bound:true,runtime_executor_bound:true,model_mediated_bytes:false,authoritative_remote_history:false,committed_remote_rounds:0,transfer_receipt_sha256:'e'.repeat(64),authority:0})}
test('C40 ledger failure memory advances to a distinct carrier without caller attempted classes',()=>{const cap=issueFastbootCapabilityReceipt({carrier:'GITHUB_API_BASE64',status:'AVAILABLE',capabilities:proven(),evidence:'available',probeOwner:'c40',operationId:'exec',sourceHead:HEAD}),ledger=buildFastbootChannelLedger({receipts:[cap],sourceHead:HEAD}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),failed=recordFastbootFailure(ledger,step),next=deriveFastbootStep({ledger:failed,runtimeRootSha256:ROOT});assert.equal(step.canonical_carrier,'GITHUB_API_BASE64');assert.notEqual(next.canonical_carrier,step.canonical_carrier);assert.equal(next.retry_allowed,true);});
test('C40 typed probe evidence re-enters the same owner and yields the next canonical step',()=>{const ledger=buildFastbootChannelLedger({sourceHead:HEAD,receipts:[]}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),receipt=issueFastbootCapabilityReceipt({carrier:step.canonical_carrier,status:'UNAVAILABLE',capabilities:{...proven(),surface_supported:false},evidence:'not available',probeOwner:'c40',operationId:'probe',sourceHead:HEAD}),cycle=advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:receipt});assert.equal(cycle.schema,FASTBOOT_OBSERVATION_TRANSITION_SCHEMA);assert.equal(cycle.disposition,'PROBE_EVIDENCE_ACCEPTED');assert.notEqual(cycle.next_step.canonical_carrier,step.canonical_carrier);assert.equal(validateFastbootObservationTransition(cycle,{sourceHead:HEAD,runtimeRootSha256:ROOT}).ok,true);});
test('C40 failed and partial execute receipts advance only to a distinct carrier',()=>{for(const result of ['FAILED','PARTIAL']){const cap=issueFastbootCapabilityReceipt({carrier:'GITHUB_API_BASE64',status:'AVAILABLE',capabilities:proven(),evidence:'available-'+result,probeOwner:'c40',operationId:'exec-'+result,sourceHead:HEAD}),ledger=buildFastbootChannelLedger({receipts:[cap],sourceHead:HEAD}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),cycle=advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:failedAttempt(step,result),runtimeRootDescriptor:D,acceptanceEventId:EVENT});assert.equal(cycle.disposition,'DISTINCT_RETRY_REQUIRED');assert.notEqual(cycle.next_step.canonical_carrier,step.canonical_carrier);assert.equal(cycle.handoff,null);}});
test('C40/C41 changed evidence for the failed carrier may requalify it',()=>{const cap=issueFastbootCapabilityReceipt({carrier:'GITHUB_API_BASE64',status:'AVAILABLE',capabilities:proven(),evidence:'available-a',probeOwner:'c40',operationId:'exec-a',sourceHead:HEAD}),ledger=buildFastbootChannelLedger({receipts:[cap],sourceHead:HEAD}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),failed=recordFastbootFailure(ledger,step),changedReceipt=issueFastbootCapabilityReceipt({carrier:'GITHUB_API_BASE64',status:'AVAILABLE',capabilities:proven(),evidence:'changed-same-carrier',probeOwner:'c40',operationId:'same-carrier',sourceHead:HEAD}),changed=buildFastbootChannelLedger({previous:failed,receipts:[changedReceipt],sourceHead:HEAD}),replanned=deriveFastbootStep({ledger:changed,runtimeRootSha256:ROOT});assert.equal(replanned.canonical_carrier,'GITHUB_API_BASE64');});
test('C40 complete execute receipt hands off pre-runtime and cannot claim ACTIVE',()=>{const cap=issueFastbootCapabilityReceipt({carrier:'GITHUB_API_BASE64',status:'AVAILABLE',capabilities:proven(),evidence:'available-complete',probeOwner:'c40',operationId:'complete',sourceHead:HEAD}),ledger=buildFastbootChannelLedger({receipts:[cap],sourceHead:HEAD}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),cycle=advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:completeAttempt(step),runtimeRootDescriptor:D,acceptanceEventId:EVENT});assert.equal(cycle.disposition,'HANDOFF_PRE_RUNTIME');assert.equal(cycle.next_step,null);assert.equal(cycle.handoff.owner,'PRE_RUNTIME_HOST_ADAPTER');assert.equal(cycle.handoff.active_claim,false);assert.equal(cycle.active_claim,false);});
test('C40 mismatched or untyped observations fail closed',()=>{const ledger=buildFastbootChannelLedger({sourceHead:HEAD,receipts:[]}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),wrong=issueFastbootCapabilityReceipt({carrier:'HOST_FILE_BRIDGE',status:'UNAVAILABLE',capabilities:{...proven(),surface_supported:false},evidence:'wrong carrier',probeOwner:'c40',operationId:'wrong',sourceHead:HEAD});assert.notEqual(wrong.carrier,step.canonical_carrier);assert.throws(()=>advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:wrong}),/carrier mismatch/);assert.throws(()=>advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:{ok:false}}),/typed fastboot observation required/);assert.throws(()=>for_ai_agent_first_entrypoint({channel_ledger:ledger,runtime_root_sha256:ROOT,attempted_classes:['WARM_CACHE_EXACT']}),/ledger owns retry memory/);});
