import test from 'node:test';
import assert from 'node:assert/strict';
import {FASTBOOT_ATTEMPT_SCHEMA,FASTBOOT_CAPABILITY_FIELDS,advanceFastbootObservation,buildFastbootChannelLedger,deriveFastbootStep,fastbootObservationTransitionDigest,fastbootReceiptDigest,issueFastbootCapabilityReceipt,recordFastbootFailure,validateFastbootChannelLedger,validateFastbootObservationTransition,validateFastbootStep} from '../src/fastboot-convergence.mjs';
import {runtimeRootDescriptor} from '../src/runtime-root-verified.mjs';
import {buildSessionShell,renderSessionShell,validateSessionShell} from '../src/session-shell.mjs';

const HEAD='a'.repeat(40),EVENT='evt-c41',D=runtimeRootDescriptor(),ROOT=D.runtime_root_sha256,proven=()=>Object.fromEntries(FASTBOOT_CAPABILITY_FIELDS.map(k=>[k,true]));
const preState=()=>({status:'DISCOVERED',accepted:true,admission:{terms_presented:true},bootstrap:{terminal:'ACTIVATING'},experience:{turns:0,maturity_mode:'ORIENTING'},psyche:{last_runtime_outcome:'NONE'}});
const sign=x=>{const y=structuredClone(x);delete y.receipt_sha256;return{...y,receipt_sha256:fastbootReceiptDigest(y)}};
const resignTransition=x=>({...x,receipt_sha256:fastbootObservationTransitionDigest(x)});
function available(carrier='GITHUB_API_BASE64',evidence='available'){return issueFastbootCapabilityReceipt({carrier,status:'AVAILABLE',capabilities:proven(),evidence,probeOwner:'c41',operationId:'op-'+evidence,sourceHead:HEAD});}
function unavailable(carrier,evidence){return issueFastbootCapabilityReceipt({carrier,status:'UNAVAILABLE',capabilities:{...proven(),surface_supported:false},evidence,probeOwner:'c41',operationId:'op-'+evidence,sourceHead:HEAD});}
function baseFailure(){const ledger=buildFastbootChannelLedger({receipts:[available()],sourceHead:HEAD}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),failed=recordFastbootFailure(ledger,step);return{ledger,step,failed};}
function completeAttempt(step){const objects=[{path:D.loader.path,blob_sha1:D.loader.blob_sha1},...D.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>({...x,sha256:'d'.repeat(64),bytes:1}));return sign({schema:FASTBOOT_ATTEMPT_SCHEMA,attempt_id:'c41-complete',carrier:step.canonical_carrier,acceptance_event_id:EVENT,source_head:HEAD,runtime_root_sha256:ROOT,result:'COMPLETE',source_object_identity:'source-complete',runtime_sink_object_id:'sink-complete',remote_objects:objects,remote_reads:objects.length,bytes_observed:objects.length,source_fetch_observed:true,byte_preserving_runtime_sink_observed:true,runtime_materializer_bound:true,runtime_executor_bound:true,model_mediated_bytes:false,authoritative_remote_history:false,committed_remote_rounds:0,transfer_receipt_sha256:'e'.repeat(64),authority:0})}
function completeCycle(){const ledger=buildFastbootChannelLedger({receipts:[available()],sourceHead:HEAD}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),cycle=advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:completeAttempt(step),runtimeRootDescriptor:D,acceptanceEventId:EVENT});return{ledger,step,cycle};}

test('C41 canonical step and Session Shell reject caller-owned retry memory',()=>{const ledger=buildFastbootChannelLedger({sourceHead:HEAD,receipts:[]});assert.throws(()=>deriveFastbootStep({ledger,runtimeRootSha256:ROOT,attemptedClasses:['WARM_CACHE_EXACT']}),/ledger owns retry memory/);const step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT});assert.equal(validateFastbootStep(step,{sourceHead:HEAD,runtimeRootSha256:ROOT,ledger,attemptedClasses:['WARM_CACHE_EXACT']}).ok,false);assert.throws(()=>buildSessionShell({surfaceText:'x',state:preState(),bootstrapStep:step,bootstrapLedger:ledger,attemptedClasses:['WARM_CACHE_EXACT']}),/ledger owns retry memory/);});

test('C41 failure memory is carrier-local: unrelated evidence cannot requalify, same-carrier evidence can',()=>{const {step,failed}=baseFailure(),row=failed.failed_decisions[0];assert.match(row.carrier_evidence_sha256,/^[a-f0-9]{64}$/);assert.equal(failed.failure_memory_scope,'CARRIER_LOCAL_CHANNEL_EVIDENCE');const unrelated=buildFastbootChannelLedger({previous:failed,receipts:[unavailable('WARM_CACHE_EXACT','unrelated-change')],sourceHead:HEAD}),stillExcluded=deriveFastbootStep({ledger:unrelated,runtimeRootSha256:ROOT});assert.notEqual(stillExcluded.canonical_carrier,step.canonical_carrier);const related=buildFastbootChannelLedger({previous:failed,receipts:[available('GITHUB_API_BASE64','related-change')],sourceHead:HEAD}),requalified=deriveFastbootStep({ledger:related,runtimeRootSha256:ROOT});assert.equal(requalified.canonical_carrier,step.canonical_carrier);});

test('C41 canonical ledger rejects failure memory without carrier-local epoch',()=>{const {failed}=baseFailure(),forged=structuredClone(failed);delete forged.failed_decisions[0].carrier_evidence_sha256;delete forged.receipt_sha256;forged.receipt_sha256=fastbootReceiptDigest(forged);const v=validateFastbootChannelLedger(forged,{sourceHead:HEAD});assert.equal(v.ok,false);assert.ok(v.errors.includes('failure_memory'));});

test('C41 complete Fastboot route is digest-bound and cannot claim ACTIVE',()=>{const {cycle}=completeCycle();assert.equal(validateFastbootObservationTransition(cycle,{sourceHead:HEAD,runtimeRootSha256:ROOT}).ok,true);assert.equal(cycle.handoff.action,'EXECUTE_PRE_RUNTIME_BOOTSTRAP');assert.equal(cycle.active_claim,false);for(const mutate of [
 x=>{x.handoff.action='FORGED_ACTION'},
 x=>{x.handoff.owner='FORGED_OWNER';x.handoff_owner='FORGED_OWNER'},
 x=>{x.handoff.attempt_receipt_sha256='f'.repeat(64)},
 x=>{x.handoff.active_claim=true},
 x=>{x.handoff.authority=1}
]){const forged=structuredClone(cycle);mutate(forged);const resigned=resignTransition(forged);assert.equal(validateFastbootObservationTransition(resigned,{sourceHead:HEAD,runtimeRootSha256:ROOT}).ok,false);}});

test('C41 Session Shell projects complete transition continuously into LOCAL_MATERIALIZATION',()=>{const {cycle}=completeCycle(),shell=buildSessionShell({surfaceText:'Bootstrap control surface.',state:preState(),bootstrapTransition:cycle});assert.equal(shell.status.runtime_guidance.source,'VALIDATED_FASTBOOT_TRANSITION');assert.equal(shell.status.runtime_guidance.next_action,'EXECUTE_PRE_RUNTIME_BOOTSTRAP');assert.equal(shell.status.runtime_guidance.first_unclosed_edge,'LOCAL_MATERIALIZATION');assert.equal(shell.status.runtime_guidance.retry_disposition,'OWNER_HANDOFF_ONCE');assert.equal(shell.status.active,false);assert.equal(validateSessionShell(shell).ok,true);const rendered=renderSessionShell(shell);assert.match(rendered,/Next: EXECUTE_PRE_RUNTIME_BOOTSTRAP/);assert.match(rendered,/Edge: LOCAL_MATERIALIZATION/);});

test('C41 Session Shell accepts a validated re-entry transition NEXT and rejects mixed or forged guidance',()=>{const ledger=buildFastbootChannelLedger({sourceHead:HEAD,receipts:[]}),step=deriveFastbootStep({ledger,runtimeRootSha256:ROOT}),receipt=unavailable(step.canonical_carrier,'probe-unavailable'),cycle=advanceFastbootObservation({ledger,runtimeRootSha256:ROOT,observation:receipt}),shell=buildSessionShell({surfaceText:'Bootstrap control surface.',state:preState(),bootstrapTransition:cycle});assert.equal(shell.status.runtime_guidance.next_action,cycle.next_step.canonical_next);assert.equal(shell.status.runtime_guidance.first_unclosed_edge,'LOCAL_INGRESS');assert.equal(validateSessionShell(shell).ok,true);assert.throws(()=>buildSessionShell({surfaceText:'x',state:preState(),bootstrapStep:step,bootstrapLedger:ledger,bootstrapTransition:cycle}),/one bootstrap guidance source/);const {cycle:complete}=completeCycle(),forged=structuredClone(complete);forged.handoff.action='FORGED_ACTION';forged.receipt_sha256=fastbootObservationTransitionDigest(forged);assert.throws(()=>buildSessionShell({surfaceText:'x',state:preState(),bootstrapTransition:forged}),/transition guidance invalid/);});

test('C41 ACTIVE ownership hides both step and transition bootstrap guidance',()=>{const {cycle}=completeCycle(),activeState={status:'ACTIVE',accepted:true,probed:true,bootstrap:{terminal:'ACTIVE'},experience:{turns:0,maturity_mode:'ORIENTING'},psyche:{last_runtime_outcome:'NONE'}},shell=buildSessionShell({surfaceText:'Runtime surface.',state:activeState,bootstrapTransition:cycle});assert.equal(shell.status.active,true);assert.equal(shell.status.runtime_guidance,null);assert.doesNotMatch(renderSessionShell(shell),/Next: /);});
