import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {ROOT} from '../src/contract.mjs';import {buildFastbootChannelLedger} from '../src/fastboot-convergence.mjs';import {for_ai_agent_first_entrypoint,renderLocalHostMetaPrompt} from '../src/local-host-meta-prompt.mjs';import {ASCII_SHELL_WIDTH,buildSessionShell,readSessionStyleContext,renderBootstrapAsciiShell,renderSessionShell,validateSessionShell} from '../src/session-shell.mjs';const boot=JSON.parse(fs.readFileSync(path.join(ROOT,'BOOTSTRAP.json'),'utf8')),base={status:'ORIENTING',accepted:false,probed:false,admission:{terms_presented:false,source_head:null,source_head_locked:false,orientation_objects:[]},bootstrap:{terminal:'UNVERIFIED',probe:null},experience:{turns:0,maturity_mode:'ORIENTING'},psyche:{last_runtime_outcome:'NONE'}};

test('C44 prompt methodology',()=>{const p=renderLocalHostMetaPrompt();assert.match(p,/owner-returned necessari alla re-entry/);assert.match(p,/solo tramite un meccanismo tipizzato disponibile/);assert.match(p,/shell ASCII owner-rendered/);assert.doesNotMatch(p,/FASTBOOT_CHANNEL_LEDGER|failure_taxonomy|stile_comunicativo\.md/)});

test('C44 registries remain owner-owned',()=>{const m=boot.for_ai_agent_first_entrypoint.methodology;assert.equal(m.new_registry,false);assert.equal(m.conversation_is_retry_memory,false);assert.equal(m.on_impediment,'REENTER_ENTRYPOINT_REQUEST_NEXT');assert.equal(m.owner_selected_retry_only,true);assert.equal(m.tool_error_is_carrier_fact,false)});

test('C44 style context runtime member',()=>{const r=readSessionStyleContext();assert.equal(r.path,'stile_comunicativo.md');assert.equal(r.effect,'VOICE_STYLE_ONLY');assert.equal(r.authority,0);assert.match(r.sha256,/^[a-f0-9]{64}$/);assert.ok(boot.post_accept_fastboot.runtime_root.members.some(x=>x.path==='stile_comunicativo.md'))});

test('C44 bootstrap ASCII shell',()=>{const l=buildFastbootChannelLedger({sourceHead:'a'.repeat(40),receipts:[]}),x=for_ai_agent_first_entrypoint({channel_ledger:l,runtime_root_sha256:boot.post_accept_fastboot.runtime_root.runtime_root_sha256});assert.match(x.readiness.public_shell,/BOOTSTRAP/);for(const line of x.readiness.public_shell.split('\n'))assert.equal(line.length,ASCII_SHELL_WIDTH)});

test('C44 runtime ASCII shell',()=>{const s=buildSessionShell({surfaceText:'Risposta di prova',state:base});assert.equal(validateSessionShell(s).ok,true);const o=renderSessionShell(s);assert.match(o,/Status: READ_REPO_ONLY/);assert.match(o,/Backlog e telemetria/);assert.match(o,/stile_comunicativo\.md/);for(const line of o.split('\n'))assert.equal(line.length,ASCII_SHELL_WIDTH);assert.match(renderBootstrapAsciiShell('iKant · VERIFICA'),/iKant · VERIFICA/)});
