import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {ROOT,sha256} from '../src/contract.mjs';
import {runtimeRootDescriptor,issuePreRuntimeBindNucleus,reopenPreRuntimeBindNucleus,buildPreRuntimeBindFrame,executePreRuntimeBootstrapFromBind} from '../src/runtime-root-verified.mjs';
import {bindCohostContextRoot} from '../src/cohost-context-root.mjs';
import {PARTICIPATION_LEASE_SCHEMA,ATTRIBUTED_DELIVERY_SCHEMA} from '../src/cohost-root-qualification.mjs';
import {qualifyColdstartCohostRoot,COHOST_COLDSTART_COMMON_SHA} from '../src/cohost-coldstart-qualification.mjs';
import {bootstrapHandoffV2} from './bootstrap-fixture.mjs';
const sign=x=>({...x,receipt_sha256:crypto.createHash('sha256').update(Buffer.from(JSON.stringify(x))).digest('hex')});
function executorReceipt(sourceHead,orientation){const d=runtimeRootDescriptor(),objects=[{path:d.loader.path,blob_sha1:d.loader.blob_sha1},...d.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>{const b=fs.readFileSync(path.join(ROOT,x.path));return{...x,bytes:b.length};});const body={schema:'ikant-le-activation-executor/v1',repository:'Luke883i/iKant_LE',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,execution_plane:'SESSION_LOCAL_NODE',capability_probe_passed:true,capability_probe_before_acquisition:true,content_addressed:true,byte_path:'LOCAL_DIRECT',model_mediated_bytes:false,model_role:'NONE',model_rewrite_allowed:false,semantic_equivalence_allowed:false,source_arrival_samehash_required:true,source_arrival_samehash_verified:true,opaque_relay_roundtrip_verified:false,retry_semantics:'IDEMPOTENT_BY_OBJECT_IDENTITY',retry_count:0,acquisition_complete:true,orientation_objects:orientation.map(x=>({path:x.path,blob_sha1:x.blob_sha1,bytes:x.bytes})),runtime_objects:objects,slo_elapsed_ms:5,authority:0};return sign(body);}
function hostEvidence(bind,frame){const lease=sign({schema:PARTICIPATION_LEASE_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:bind.session_locator_sha256,actor:'IKANT',current_turn_entitlement:true,persistent_route:true,no_manual_reselection:true,host_route_guard:true,authority:0});const native=sign({schema:'ikant-le-cohost-native-delivery-receipt/v1',observation_owner:'HOST_NATIVE_CHAT',observed:true,surface:'NATIVE_CHAT',platform_roundtrip_id:'bind-1',session_locator_sha256:bind.session_locator_sha256,shell_receipt_sha256:frame.shell_receipt_sha256,ascii_sha256:frame.ascii_sha256,ascii_bytes:frame.ascii_bytes,envelope_receipt_sha256:frame.receipt_sha256,authority:0});const attributed=sign({schema:ATTRIBUTED_DELIVERY_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:bind.session_locator_sha256,turn_id:'BIND-1',actor:'IKANT',exact_runtime_bytes:true,native_delivery_receipt_sha256:native.receipt_sha256,authority:0});return{lease,native,attributed};}
test('C46 B0 binds before any full runtime directory exists',()=>{const sourceHead='a'.repeat(40),handoff=bootstrapHandoffV2('inizializza',sourceHead),root=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c46-'));try{const bind=issuePreRuntimeBindNucleus({workspace:ROOT,storageRoot:root,hostSessionId:'CHAT-46',sourceHead,preacceptHandoff:handoff,humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:10});assert.equal(bind.full_runtime_hydrated,false);assert.equal(bind.target_full_runtime_bound,true);const again=reopenPreRuntimeBindNucleus({workspace:ROOT,storageRoot:root,hostSessionId:'CHAT-46',sourceHead,preacceptHandoff:handoff});assert.equal(again.receipt_sha256,bind.receipt_sha256);const runtimeDir=path.join(root,'sessions',bind.session_locator_sha256,'runtime');assert.equal(fs.existsSync(runtimeDir),false);const frame=buildPreRuntimeBindFrame(bind),h=hostEvidence(bind,frame),q=qualifyColdstartCohostRoot({bindNucleus:bind,participationLease:h.lease,attributedDelivery:h.attributed,envelope:frame,nativeReceipt:h.native});assert.equal(q.common_semantic_sha256,COHOST_COLDSTART_COMMON_SHA);assert.equal(q.state,'COHOST_SAME_SESSION');assert.equal(q.runtime_capability_tier,'BIND_NUCLEUS');assert.equal(q.full_runtime_hydration_required_for_relation,false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('C46 hydration upgrades capability without changing cohost relation or session identity',async()=>{const sourceHead='a'.repeat(40),handoff=bootstrapHandoffV2('inizializza',sourceHead),root=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c46-up-'));try{const bind=issuePreRuntimeBindNucleus({workspace:ROOT,storageRoot:root,hostSessionId:'CHAT-UP',sourceHead,preacceptHandoff:handoff,humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:11}),frame=buildPreRuntimeBindFrame(bind),h=hostEvidence(bind,frame),before=qualifyColdstartCohostRoot({bindNucleus:bind,participationLease:h.lease,attributedDelivery:h.attributed,envelope:frame,nativeReceipt:h.native});const out=await executePreRuntimeBootstrapFromBind({workspace:ROOT,storageRoot:root,hostSessionId:'CHAT-UP',sourceHead,preacceptHandoff:handoff,activationExecutor:executorReceipt(sourceHead,handoff.orientation_objects),humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:12});assert.equal(out.bind_nucleus_receipt_sha256,bind.receipt_sha256);assert.equal(out.session_locator_sha256,bind.session_locator_sha256);const context=bindCohostContextRoot({storageRoot:root,hostSessionId:'CHAT-UP',sourceHead,runtimeRootSha256:bind.runtime_root_sha256}),after=qualifyColdstartCohostRoot({bindNucleus:bind,contextReadback:context,participationLease:h.lease,attributedDelivery:h.attributed,envelope:frame,nativeReceipt:h.native});assert.equal(before.state,'COHOST_SAME_SESSION');assert.equal(after.state,'COHOST_SAME_SESSION');assert.equal(before.runtime_capability_tier,'BIND_NUCLEUS');assert.equal(after.runtime_capability_tier,'FULL_OR_LIMITED_RUNTIME');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('C46 cannot substitute full hydration, compression or raw host booleans for the four-node root',()=>{const q=qualifyColdstartCohostRoot({bindNucleus:{},participationLease:{},attributedDelivery:{}});assert.notEqual(q.state,'COHOST_SAME_SESSION');assert.equal(q.physical_host_capability_created,false);});
