import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {ROOT} from '../src/contract.mjs';
import {runtimeRootDescriptor,issuePreRuntimeBindNucleus,executePreRuntimeBootstrapFromBind,reopenCohostHydrationUpgradeReceipt,validateCohostHydrationUpgradeReceipt} from '../src/runtime-root-verified.mjs';
import {reopenCohostContextRoot} from '../src/cohost-context-root.mjs';
import {bootstrapHandoffV2} from './bootstrap-fixture.mjs';
const sign=x=>({...x,receipt_sha256:crypto.createHash('sha256').update(Buffer.from(JSON.stringify(x))).digest('hex')});
function executorReceipt(sourceHead,orientation){const d=runtimeRootDescriptor(),objects=[{path:d.loader.path,blob_sha1:d.loader.blob_sha1},...d.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>{const b=fs.readFileSync(path.join(ROOT,x.path));return{...x,bytes:b.length};});return sign({schema:'ikant-le-activation-executor/v1',repository:'Luke883i/iKant_LE',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,execution_plane:'SESSION_LOCAL_NODE',capability_probe_passed:true,capability_probe_before_acquisition:true,content_addressed:true,byte_path:'LOCAL_DIRECT',model_mediated_bytes:false,model_role:'NONE',model_rewrite_allowed:false,semantic_equivalence_allowed:false,source_arrival_samehash_required:true,source_arrival_samehash_verified:true,opaque_relay_roundtrip_verified:false,retry_semantics:'IDEMPOTENT_BY_OBJECT_IDENTITY',retry_count:0,acquisition_complete:true,orientation_objects:orientation.map(x=>({path:x.path,blob_sha1:x.blob_sha1,bytes:x.bytes})),runtime_objects:objects,slo_elapsed_ms:5,authority:0});}
test('C47 persists and reopens bind-to-runtime upgrade and C45 context',async()=>{const sourceHead='a'.repeat(40),handoff=bootstrapHandoffV2('inizializza',sourceHead),root=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c47-'));try{const bind=issuePreRuntimeBindNucleus({workspace:ROOT,storageRoot:root,hostSessionId:'CHAT-C47',sourceHead,preacceptHandoff:handoff,humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:20});const out=await executePreRuntimeBootstrapFromBind({workspace:ROOT,storageRoot:root,hostSessionId:'CHAT-C47',sourceHead,preacceptHandoff:handoff,activationExecutor:executorReceipt(sourceHead,handoff.orientation_objects),humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:21});assert.equal(out.bind_nucleus_receipt_sha256,bind.receipt_sha256);assert.ok(out.hydration_upgrade_receipt_sha256);const context=reopenCohostContextRoot({storageRoot:root,hostSessionId:'CHAT-C47'}),upgrade=reopenCohostHydrationUpgradeReceipt({storageRoot:root,hostSessionId:'CHAT-C47',bindNucleus:bind,bootstrapResult:out,contextReadback:context});assert.equal(validateCohostHydrationUpgradeReceipt(upgrade,{bindNucleus:bind,bootstrapResult:out,contextReadback:context}).ok,true);assert.equal(upgrade.cohost_relation_changed,false);assert.equal(upgrade.runtime_capability_upgraded,true);assert.equal(context.session_locator_sha256,bind.session_locator_sha256);assert.equal(context.routable,true);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('C47 exact-main workflow is explicit without requiring all PR workflows on main',()=>{const text=fs.readFileSync(path.join(ROOT,'.github/workflows/c46-fast-cohost-bind.yml'),'utf8');assert.match(text,/push:\n    branches: \[main\]/);const c=JSON.parse(fs.readFileSync(path.join(ROOT,'contracts/cohost-runtime-closure.json'),'utf8'));assert.equal(c.main_promotion.exact_main_c47_gate_required,true);assert.equal(c.main_promotion.all_pr_workflows_rerun_on_main_required,false);});
