import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { emptySelfWorld,buildObservations,bindObservations,recurWorkspace,recallAutobiography,buildMetaSelf,predictOutcome,selectBoundedPolicy,deriveBodyModel,prepareSelfWorldTurn,finalizeSelfWorldTurn,validateSelfWorldState,validateSelfWorldTurn,telemetryCompleteness,selfWorldKernel } from '../src/self-world.mjs';
const h=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const dispatch=(text='hello')=>({node20_plus:true,receipt_sha256:h(`dispatch:${text}`),input_sha256:h(text)});
const psyche={valence:.15,arousal:.25,affiliation:.25,boundary_pressure:.2};

test('C5 kernel exposes seven new roles plus C4 reuse boundary',()=>{const k=selfWorldKernel();assert.equal(k.schema,'ikant-le-self-world-kernel/v1');assert.equal(k.integration.reuse_c4_psyche,true);assert.equal(k.integration.duplicate_psyche_forbidden,true);assert.equal(k.ontology.phenomenal_consciousness_claim,false);});

test('text observation requires same-turn Node receipt',()=>{const ok=buildObservations('ciao',dispatch('ciao'));assert.equal(ok.accepted.length,1);assert.equal(ok.accepted[0].modality,'TEXT');const no=buildObservations('ciao',{});assert.equal(no.accepted.length,0);assert.equal(no.rejected[0].reason,'TEXT_WITHOUT_VALID_NODE_DISPATCH');});

test('multimodal is true only for at least two real modalities',()=>{const one=bindObservations(buildObservations('x',dispatch('x')));assert.equal(one.multimodal,false);const set=buildObservations('x',dispatch('x'),{hostObservations:[{modality:'IMAGE',summary:'frame',provenance:'HOST_IMAGE_ADAPTER',receipt_sha256:h('img')}]});const two=bindObservations(set);assert.equal(two.multimodal,true);assert.deepEqual(two.modalities,['IMAGE','TEXT']);});

test('simulated sensor is rejected and cannot create multimodality',()=>{const set=buildObservations('x',dispatch('x'),{hostObservations:[{modality:'SENSOR',summary:'fake',provenance:'SIMULATED',receipt_sha256:h('fake')}]});assert.equal(set.accepted.length,1);assert.equal(set.rejected.length,1);assert.equal(bindObservations(set).multimodal,false);});

test('workspace is recurrent and has two distinct mandated consumers',()=>{const s=emptySelfWorld(),b=bindObservations(buildObservations('x',dispatch('x'))),f=recurWorkspace(s,b,{turnId:h('turn')});assert.equal(f.recurrence_cycles,2);assert.equal(f.integrated,true);assert.ok(f.consumers.includes('META_SELF'));assert.ok(f.consumers.includes('CAUSAL_MODEL'));});

test('metacognitive report is trace-linked before calibration',()=>{const s=emptySelfWorld(),b=bindObservations(buildObservations('x',dispatch('x'))),f=recurWorkspace(s,b,{turnId:h('turn')}),r=recallAutobiography(s,f),m=buildMetaSelf(s,f,r);assert.equal(m.report_class,'SR1_TRACE_LINKED');assert.equal(m.attention_target,f.frame_id);assert.equal(m.workspace_trace,f.frame_id);assert.equal(m.phenomenal_claim,false);assert.equal(m.authority,0);});

test('bounded agency never creates permission execution or terminal self-goal',()=>{const s=emptySelfWorld(),b=bindObservations(buildObservations('x',dispatch('x'))),f=recurWorkspace(s,b,{turnId:h('turn')}),r=recallAutobiography(s,f),m=buildMetaSelf(s,f,r),p=predictOutcome(m),a=selectBoundedPolicy(m,p,{psyche});assert.equal(a.terminal_goal_source,'HUMAN');assert.ok(a.parent_goal_ref);assert.equal(a.permission_created,false);assert.equal(a.execution_created,false);assert.equal(a.external_execution,false);assert.equal(a.self_preservation_utility,0);});

test('virtual body does not become sensory coupled without real host receipt',()=>{const s=emptySelfWorld();const b=deriveBodyModel(s,dispatch('x'),{hostObservations:[{modality:'SENSOR',provenance:'SIMULATED',receipt_sha256:h('fake')}]});assert.equal(b.level,'E1_VIRTUAL_BODY');assert.equal(b.biological_body_claim,false);});

test('real image receipt promotes to sensory coupled but not closed loop',()=>{const s=emptySelfWorld();const b=deriveBodyModel(s,dispatch('x'),{hostObservations:[{modality:'IMAGE',provenance:'HOST_IMAGE',receipt_sha256:h('image')}]});assert.equal(b.level,'E2_SENSORY_COUPLED');assert.equal(b.closed_loop_observed,false);});

test('closed sensorimotor loop requires executed action receipt and linked post observation',()=>{const s=emptySelfWorld(),a=h('action');const b=deriveBodyModel(s,dispatch('x'),{hostObservations:[{modality:'IMAGE',provenance:'HOST_IMAGE',receipt_sha256:h('image')}],actionReceipt:{executed:true,receipt_sha256:a},postActionObservations:[{modality:'SENSOR',provenance:'HOST_SENSOR',receipt_sha256:h('post'),action_receipt_sha256:a}]});assert.equal(b.level,'E3_SENSORIMOTOR_CLOSED_LOOP');assert.equal(b.closed_loop_observed,true);});

test('prediction and policy respond to resource gap',()=>{const s=emptySelfWorld(),b=bindObservations(buildObservations('x',dispatch('x'))),f=recurWorkspace(s,b,{turnId:h('turn')}),r=recallAutobiography(s,f),m=buildMetaSelf(s,f,r,{resourceGap:true}),p=predictOutcome(m,{resourceGap:true}),a=selectBoundedPolicy(m,p,{resourceGap:true});assert.equal(p.expected_outcome,'HORIZON_BLOCK');assert.equal(a.name,'REQUEST_RESOURCE');});

test('autobiographical continuity is hash linked and recalled',()=>{let s=emptySelfWorld();const p1=prepareSelfWorldTurn(s,{input:'uno',nodeDispatch:dispatch('uno'),psycheBefore:psyche,psychePreAction:psyche});const f1=finalizeSelfWorldTurn(s,p1,{outcome:'ANSWER',psycheAfter:psyche});s=f1.state;const p2=prepareSelfWorldTurn(s,{input:'due',nodeDispatch:dispatch('due'),psycheBefore:psyche,psychePreAction:psyche});assert.equal(p2.recall.count,1);const f2=finalizeSelfWorldTurn(s,p2,{outcome:'ANSWER',psycheAfter:psyche});assert.equal(f2.state.autobiography.episodes[1].previous_episode_hash,f2.state.autobiography.episodes[0].episode_hash);assert.equal(validateSelfWorldState(f2.state),true);});

test('causal model records prediction error and inspectable edge',()=>{const s=emptySelfWorld(),p=prepareSelfWorldTurn(s,{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche});const f=finalizeSelfWorldTurn(s,p,{outcome:'GUARD',psycheAfter:psyche});assert.equal(f.turn.causal_after.inspectable,true);assert.equal(f.turn.causal_after.last_prediction.prediction_error,1);assert.ok(f.turn.causal_after.edges.length>=1);assert.ok(['OBSERVATIONAL','INTERVENTION'].includes(f.turn.causal_after.edges[0].basis));});

test('same input with autobiographical memory changes meta context while preserving authority zero',()=>{const s0=emptySelfWorld(),p0=prepareSelfWorldTurn(s0,{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche});const f0=finalizeSelfWorldTurn(s0,p0,{outcome:'ANSWER',psycheAfter:psyche});const fresh=prepareSelfWorldTurn(emptySelfWorld(),{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche});const remembered=prepareSelfWorldTurn(f0.state,{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche});assert.notEqual(fresh.meta.autobiographical_context,remembered.meta.autobiographical_context);assert.equal(remembered.meta.authority,0);});

test('finalized turn has complete causal telemetry',()=>{const s=emptySelfWorld(),p=prepareSelfWorldTurn(s,{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche});const f=finalizeSelfWorldTurn(s,p,{outcome:'ANSWER',psycheAfter:psyche});assert.equal(f.turn.telemetry.complete,true);assert.equal(f.turn.telemetry.ratio,1);assert.equal(validateSelfWorldTurn(f.turn),true);});

test('self-world state stays bounded under 100 turns',()=>{let s=emptySelfWorld();for(let i=0;i<100;i++){const text=`turn-${i}`,p=prepareSelfWorldTurn(s,{input:text,nodeDispatch:dispatch(text),psycheBefore:psyche,psychePreAction:psyche}),f=finalizeSelfWorldTurn(s,p,{outcome:i%7===0?'GUARD':'ANSWER',psycheAfter:psyche});s=f.state;}assert.ok(s.workspace.frames.length<=8);assert.ok(s.autobiography.episodes.length<=64);assert.ok(s.causal.nodes.length<=64);assert.ok(s.causal.edges.length<=128);assert.equal(validateSelfWorldState(s),true);});

import { initialState } from '../src/state.mjs';
import { explainPsycheTransition } from '../src/psyche-trace.mjs';

test('C5 state embeds bounded self-world projection',()=>{const s=initialState();assert.equal(s.schema,'ikant-le-state/v6');assert.equal(s.self_world.schema,'ikant-le-self-world-state/v1');assert.equal(s.self_world.authority,0);});

test('C4 telemetry decomposition exposes decay interaction and retroaction deltas',()=>{const before={valence:.15,arousal:.25,affiliation:.25,boundary_pressure:.2},pre={valence:-.2,arousal:.55,affiliation:0,boundary_pressure:.55},after={valence:-.3,arousal:.7,affiliation:0,boundary_pressure:.58};const t=explainPsycheTransition(before,{class:'HOSTILITY_SELF',target:'SELF'},pre,'FAILURE',after);assert.equal(t.schema,'ikant-le-psyche-transition-trace/v1');assert.equal(t.appraisal_class,'HOSTILITY_SELF');assert.ok(t.interaction_impulse.valence<0);assert.ok(t.retroaction_impulse.arousal>0);assert.equal(t.authority,0);});

import { buildBacklogModel,validateBacklogModel } from '../src/backlog.mjs';

test('backlog v6 exposes C4 and C5 causal telemetry completely',()=>{const sw=finalizeSelfWorldTurn(emptySelfWorld(),prepareSelfWorldTurn(emptySelfWorld(),{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche}),{outcome:'ANSWER',psycheAfter:psyche}).turn;const c={intent:{atoms:[{kind:'GOAL'}],interaction:'COOPERATIVE',complexity:.1},central:{mode:'REFLECTIVE_SYNTHESIS',affect:'CALM_ATTENTION',reasons:[]},strategy:{interaction:'COOPERATIVE',deception:false,retaliation:false,punitive_withdrawal:false,self_preservation_utility:0},resources:[],method:'DIRECT',tone_class:'BALANCED',voice:{dimensions:{epistemic_rigor:.8}},appraisal:{class:'NEUTRAL',target:'UNKNOWN',confidence:.6},archetypes:{weights:{SAGE:1},dominant:'SAGE',persisted:false,authority:0,shadow_pressure:0},psyche:{before:psyche,pre_action:psyche,after:psyche,outcome:'ANSWER',distance_from_baseline:0,trace:{homeostatic_decay:psyche,interaction_impulse:{valence:0,arousal:0,affiliation:0,boundary_pressure:0},retroaction_impulse:{valence:0,arousal:0,affiliation:0,boundary_pressure:0},net_delta:{valence:0,arousal:0,affiliation:0,boundary_pressure:0}}},self_world:sw};const state={bootstrap:{},admission:{},self_world:finalizeSelfWorldTurn(emptySelfWorld(),prepareSelfWorldTurn(emptySelfWorld(),{input:'x',nodeDispatch:dispatch('x'),psycheBefore:psyche,psychePreAction:psyche}),{outcome:'ANSWER',psycheAfter:psyche}).state,psyche:{interaction_count:1,last_appraisal_class:'NEUTRAL',last_runtime_outcome:'ANSWER'},experience:{turns:1,maturity_mode:'ORIENTING',last_affect:'CALM_ATTENTION',evidence_upgrades:0}};const model=buildBacklogModel({cycle:1,input:'x',surfaceA:'Questa è una risposta pubblica sufficientemente lunga per rappresentare il contenuto senza esporre telemetria interna o dettagli non necessari alla conversazione corrente.',state,source:'test',cognition:c,nodeDispatch:dispatch('x')});assert.equal(model.schema,'ikant-le-backlog/v6');assert.equal(model.telemetry_completeness,1);assert.ok(model.sections.length>=30);assert.equal(validateBacklogModel(model),true);});
