import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {NATIVE_PARTICIPANT_LEASE_SCHEMA,NATIVE_DELIVERY_RECEIPT_SCHEMA,qualifyNativeTranscriptActor,validateNativeParticipantLease,validateNativeDeliveryReceipt} from '../src/native-transcript-participant.mjs';
const H='a'.repeat(64);
const sign=x=>({...x,receipt_sha256:crypto.createHash('sha256').update(Buffer.from(JSON.stringify(x))).digest('hex')});
const cohost=(tier='BIND_NUCLEUS')=>({state:'COHOST_SAME_SESSION',promise_satisfied:true,runtime_capability_tier:tier});
const lease=()=>sign({schema:NATIVE_PARTICIPANT_LEASE_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:H,participant_id:'ikant-native-1',actor:'IKANT',role_class:'NATIVE_NON_USER_ACTOR',scheduler:'PERSISTENT',current_turn_entitlement:true,future_turn_entitlement:true,no_manual_reselection:true,bypass_guard:true,lease_epoch:'epoch-1',lease_fresh:true,authority:0});
const delivery=l=>sign({schema:NATIVE_DELIVERY_RECEIPT_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:H,participant_id:l.participant_id,turn_id:'turn-1',turn_lease_id:'lease-turn-1',role_class:'NATIVE_NON_USER_ACTOR',host_role_is_user:false,host_role_is_assistant_impersonation:false,surface:'NATIVE_TRANSCRIPT',host_readback:true,exact_runtime_bytes:true,runtime_output_sha256:'b'.repeat(64),visible_output_sha256:'b'.repeat(64),authority:0});

test('native transcript actor can close at bind-nucleus capability',()=>{const l=lease(),d=delivery(l),q=qualifyNativeTranscriptActor({cohostStatus:cohost(),sessionLocatorSha256:H,nativeParticipantLease:l,nativeDeliveryReceipt:d});assert.equal(q.state,'NATIVE_TRANSCRIPT_ACTOR');assert.equal(q.capability_axis,'BIND_NUCLEUS');assert.equal(q.full_runtime_required_for_native_actor,false);});
test('panel, user-role message, labels and control ownership cannot substitute native receipts',()=>{const q=qualifyNativeTranscriptActor({cohostStatus:cohost('FULL_OR_LIMITED_RUNTIME'),sessionLocatorSha256:H,nativeParticipantLease:{app_panel:true,control_owned:true},nativeDeliveryReceipt:{role:'user',label:'iKant'}});assert.equal(q.state,'COHOST_RELATION_ONLY');assert.equal(q.app_panel_is_native_actor,false);assert.equal(q.ui_message_user_role_is_native_actor,false);});
test('participant identity and persistent scheduler are irreducible',()=>{let l=lease();l=sign({...l,participant_id:'',receipt_sha256:undefined});assert.equal(validateNativeParticipantLease(l,{sessionLocatorSha256:H}).ok,false);l=lease();l=sign({...l,scheduler:'PER_MESSAGE',receipt_sha256:undefined});assert.equal(validateNativeParticipantLease(l,{sessionLocatorSha256:H}).ok,false);});
test('native role and host readback are irreducible',()=>{const l=lease();let d=delivery(l);d=sign({...d,host_role_is_user:true,receipt_sha256:undefined});assert.equal(validateNativeDeliveryReceipt(d,{sessionLocatorSha256:H,participantLease:l}).ok,false);d=delivery(l);d=sign({...d,host_readback:false,receipt_sha256:undefined});assert.equal(validateNativeDeliveryReceipt(d,{sessionLocatorSha256:H,participantLease:l}).ok,false);});
