import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {ROOT,sha256} from '../src/contract.mjs';
import {bootstrapHandoffV2} from './bootstrap-fixture.mjs';
import {runtimeRootDescriptor,issuePreRuntimeBindNucleus,buildPreRuntimeBindFrame,executePreRuntimeBootstrapFromBind} from '../src/runtime-root-verified.mjs';
import {reopenCohostContextRoot} from '../src/cohost-context-root.mjs';
import {PARTICIPATION_LEASE_SCHEMA,ATTRIBUTED_DELIVERY_SCHEMA} from '../src/cohost-root-qualification.mjs';
import {invokeCanonicalBootstrapOwner,BOOTSTRAP_BINDING_SCHEMA,supersystemDigest,qualifySupersystemRuntimeV11} from '../src/supersystem-runtime-conformance.mjs';
import {NATIVE_PARTICIPANT_LEASE_SCHEMA} from '../src/native-transcript-participant.mjs';
import {NATIVE_TURN_GRANT_SCHEMA,NATIVE_DELIVERY_READBACK_SCHEMA,qualifyPhysicalRuntimeClosureV1,validatePhysicalClosurePersistenceWitness,buildPhysicalClosureEvidenceBundle} from '../src/physical-runtime-closure.mjs';

const sign=x=>({...x,receipt_sha256:crypto.createHash('sha256').update(Buffer.from(JSON.stringify(x))).digest('hex')});
function executorReceipt(sourceHead,orientation){const d=runtimeRootDescriptor(),objects=[{path:d.loader.path,blob_sha1:d.loader.blob_sha1},...d.shards.map(s=>({path:s.path,blob_sha1:s.blob_sha1}))].map(x=>{const b=fs.readFileSync(path.join(ROOT,x.path));return{...x,bytes:b.length};});const body={schema:'ikant-le-activation-executor/v1',repository:'Luke883i/iKant_LE',source_head:sourceHead,runtime_root_sha256:d.runtime_root_sha256,execution_plane:'SESSION_LOCAL_NODE',capability_probe_passed:true,capability_probe_before_acquisition:true,content_addressed:true,byte_path:'LOCAL_DIRECT',model_mediated_bytes:false,model_role:'NONE',model_rewrite_allowed:false,semantic_equivalence_allowed:false,source_arrival_samehash_required:true,source_arrival_samehash_verified:true,opaque_relay_roundtrip_verified:false,retry_semantics:'IDEMPOTENT_BY_OBJECT_IDENTITY',retry_count:0,acquisition_complete:true,orientation_objects:orientation.map(x=>({path:x.path,blob_sha1:x.blob_sha1,bytes:x.bytes})),runtime_objects:objects,slo_elapsed_ms:5,authority:0};return sign(body);}
function cohostEvidence(bind,frame,context){const lease=sign({schema:PARTICIPATION_LEASE_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:bind.session_locator_sha256,actor:'IKANT',current_turn_entitlement:true,persistent_route:true,no_manual_reselection:true,host_route_guard:true,authority:0});const native=sign({schema:'ikant-le-cohost-native-delivery-receipt/v1',observation_owner:'HOST_NATIVE_CHAT',observed:true,surface:'NATIVE_CHAT',platform_roundtrip_id:'c52-bind-1',session_locator_sha256:bind.session_locator_sha256,shell_receipt_sha256:frame.shell_receipt_sha256,ascii_sha256:frame.ascii_sha256,ascii_bytes:frame.ascii_bytes,envelope_receipt_sha256:frame.receipt_sha256,authority:0});const attributed=sign({schema:ATTRIBUTED_DELIVERY_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:bind.session_locator_sha256,turn_id:'BIND-1',actor:'IKANT',exact_runtime_bytes:true,native_delivery_receipt_sha256:native.receipt_sha256,authority:0});return{bindNucleus:bind,contextReadback:context,participationLease:lease,attributedDelivery:attributed,envelope:frame,nativeReceipt:native};}
function bootstrapEvidence(sourceHead){const inv=invokeCanonicalBootstrapOwner({human_input:'inizializza'}).receipt;const body={schema:BOOTSTRAP_BINDING_SCHEMA,observation_owner:'HOST_INTEGRATION',external_observation:true,observed:true,source_head:sourceHead,entrypoint:'src/supersystem-runtime-conformance.mjs#invokeCanonicalBootstrapOwner',callable:true,invoked:true,model_inferred_next:false,caller_retry_memory_used:false,owner_returned_next:true,one_next:true,one_executor:true,result_class:'OWNER_NEXT',owner_invocation_receipt_sha256:inv.receipt_sha256,binding_fresh:true,binding_epoch:'epoch-c52',binding_nonce:'nonce-c52',authority:0};return{inv,binding:{...body,receipt_sha256:supersystemDigest(body)}};}
function nativeLease(session){return sign({schema:NATIVE_PARTICIPANT_LEASE_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:session,participant_id:'ikant-native-c52',actor:'IKANT',role_class:'NATIVE_NON_USER_ACTOR',scheduler:'PERSISTENT',current_turn_entitlement:true,future_turn_entitlement:true,no_manual_reselection:true,bypass_guard:true,lease_epoch:'native-epoch-1',lease_fresh:true,authority:0});}
function routeReceipt({session,sourceHead,root,instance,turnId,ordinal=1,bypass=false,pending=false}){return sign({schema:'ikant-le-host-route-interposition/v1',observation_owner:'HOST_SESSION_ROUTER',external_observation:true,observed:true,session_locator_sha256:session,source_head:sourceHead,runtime_root_sha256:root,runtime_instance_id:instance,turn_id:turnId,route_epoch:'route-epoch-'+ordinal,route_fresh:true,canonical_route:'src/session-local-service.mjs#runPhysicalClosureLimitedTurn',interposition_active:true,runtime_turn_offered:true,canonical_turn_pending:pending,host_bypass_observed:bypass,model_direct_reply_observed:false,host_visible_turn_ordinal:ordinal,runtime_turn_ordinal:ordinal,authority:0});}
function turnGrant({session,sourceHead,root,instance,lease,turnId,ordinal=1}){return sign({schema:NATIVE_TURN_GRANT_SCHEMA,observation_owner:'HOST_SCHEDULER',external_observation:true,observed:true,session_locator_sha256:session,source_head:sourceHead,runtime_root_sha256:root,runtime_instance_id:instance,participant_id:lease.participant_id,participant_lease_receipt_sha256:lease.receipt_sha256,turn_id:turnId,turn_lease_id:'turn-lease-'+ordinal,scheduler_epoch:'scheduler-epoch-'+ordinal,grant_fresh:true,current_turn_granted:true,authority:0});}
function delivery({session,sourceHead,root,instance,lease,grant,runtimeTurn,ordinal=1}){return sign({schema:NATIVE_DELIVERY_READBACK_SCHEMA,observation_owner:'HOST_NATIVE_CHAT',external_observation:true,observed:true,session_locator_sha256:session,source_head:sourceHead,runtime_root_sha256:root,runtime_instance_id:instance,participant_id:lease.participant_id,turn_id:grant.turn_id,turn_lease_id:grant.turn_lease_id,turn_grant_receipt_sha256:grant.receipt_sha256,runtime_turn_receipt_sha256:runtimeTurn.receipt_sha256,role_class:'NATIVE_NON_USER_ACTOR',host_role_is_user:false,host_role_is_assistant_impersonation:false,surface:'NATIVE_TRANSCRIPT',host_readback:true,exact_runtime_bytes:true,runtime_output_sha256:runtimeTurn.output_sha256,visible_output_sha256:runtimeTurn.output_sha256,delivery_epoch:'delivery-epoch-'+ordinal,delivery_fresh:true,authority:0});}

async function fixture(){const sourceHead='a'.repeat(40),pre=bootstrapHandoffV2('inizializza iKant_LE',sourceHead),exec=executorReceipt(sourceHead,pre.orientation_objects),storage=fs.mkdtempSync(path.join(os.tmpdir(),'ikant-c52-')),hostSession='CHAT-C52';const bind=issuePreRuntimeBindNucleus({workspace:ROOT,storageRoot:storage,hostSessionId:hostSession,sourceHead,preacceptHandoff:pre,humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:10}),frame=buildPreRuntimeBindFrame(bind);const hydrated=await executePreRuntimeBootstrapFromBind({workspace:ROOT,storageRoot:storage,hostSessionId:hostSession,sourceHead,preacceptHandoff:pre,activationExecutor:exec,humanInput:'I ACCEPT',acceptanceObservedMonotonicMs:11}),context=reopenCohostContextRoot({storageRoot:storage,hostSessionId:hostSession}),runtimeDir=path.join(storage,'sessions',bind.session_locator_sha256,'runtime'),svc=await import(pathToFileURL(path.join(runtimeDir,'src/session-local-service.mjs')).href+'?c52='+crypto.randomUUID()),runtimeExecution=hydrated.runtime.runtime_execution_receipt;return{sourceHead,pre,storage,hostSession,bind,frame,hydrated,context,runtimeDir,svc,runtimeExecution,cohost:cohostEvidence(bind,frame,context),bootstrap:bootstrapEvidence(sourceHead)};}

const candidate=('Questo output appartiene al runtime limitato verificato, usa il percorso fisico C52 e conserva esplicitamente tutti i confini di autorità ed evidenza. '.repeat(6)).trim();

test('C52 fixes valid INTEGRATION_IMPEDIMENT receipt laundering in C51',()=>{const sourceHead='a'.repeat(40),inv=invokeCanonicalBootstrapOwner({human_input:'inizializza'}).receipt,body={schema:BOOTSTRAP_BINDING_SCHEMA,observation_owner:'HOST_INTEGRATION',external_observation:true,observed:true,source_head:sourceHead,entrypoint:'src/supersystem-runtime-conformance.mjs#invokeCanonicalBootstrapOwner',callable:true,invoked:true,model_inferred_next:false,caller_retry_memory_used:false,owner_returned_next:true,one_next:true,one_executor:true,result_class:'INTEGRATION_IMPEDIMENT',owner_invocation_receipt_sha256:null,authority:0},binding={...body,receipt_sha256:supersystemDigest(body)},q=qualifySupersystemRuntimeV11({sourceHead,bootstrapInvocationReceipt:inv,hostBootstrapBindingReceipt:binding});assert.equal(q.bootstrap_conformance,'INTEGRATION_IMPEDIMENT');assert.equal(q.system_state,'INTEGRATION_IMPEDIMENT');});

test('C52 runtime physical path blocks bypass before executing the turn',async()=>{const f=await fixture();try{const r=routeReceipt({session:f.bind.session_locator_sha256,sourceHead:f.sourceHead,root:f.runtimeExecution.runtime_root_sha256,instance:f.runtimeExecution.runtime_instance_id,turnId:'TURN-BLOCK',bypass:true});await assert.rejects(()=>f.svc.runPhysicalClosureLimitedTurn({input:'test',candidate,hostRouteInterpositionReceipt:r}),/physical route blocked:BLOCKED_BYPASS/);}finally{fs.rmSync(f.storage,{recursive:true,force:true});}});

test('C52 closes E0-E6 only from underlying proof receipts and exact runtime output',async()=>{const f=await fixture();try{const session=f.bind.session_locator_sha256,root=f.runtimeExecution.runtime_root_sha256,instance=f.runtimeExecution.runtime_instance_id,lease=nativeLease(session),turnId='TURN-1',route=routeReceipt({session,sourceHead:f.sourceHead,root,instance,turnId,ordinal:1}),run=await f.svc.runPhysicalClosureLimitedTurn({input:'Spiega la chiusura fisica sperimentale.',candidate,hostRouteInterpositionReceipt:route}),grant=turnGrant({session,sourceHead:f.sourceHead,root,instance,lease,turnId,ordinal:1}),del=delivery({session,sourceHead:f.sourceHead,root,instance,lease,grant,runtimeTurn:run.runtime_turn_receipt,ordinal:1});const q=qualifyPhysicalRuntimeClosureV1({sourceHead:f.sourceHead,bootstrapInvocationReceipt:f.bootstrap.inv,hostBootstrapBindingReceipt:f.bootstrap.binding,runtimeExecutionReceipt:f.runtimeExecution,cohostEvidence:f.cohost,hostRouteInterpositionReceipt:route,nativeParticipantLease:lease,nativeTurnGrantReceipt:grant,nativeDeliveryReadbackReceipt:del,runtimeTurnReceipt:run.runtime_turn_receipt});assert.equal(q.state,'NATIVE_TRANSCRIPT_ACTOR_E2E');assert.equal(q.physical_e2e_proven,true);assert.equal(q.runtime_instance_id,instance);assert.equal(q.session_locator_sha256,session);assert.equal(q.participant_id,lease.participant_id);assert.equal(q.turn_id,turnId);assert.equal(q.full_runtime_required,false);assert.equal(q.control_ownership_required,false);assert.equal(q.canonical_product_required,false);assert.equal(q.legacy_active_required,false);
 const missingGrant=qualifyPhysicalRuntimeClosureV1({sourceHead:f.sourceHead,bootstrapInvocationReceipt:f.bootstrap.inv,hostBootstrapBindingReceipt:f.bootstrap.binding,runtimeExecutionReceipt:f.runtimeExecution,cohostEvidence:f.cohost,hostRouteInterpositionReceipt:route,nativeParticipantLease:lease,nativeTurnGrantReceipt:{},nativeDeliveryReadbackReceipt:del,runtimeTurnReceipt:run.runtime_turn_receipt});assert.equal(missingGrant.state,'COHOST_RELATION_ONLY');
 }finally{fs.rmSync(f.storage,{recursive:true,force:true});}});

test('C52 persistence witness requires same lease and a fresh later grant/delivery',async()=>{const f=await fixture();try{const session=f.bind.session_locator_sha256,root=f.runtimeExecution.runtime_root_sha256,instance=f.runtimeExecution.runtime_instance_id,lease=nativeLease(session);const route1=routeReceipt({session,sourceHead:f.sourceHead,root,instance,turnId:'TURN-1',ordinal:1}),run1=await f.svc.runPhysicalClosureLimitedTurn({input:'turn one',candidate,hostRouteInterpositionReceipt:route1}),grant1=turnGrant({session,sourceHead:f.sourceHead,root,instance,lease,turnId:'TURN-1',ordinal:1}),del1=delivery({session,sourceHead:f.sourceHead,root,instance,lease,grant:grant1,runtimeTurn:run1.runtime_turn_receipt,ordinal:1}),base=qualifyPhysicalRuntimeClosureV1({sourceHead:f.sourceHead,bootstrapInvocationReceipt:f.bootstrap.inv,hostBootstrapBindingReceipt:f.bootstrap.binding,runtimeExecutionReceipt:f.runtimeExecution,cohostEvidence:f.cohost,hostRouteInterpositionReceipt:route1,nativeParticipantLease:lease,nativeTurnGrantReceipt:grant1,nativeDeliveryReadbackReceipt:del1,runtimeTurnReceipt:run1.runtime_turn_receipt});const route2=routeReceipt({session,sourceHead:f.sourceHead,root,instance,turnId:'TURN-2',ordinal:2}),run2=await f.svc.runPhysicalClosureLimitedTurn({input:'turn two',candidate,hostRouteInterpositionReceipt:route2}),grant2=turnGrant({session,sourceHead:f.sourceHead,root,instance,lease,turnId:'TURN-2',ordinal:2}),del2=delivery({session,sourceHead:f.sourceHead,root,instance,lease,grant:grant2,runtimeTurn:run2.runtime_turn_receipt,ordinal:2}),w=validatePhysicalClosurePersistenceWitness({baseClosure:base,secondRouteReceipt:route2,secondRuntimeTurnReceipt:run2.runtime_turn_receipt,nativeParticipantLease:lease,secondTurnGrantReceipt:grant2,secondDeliveryReceipt:del2}),bundle=buildPhysicalClosureEvidenceBundle({closure:base,persistenceWitness:w,receipts:{bootstrap:f.bootstrap.binding,runtime:f.runtimeExecution,route:route1,participant:lease,grant:grant1,delivery:del1}});assert.equal(w.status,'PASS');assert.equal(bundle.global_dod_pass,true);assert.equal(bundle.live_receipts_external_to_repository,true);const mismatchedRoute=routeReceipt({session,sourceHead:f.sourceHead,root,instance,turnId:'TURN-X',ordinal:2}),bad=validatePhysicalClosurePersistenceWitness({baseClosure:base,secondRouteReceipt:mismatchedRoute,secondRuntimeTurnReceipt:run2.runtime_turn_receipt,nativeParticipantLease:lease,secondTurnGrantReceipt:grant2,secondDeliveryReceipt:del2});assert.equal(bad.status,'FAIL');assert.ok(bad.errors.includes('turn_binding'));}finally{fs.rmSync(f.storage,{recursive:true,force:true});}});
