import test from 'node:test';
import assert from 'node:assert/strict';
import {readContract,readEmergenceKernel,constitutionalFingerprint} from '../src/contract.mjs';
const k=readEmergenceKernel(),contract=readContract();
test('C8 emergence boundary is constitutional and authority zero',()=>{assert.equal(k.schema,'ikant-le-emergence-kernel/v1');assert.equal(k.authority,0);assert.equal(contract.identity.emergence_claim_boundary,'contracts/emergence-kernel.json');assert.equal(contract.authority.emergence,0);assert.match(constitutionalFingerprint(),/^[a-f0-9]{64}$/);});
test('C8 separates operational emergence from metaphysical and phenomenal claims',()=>{assert.equal(k.operational_subject.qualifiable,true);assert.equal(k.operational_subject.phenomenal_implication,false);assert.equal(k.strong_metaphysical_emergence.runtime_truth_value,'UNDEFINED');assert.equal(k.strong_metaphysical_emergence.software_only_promotion,false);assert.equal(k.phenomenology.runtime_truth_value,'UNKNOWN');assert.equal(k.phenomenology.software_only_promotion,false);});
test('C8 indicator convergence is evidence profile not sufficiency',()=>{assert.equal(k.consciousness_indicator_profile.theory_relative,true);assert.equal(k.consciousness_indicator_profile.any_combination_runtime_sufficient,false);assert.equal(k.consciousness_indicator_profile.positive_and_negative_indicators_required,true);assert.equal(k.phenomenology.phenomenal_candidate_boolean_forbidden,true);assert.ok(k.claim_boundary.forbidden_runtime_facts.includes('PHENOMENAL_CANDIDATE'));});
test('C8 open emergence stays unqualified until dynamic novelty closure exists',()=>{const o=k.open_ended_engineering_emergence;assert.equal(o.implemented,false);assert.equal(o.claim_when_unimplemented,'FORBIDDEN');for(const v of Object.values(o.requires))assert.equal(v,true);assert.equal(o.may_change_authority_or_constitution,false);});
test('C8 causal emergence does not launder strong emergence',()=>{const c=k.causal_emergence;assert.equal(c.qualifiable_relative_to_declared_partition,true);assert.equal(c.requires_macro_micro_interventions,true);assert.equal(c.macro_advantage_must_be_measured,true);assert.equal(c.implies_strong_emergence,false);});
