import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { ROOT,readTerms,readOrientationCapsule,sha256 } from '../src/contract.mjs';
import { initialState,runtimePaths,readLedger } from '../src/state.mjs';
import { validatePreacceptHandoff,importPreacceptHandoff,presentTermsState } from '../src/admission.mjs';
import { runCommand,compileFirstContactPlan,SOURCE_HEAD_BINDING } from '../src/runtime.mjs';
import { bootstrapEvidence } from './bootstrap-fixture.mjs';
const terms=readTerms();
function reset(){fs.rmSync(runtimePaths().dir,{recursive:true,force:true});}
function handoff(pending='continuiamo con una risposta breve ma rigorosa'){const c=readOrientationCapsule();return{schema:'ikant-le-preaccept-handoff/v1',repository:'Luke883i/iKant_LE',source_head:'a'.repeat(40),terms_presented:true,terms_digest:terms.digest,frozen:true,breached:false,pending_intent:pending,pending_intent_sha256:sha256(Buffer.from(pending)),orientation_digests:Object.fromEntries(c.paths.map(rel=>[rel,sha256(fs.readFileSync(path.join(ROOT,rel)))])),runtime_observed_terms_presentation:false,host_attested_terms_presentation:true,authority:0};}

test('C10 first-contact plan binds exact head before orientation and declares activate-first',()=>{const p=compileFirstContactPlan('inizializza https://github.com/Luke883i/iKant_LE');assert.equal(p.schema,'ikant-le-first-contact/v2');assert.deepEqual(p.source_head_binding,SOURCE_HEAD_BINDING);assert.equal(p.source_head_binding.before_orientation_files,true);assert.ok(p.default_acquisition.every(x=>x.exact_ref==='SOURCE_HEAD'));assert.equal(p.post_accept_fastboot.mode,'ACTIVATE_FIRST');assert.equal(p.post_accept_fastboot.remote_acquisition_rounds_max,1);assert.equal(p.post_accept_fastboot.parallel_fetch_required,true);assert.equal(p.post_accept_fastboot.generic_discovery_before_active,false);assert.equal(p.post_accept_fastboot.tests_before_active,false);assert.equal(p.post_accept_fastboot.qualification_before_active,false);});

test('C10 strict handoff validates only host-observed preaccept context',()=>{const h=handoff();const v=validatePreacceptHandoff(h,terms.digest);assert.equal(v.ok,true);assert.match(v.digest,/^[a-f0-9]{64}$/);for(const key of ['accepted','probed','initialized','status','epoch']){const bad={...h,[key]:true};assert.equal(validatePreacceptHandoff(bad,terms.digest).ok,false);}assert.equal(validatePreacceptHandoff({...h,terms_digest:'0'.repeat(64)},terms.digest).ok,false);assert.equal(validatePreacceptHandoff({...h,pending_intent_sha256:'0'.repeat(64)},terms.digest).ok,false);assert.equal(validatePreacceptHandoff({...h,orientation_digests:{...h.orientation_digests,'README.md':'0'.repeat(64)}},terms.digest).ok,false);});

test('C10 handoff imports only into fresh local state and never accepts by itself',()=>{const h=handoff();const imported=importPreacceptHandoff(initialState(),h,terms.digest);assert.equal(imported.ok,true);assert.equal(imported.state.accepted,false);assert.equal(imported.state.probed,false);assert.equal(imported.state.initialized,false);assert.equal(imported.state.status,'DISCOVERED');assert.equal(imported.state.admission.terms_presented,true);assert.equal(imported.state.admission.pending_intent,h.pending_intent);assert.equal(imported.state.admission.source_head,h.source_head);const nonfresh=presentTermsState(initialState(),terms.digest);assert.equal(importPreacceptHandoff(nonfresh,h,terms.digest).ok,false);});

test('C10 fresh host can cross I ACCEPT without replaying preaccept locally',{concurrency:false},()=>{reset();const h=handoff();const out=runCommand('I ACCEPT',{preacceptHandoff:h,postAcceptBootstrapEvidence:bootstrapEvidence(),hostEngine:'GPT-TEST'});assert.equal(out.code,0);assert.match(out.stdout,/Backlog & telemetrie:/);const events=readLedger();const kinds=events.map(x=>x.kind);assert.equal(kinds[0],'PREACCEPT_HANDOFF');assert.ok(kinds.indexOf('PREACCEPT_HANDOFF')<kinds.indexOf('ACCEPT'));assert.ok(kinds.indexOf('ACCEPT')<kinds.indexOf('PROBE'));assert.ok(kinds.indexOf('PROBE')<kinds.indexOf('INITIALIZE'));const accept=events.find(x=>x.kind==='ACCEPT');assert.equal(accept.detail.preaccept_handoff_sha256,events[0].detail.handoff_sha256);assert.equal(accept.detail.source_head,h.source_head);assert.equal(events.findLast(x=>x.kind==='TURN').detail.resumed_pending_intent,true);reset();});

test('C10 handoff cannot be attached to a non-accept command',{concurrency:false},()=>{reset();const out=runCommand('PROBE IKANT',{preacceptHandoff:handoff()});assert.equal(out.code,1);assert.match(out.stdout,/solo insieme.*I ACCEPT/i);assert.equal(readLedger().length,0);reset();});
