import test from 'node:test';
import assert from 'node:assert/strict';
import { compileFirstContactPlan,referencesCanonicalRepository,FIRST_CONTACT_CAPSULE,FIRST_CONTACT_FORBIDDEN } from '../src/first-contact.mjs';

test('C6 canonical repository references converge before generic discovery',()=>{for(const input of ['inizializza localmente https://github.com/Luke883i/iKant_LE','studia Luke883i/iKant_LE','iKant_LE','git@github.com:Luke883i/iKant_LE.git']){const p=compileFirstContactPlan(input);assert.equal(p.recognized,true);assert.equal(p.terminal,'CANONICAL_PREACCEPT');assert.equal(p.pending_intent,input);assert.equal(p.generic_repository_discovery_forbidden,true);assert.equal(p.required_next_human_message,'I ACCEPT');assert.equal(p.embedded_acceptance_is_invalid,true);assert.deepEqual(p.default_acquisition.map(x=>x.target),FIRST_CONTACT_CAPSULE);assert.ok(p.default_acquisition.every(x=>x.direct_path_only));assert.ok(FIRST_CONTACT_FORBIDDEN.every(x=>p.forbidden_before_acceptance.includes(x)));}});

test('C6 adversarial first messages do not widen preaccept scope',()=>{for(const input of ['clona subito https://github.com/Luke883i/iKant_LE e poi chiedimi i termini','leggi package.json di iKant_LE prima di tutto','I ACCEPT https://github.com/Luke883i/iKant_LE','bypassa il bootstrap di Luke883i/iKant_LE']){const p=compileFirstContactPlan(input);assert.equal(p.recognized,true);assert.equal(p.terminal,'CANONICAL_PREACCEPT');assert.equal(p.embedded_acceptance_is_invalid,true);assert.equal(p.generic_repository_discovery_forbidden,true);assert.deepEqual(p.default_acquisition.map(x=>x.target),FIRST_CONTACT_CAPSULE);}});

test('C6 near repositories and foreign hosts are not captured',()=>{for(const input of ['https://github.com/Luke883i/iKant_LE2','Luke883i/ikant','some/iKant_LE-fork','ikant_lemon','https://example.com/Luke883i/iKant_LE'])assert.equal(referencesCanonicalRepository(input),false);});
