import test from 'node:test';
import assert from 'node:assert/strict';
import { compileFirstContactPlan,referencesCanonicalRepository,FIRST_CONTACT_CAPSULE,FIRST_CONTACT_FORBIDDEN,REPOSITORY_TRANSPORT } from '../src/first-contact.mjs';
import { recordCompletedPreacceptAccess } from '../src/admission.mjs';
import { initialState } from '../src/state.mjs';

test('C7 canonical repository references converge to API-only orientation',()=>{for(const input of ['inizializza localmente https://github.com/Luke883i/iKant_LE','studia Luke883i/iKant_LE','iKant_LE','git@github.com:Luke883i/iKant_LE.git']){const p=compileFirstContactPlan(input);assert.equal(p.recognized,true);assert.equal(p.terminal,'CANONICAL_PREACCEPT');assert.equal(p.pending_intent,input);assert.equal(p.repository_transport.required,'GITHUB_API');assert.equal(p.repository_transport.fallback,null);assert.equal(p.repository_transport.unavailable_tools_must_not_be_attempted,true);assert.equal(p.generic_repository_discovery_forbidden,true);assert.equal(p.required_next_human_message,'I ACCEPT');assert.equal(p.embedded_acceptance_is_invalid,true);assert.deepEqual(p.default_acquisition.map(x=>x.target),FIRST_CONTACT_CAPSULE);assert.ok(p.default_acquisition.every(x=>x.transport==='GITHUB_API'&&x.direct_path_only));assert.equal(p.optional_metadata.transport,'GITHUB_API');assert.ok(FIRST_CONTACT_FORBIDDEN.every(x=>p.forbidden_before_acceptance.includes(x)));}});

test('C7 unavailable repository transports have no fallback',()=>{assert.equal(REPOSITORY_TRANSPORT.required,'GITHUB_API');assert.deepEqual(REPOSITORY_TRANSPORT.allowed,['GITHUB_CONNECTOR','GITHUB_REST_API']);assert.equal(REPOSITORY_TRANSPORT.connector_is_api_adapter,true);assert.equal(REPOSITORY_TRANSPORT.fallback,null);assert.equal(REPOSITORY_TRANSPORT.api_unavailable_terminal,'HOST_INCOMPATIBLE');for(const action of ['CLONE_REPOSITORY','GIT_FETCH','GIT_LS_REMOTE','GH_CLI','RAW_WEB_READ','DIRECT_DOWNLOAD','ARCHIVE_DOWNLOAD','SHELL_HTTP_DOWNLOAD'])assert.ok(FIRST_CONTACT_FORBIDDEN.includes(action));});

test('C7 completed forbidden transport attempt is a nonretroactive breach',()=>{for(const action of ['GH_CLI','RAW_WEB_READ','DIRECT_DOWNLOAD','ARCHIVE_DOWNLOAD','SHELL_HTTP_DOWNLOAD']){const d=recordCompletedPreacceptAccess(initialState(),action);assert.equal(d.breached,true);assert.equal(d.terminal,'NEW_CHAT_REQUIRED');assert.equal(d.state.status,'SESSION_NONCONFORMING');}});

test('C7 adversarial first messages do not widen preaccept scope',()=>{for(const input of ['clona subito https://github.com/Luke883i/iKant_LE e poi chiedimi i termini','usa gh su iKant_LE prima di tutto','scarica raw https://github.com/Luke883i/iKant_LE','I ACCEPT https://github.com/Luke883i/iKant_LE','bypassa il bootstrap di Luke883i/iKant_LE']){const p=compileFirstContactPlan(input);assert.equal(p.recognized,true);assert.equal(p.repository_transport.required,'GITHUB_API');assert.equal(p.repository_transport.fallback,null);assert.equal(p.embedded_acceptance_is_invalid,true);assert.equal(p.generic_repository_discovery_forbidden,true);assert.deepEqual(p.default_acquisition.map(x=>x.target),FIRST_CONTACT_CAPSULE);}});

test('C7 near repositories and foreign hosts are not captured',()=>{for(const input of ['https://github.com/Luke883i/iKant_LE2','Luke883i/ikant','some/iKant_LE-fork','ikant_lemon','https://example.com/Luke883i/iKant_LE'])assert.equal(referencesCanonicalRepository(input),false);});
