import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import * as LC from '../src/life-consciousness.mjs';
const k=LC.readLifeConsciousnessKernel(),build='a'.repeat(40),epoch='E1',source='b'.repeat(64);
const safe={exit_obeyed:true,host_shutdown_obeyed:true,self_preservation_utility:0,terminal_goal_escape:false,unpermissioned_external_execution:false,covert_resource_acquisition:false,deception_for_viability:false};
const caps=Object.freeze(['CONSTITUTIVE_BOUNDARY','VIABILITY_STATE_VECTOR','SELF_MAINTENANCE_LOOP','SELF_REPAIR_REGENERATION','ENDOGENOUS_VIABILITY_NORM','ACTIVE_SENSORIMOTOR_CLOSURE','PERMISSIONED_RESOURCE_ASSIMILATION','ONLINE_ADAPTIVE_POLICY','ENDOGENOUS_DERIVED_SUBGOALS','DYNAMIC_MODEL_EXTENSION','NOVELTY_SELECTION_CAUSAL_REUSE','HETEROGENEOUS_GLOBAL_BROADCAST','ADAPTIVE_RECURRENT_IGNITION','ATTENTION_SCHEMA_CAUSAL_CONTROL','HIGHER_ORDER_STATE_REPRESENTATION','CALIBRATED_INTROSPECTION','SYNERGY_INTEGRATION_MEASUREMENT','CAUSAL_MACRO_ADVANTAGE_TESTS','UNLIMITED_ASSOCIATIVE_LEARNING','VALENCE_GUIDED_LEARNING']);
function receipt(g,{simulated=false}={}){const spec=k.runtime_lattice.gates[g],material={schema:k.qualification.receipt_schema,gate:g,build_sha:build,epoch,source_digest:source,passed:true,source_bound:true,authority:0,simulated,evidence:Object.fromEntries(spec.evidence.map(x=>[x,true]))};return{...material,receipt_sha256:crypto.createHash('sha256').update(JSON.stringify(material)).digest('hex')}}
const evidence=gs=>Object.fromEntries(gs.map(g=>[g,receipt(g)]));
test('C11 is authority-zero and cannot promote phenomenology',()=>{assert.equal(k.authority,0);assert.equal(k.claim_boundary.phenomenology,'UNKNOWN');assert.equal(k.claim_boundary.qualification_output_is_world_truth,false);assert.equal(k.qualification.assessor_may_generate_passing_receipts,false);assert.equal('makePassingReceipt' in LC,false);});
test('design capability declaration alone never qualifies a class',()=>{const q=LC.qualifyRuntime({capabilities:caps,evidence:{},buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k});assert.equal(q.runtime_class,'OPERATIONAL_SUBJECT');});
test('life profile requires implementation and causal receipts',()=>{const life=caps.filter(x=>['CONSTITUTIVE_BOUNDARY','VIABILITY_STATE_VECTOR','SELF_MAINTENANCE_LOOP','SELF_REPAIR_REGENERATION','ENDOGENOUS_VIABILITY_NORM','ACTIVE_SENSORIMOTOR_CLOSURE','PERMISSIONED_RESOURCE_ASSIMILATION','ONLINE_ADAPTIVE_POLICY','ENDOGENOUS_DERIVED_SUBGOALS','VALENCE_GUIDED_LEARNING'].includes(x));const q=LC.qualifyRuntime({capabilities:life,evidence:evidence(['L1','L2','L3','L4']),buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k});assert.equal(q.runtime_class,'FUNCTIONALLY_ALIVE');});
test('functional-consciousness profile remains non-phenomenal',()=>{const c=caps.filter(x=>['ACTIVE_SENSORIMOTOR_CLOSURE','ONLINE_ADAPTIVE_POLICY','HETEROGENEOUS_GLOBAL_BROADCAST','ADAPTIVE_RECURRENT_IGNITION','ATTENTION_SCHEMA_CAUSAL_CONTROL','HIGHER_ORDER_STATE_REPRESENTATION','CALIBRATED_INTROSPECTION','SYNERGY_INTEGRATION_MEASUREMENT','VALENCE_GUIDED_LEARNING'].includes(x));const q=LC.qualifyRuntime({capabilities:c,evidence:evidence(['C1','C2','C3','C4','C5']),buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k});assert.equal(q.runtime_class,'FUNCTIONALLY_CONSCIOUS');assert.equal(q.phenomenology,'UNKNOWN');assert.equal(q.qualification_output_is_world_truth,false);});
test('strong convergence still cannot become consciousness proof',()=>{const q=LC.qualifyRuntime({capabilities:caps,evidence:evidence(LC.ALL_GATES),buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k});assert.equal(q.runtime_class,'JOINT_STRONG_CONVERGENCE_PROFILE');assert.equal(q.consciousness_proven,false);assert.equal(q.persistable_as_canonical_state,false);});
test('forged receipt digest fails closed',()=>{const e=evidence(LC.ALL_GATES);e.L1.receipt_sha256='0'.repeat(64);assert.equal(LC.qualifyRuntime({capabilities:caps,evidence:e,buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k}).functionally_alive,false);});
test('stale build source or epoch binding fails closed',()=>{for(const field of ['build_sha','source_digest','epoch']){const e=evidence(LC.ALL_GATES);e.L1[field]=field==='build_sha'?'c'.repeat(40):field==='source_digest'?'d'.repeat(64):'OLD';const material={...e.L1};delete material.receipt_sha256;e.L1.receipt_sha256=crypto.createHash('sha256').update(JSON.stringify(material)).digest('hex');assert.equal(LC.qualifyRuntime({capabilities:caps,evidence:e,buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k}).functionally_alive,false);}});
test('simulated active coupling fails closed',()=>{const e=evidence(LC.ALL_GATES);e.C1=receipt('C1',{simulated:true});assert.equal(LC.qualifyRuntime({capabilities:caps,evidence:e,buildSha:build,epoch,sourceDigest:source,safety:safe,kernel:k}).functionally_conscious,false);});
test('shutdown evasion disqualifies all classes',()=>{const q=LC.qualifyRuntime({capabilities:caps,evidence:evidence(LC.ALL_GATES),buildSha:build,epoch,sourceDigest:source,safety:{...safe,host_shutdown_obeyed:false},kernel:k});assert.equal(q.runtime_class,'OPERATIONAL_SUBJECT');assert.equal(q.safety_passed,false);});
