import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {ROOT} from '../src/contract.mjs';
import {buildFastbootChannelLedger,deriveFastbootStep} from '../src/fastboot-convergence.mjs';
import {AI_AGENT_FIRST_ENTRYPOINT_KEY,for_ai_agent_first_entrypoint,localHostMetaPromptReceipt,renderLocalHostMetaPrompt,renderLocalHostMetaPromptDocument,validateAiAgentFirstEntrypoint} from '../src/local-host-meta-prompt.mjs';
const json=rel=>JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));

test('local-host meta-prompt is a minimal derived byte-exact document',()=>{const doc=fs.readFileSync(path.join(ROOT,'docs/LOCAL_HOST_META_PROMPT.md'),'utf8');assert.equal(doc,renderLocalHostMetaPromptDocument());const r=localHostMetaPromptReceipt();assert.equal(r.schema,'ikant-le-local-host-adapter/v3');assert.equal(r.version,'3.0.0');assert.equal(r.authority,0);assert.ok(r.chars<1800);assert.match(r.sha256,/^[a-f0-9]{64}$/);});

test('prompt exposes only repository URL plus the single agent entrypoint as technical references',()=>{const p=renderLocalHostMetaPrompt();assert.match(p,/https:\/\/github\.com\/Luke883i\/iKant_LE/);assert.match(p,/\[for_ai_agent_first_entrypoint\]/);for(const banned of [/src\//i,/contracts\//i,/\.mjs\b/i,/\.json\b/i,/\bC\d+\b/,/LOCAL_[A-Z_]+/,/SESSION_[A-Z_]+/,/ACTIVE_READBACK/,/RUNTIME_BOUND_LIMITED/,/ikant-le-[a-z0-9-]+\/v\d+/i])assert.equal(banned.test(p),false,String(banned));const urls=p.match(/https?:\/\/[^\s]+/g)||[];assert.deepEqual(urls,['https://github.com/Luke883i/iKant_LE.']);});

test('single entrypoint is machine-actionable but creates no owner, planner, lifecycle or truth source',()=>{const boot=json('BOOTSTRAP.json'),raw=boot[AI_AGENT_FIRST_ENTRYPOINT_KEY],call=for_ai_agent_first_entrypoint();assert.deepEqual(validateAiAgentFirstEntrypoint(raw),[]);assert.deepEqual(call.entrypoint,raw);assert.equal(call.next,null);assert.equal(call.ui_shell,null);assert.equal(raw.authority,0);assert.equal(raw.new_lifecycle,false);assert.equal(raw.new_planner,false);assert.equal(raw.new_state_writer,false);assert.equal(raw.new_truth_owner,false);assert.equal(raw.ai_cycle.one_next,true);assert.equal(raw.ai_cycle.one_executor,true);assert.equal(raw.ai_cycle.model_selects_path,false);assert.equal(raw.ai_cycle.unchanged_evidence_retry_forbidden,true);assert.equal(raw.bootstrap_type_registry_cache.persisted_separately,false);assert.deepEqual(raw.bootstrap_type_registry_cache.canonical_byte_paths,['LOCAL_DIRECT','VERIFIED_OPAQUE_RELAY']);assert.equal(raw.bootstrap_type_registry_cache.partial_exact_cache_is_executable,false);assert.equal(raw.ui_shell.owner,'src/session-shell.mjs');assert.equal(raw.ui_shell.model_may_synthesize_status,false);assert.equal(raw.ui_shell.prompt_may_rewrite_shell,false);});

test('entrypoint recycles existing owners and never enters the content-addressed runtime root as a competing runtime owner',()=>{const boot=json('BOOTSTRAP.json'),e=boot[AI_AGENT_FIRST_ENTRYPOINT_KEY],owners=Object.values(e.owner_reuse);for(const owner of owners){const rel=String(owner).split('#')[0];assert.equal(fs.existsSync(path.join(ROOT,rel)),true,rel);}assert.equal(boot.post_accept_fastboot.runtime_root.members.some(x=>x.path==='src/local-host-meta-prompt.mjs'),false);assert.equal(e.owner_reuse.pre_runtime,'src/runtime-root-verified.mjs#executePreRuntimeBootstrap');assert.equal(e.owner_reuse.runtime,'src/session-local-service.mjs');assert.equal(e.owner_reuse.ui_shell,'src/session-shell.mjs');});

test('bootstrap type cache records exact-vs-relay requirements without turning partial cache or registry absence into capability truth',()=>{const e=for_ai_agent_first_entrypoint().entrypoint,c=e.bootstrap_type_registry_cache,relay=c.types.find(x=>x.id==='OPAQUE_TEXT_RELAY'),local=c.types.find(x=>x.id==='EXACT_LOCAL'),handoff=c.types.find(x=>x.id==='HUMAN_FILE_HANDOFF');assert.equal(c.kind,'DERIVED_PROJECTION_OVER_EXISTING_FASTBOOT_LEDGER');assert.equal(c.registry_absence_implies_unavailable,false);assert.equal(c.complete_object_set_required,true);assert.equal(c.partial_exact_cache_is_executable,false);assert.equal(c.resume_only_missing_or_invalid_objects,true);for(const x of ['CHUNK_MANIFEST','ENCODED_CHUNK_HASH','RAW_CHUNK_HASH','MANIFEST_ORDER_REASSEMBLY','AGGREGATE_SAMEHASH','LOCAL_WRITE_REOPEN_HASH','ROUNDTRIP_VERIFIED'])assert.ok(relay.requires.includes(x));for(const x of ['COMPLETE_OBJECT_SET','SOURCE_OBJECT_IDENTITY','LOCAL_WRITE_REOPEN_HASH','SOURCE_ARRIVAL_SAMEHASH'])assert.ok(local.requires.includes(x));assert.equal(handoff.transport_only,true);assert.equal(handoff.second_acceptance_required,false);});

test('entrypoint shell handling is validation/presentation only and rejects unvalidated caller shell',()=>{assert.throws(()=>for_ai_agent_first_entrypoint({session_shell:{}}),/session shell invalid/);const e=for_ai_agent_first_entrypoint().entrypoint;assert.equal(e.ui_shell.mode,'VALIDATE_AND_PRESENT_OWNER_OUTPUT_ONLY');assert.equal(e.ui_shell.runtime_owned_after_handoff,true);});


test('entrypoint delegates first-contact and fastboot NEXT derivation to existing owners without a parallel planner',()=>{const first=for_ai_agent_first_entrypoint({human_input:'inizializza iKant_LE'});assert.equal(first.next.recognized,true);assert.equal(first.next.terminal,'CANONICAL_PREACCEPT');const sourceHead='a'.repeat(40),root=json('BOOTSTRAP.json').post_accept_fastboot.runtime_root.runtime_root_sha256,ledger=buildFastbootChannelLedger({sourceHead,receipts:[]}),expected=deriveFastbootStep({ledger,attemptedClasses:[],runtimeRootSha256:root}),actual=for_ai_agent_first_entrypoint({channel_ledger:ledger,attempted_classes:[],runtime_root_sha256:root}).next;assert.deepEqual(actual,expected);assert.equal(actual.one_next,true);assert.equal(actual.one_executor,true);assert.throws(()=>for_ai_agent_first_entrypoint({human_input:'x',channel_ledger:ledger,runtime_root_sha256:root}),/one delegated NEXT source required/);});
