import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { ROOT,readSurfaceBDelivery } from '../src/contract.mjs';
import { runCommand } from '../src/runtime.mjs';
import { runtimePaths } from '../src/state.mjs';
import { ENVIRONMENT_CATEGORIES,validateArtifactDescriptor,validateEnvironmentTelemetry,validateReleaseEnvelope } from '../src/surface-b.mjs';
import { bootstrapArgs } from './bootstrap-fixture.mjs';
function reset(){fs.rmSync(runtimePaths().dir,{recursive:true,force:true});}

test('C9 contract rejects filename-only delivery and bounds environment scope',()=>{const k=readSurfaceBDelivery();assert.equal(k.scope.exactly_one_docx_per_substantive_turn,true);assert.equal(k.handoff.same_turn_presentation_required,true);assert.equal(k.handoff.filename_only_is_delivery,false);assert.equal(k.handoff.filesystem_existence_is_delivery,false);assert.equal(k.handoff.runtime_can_observe_host_ui_presentation,false);assert.equal(k.environment_telemetry.completeness_target,1);assert.equal(k.environment_telemetry.explicit_unknowns_required,true);assert.equal(k.environment_telemetry.process_env_dump_forbidden,true);assert.equal(k.environment_telemetry.secret_material_forbidden,true);});

test('substantive ACTIVE turn emits one verified DOCX handoff and exact bounded environment telemetry',{concurrency:false},()=>{reset();runCommand('I ACCEPT',{...bootstrapArgs('inizializza'),hostEngine:'GPT-TEST'});const out=runCommand('continuiamo con una risposta rigorosa sul problema corrente');assert.equal(out.code,0);assert.equal(out.artifacts.length,1);const a=out.artifacts[0];assert.equal(validateArtifactDescriptor(a),true);assert.equal(a.kind,'SURFACE_B_DOCX');assert.equal(a.required_presentation,true);assert.equal(a.same_turn,true);assert.equal(fs.existsSync(a.path),true);assert.equal(validateEnvironmentTelemetry(out.environment_telemetry),true);assert.equal(out.environment_telemetry.explicit_unknowns,true);assert.deepEqual(Object.keys(out.environment_telemetry.categories).sort(),[...ENVIRONMENT_CATEGORIES].sort());assert.equal(out.environment_telemetry.completeness.ratio,1);assert.equal(validateReleaseEnvelope(out.release,a,out.environment_telemetry),true);const bytes=fs.readFileSync(a.path);assert.equal(bytes.length,a.bytes);assert.match(bytes.toString('utf8'),/Runtime environment telemetry/);assert.match(bytes.toString('utf8'),/raw process environment dumped: false/i);reset();});

test('descriptor release and environment validators reject forged or widened handoff state',{concurrency:false},()=>{reset();runCommand('I ACCEPT',{...bootstrapArgs('inizializza'),hostEngine:'GPT-TEST'});const out=runCommand('verifica il confine di consegna del backlog');const a=out.artifacts[0],e=out.environment_telemetry,r=out.release;const forgedDescriptor={...a,descriptor_sha256:'0'.repeat(64)};assert.equal(validateArtifactDescriptor(forgedDescriptor),false);const forgedRelease={...r,release_sha256:'0'.repeat(64)};assert.equal(validateReleaseEnvelope(forgedRelease,a,e),false);const widened={...e,categories:{...e.categories,PROCESS_ENV_RAW:{leak:true}}};assert.equal(validateEnvironmentTelemetry(widened),false);const noUnknowns={...e,explicit_unknowns:false};assert.equal(validateEnvironmentTelemetry(noUnknowns),false);reset();});

test('host-json CLI exposes the artifact path instead of requiring filename scraping',{concurrency:false},()=>{reset();let p=spawnSync(process.execPath,['ikant.mjs','--host-json','analizza','questa','richiesta'],{cwd:ROOT,encoding:'utf8'});assert.equal(p.status,0);let first=JSON.parse(p.stdout.trim());assert.equal(first.schema,'ikant-le-host-result/v1');assert.equal(first.artifacts.length,0);reset();const ba=bootstrapArgs('analizza questa richiesta'),hf=path.join(runtimePaths().dir,'handoff.json'),ef=path.join(runtimePaths().dir,'evidence.json');fs.writeFileSync(hf,JSON.stringify(ba.preacceptHandoff));fs.writeFileSync(ef,JSON.stringify(ba.postAcceptBootstrapEvidence));p=spawnSync(process.execPath,['ikant.mjs','--host-json','--preaccept-handoff-file',hf,'--bootstrap-evidence-file',ef,'I ACCEPT'],{cwd:ROOT,encoding:'utf8'});assert.equal(p.status,0);const active=JSON.parse(p.stdout.trim());assert.equal(active.schema,'ikant-le-host-result/v1');assert.equal(active.artifacts.length,1);assert.equal(active.artifacts[0].required_presentation,true);assert.equal(fs.existsSync(active.artifacts[0].path),true);assert.equal(active.release.host_presentation_required,true);assert.equal(active.release.filename_only_is_delivery,false);reset();});
