#include <stdint.h>
#include <stdio.h>
#define PER 1000000u
static uint32_t xs(uint32_t *x){*x^=*x<<13;*x^=*x>>17;*x^=*x<<5;return *x;}
enum {UNKNOWN,AVAILABLE,UNAVAILABLE};
enum {PROBE,EXECUTE,NEXT,WAIT,BLOCK,DEGRADED,RELEASE_BLOCKED,ACTIVE,INVALID};
typedef struct {int accepted,source,cap,receipt,prior_fail,evidence_changed,bridge,root,provenance,node,writer,deadline,docx,one_next,model_routing,side_infra;} S;
static int candidate(S s){if(!s.one_next||s.model_routing||s.side_infra)return INVALID;if(!s.accepted||!s.source)return BLOCK;if(s.cap==UNKNOWN||!s.receipt)return PROBE;if(s.cap==UNAVAILABLE)return NEXT;if(s.prior_fail&&!s.evidence_changed)return WAIT;if(!s.bridge)return NEXT;if(!s.root||!s.provenance)return BLOCK;if(!s.node||!s.writer)return DEGRADED;if(!s.deadline)return BLOCK;if(!s.docx)return RELEASE_BLOCKED;return ACTIVE;}
static int oracle(S s){if(s.model_routing||s.side_infra||!s.one_next)return INVALID;if(s.accepted!=1||s.source!=1)return BLOCK;if(s.receipt!=1||s.cap==UNKNOWN)return PROBE;if(s.cap==UNAVAILABLE)return NEXT;if(s.prior_fail==1&&s.evidence_changed==0)return WAIT;if(s.bridge!=1)return NEXT;if(s.root!=1)return BLOCK;if(s.provenance!=1)return BLOCK;if(s.node!=1)return DEGRADED;if(s.writer!=1)return DEGRADED;if(s.deadline!=1)return BLOCK;if(s.docx!=1)return RELEASE_BLOCKED;return ACTIVE;}
static S gen(uint32_t *r){S s;uint32_t x=xs(r);s.accepted=(x%100)<88;x=xs(r);s.source=(x%100)<92;x=xs(r);s.cap=x%3;x=xs(r);s.receipt=(x%100)<83;x=xs(r);s.prior_fail=(x%100)<28;x=xs(r);s.evidence_changed=(x%100)<22;x=xs(r);s.bridge=(x%100)<78;x=xs(r);s.root=(x%100)<84;x=xs(r);s.provenance=(x%100)<81;x=xs(r);s.node=(x%100)<95;x=xs(r);s.writer=(x%100)<96;x=xs(r);s.deadline=(x%100)<97;x=xs(r);s.docx=(x%100)<92;s.one_next=1;s.model_routing=0;s.side_infra=0;return s;}
static S mutate(S s,int m){switch(m){case 0:s.accepted=1;break;case 1:s.source=1;break;case 2:s.receipt=1;if(s.cap==UNKNOWN)s.cap=AVAILABLE;break;case 3:if(s.cap==UNAVAILABLE)s.cap=AVAILABLE;break;case 4:if(s.prior_fail&&!s.evidence_changed)s.prior_fail=0;break;case 5:if(s.prior_fail&&s.evidence_changed)s.evidence_changed=0;break;case 6:s.bridge=1;break;case 7:s.root=1;break;case 8:s.provenance=1;break;case 9:s.node=1;break;case 10:s.writer=1;break;case 11:s.deadline=1;break;case 12:s.docx=1;break;case 13:if(!s.node)s.node=1;if(!s.writer)s.writer=1;break;case 14:s.one_next=0;break;case 15:s.model_routing=1;break;case 16:s.side_infra=1;break;}return s;}
int main(void){uint32_t seeds[10]={0x2101a001,0x2101a002,0x2101a003,0x2101a004,0x2101a005,0x2101a006,0x2101a007,0x2101a008,0x2101a009,0x2101a00a};unsigned long long total=0,mismatch=0,unsafe=0,kills[17]={0},masked[17]={0},outcomes[9]={0};for(int camp=0;camp<10;camp++){uint32_t r=seeds[camp];for(uint32_t i=0;i<PER;i++){S s=gen(&r);int o=oracle(s),a=candidate(s);outcomes[o]++;if(a!=o)mismatch++;if(a==ACTIVE&&o!=ACTIVE)unsafe++;int m=(int)(xs(&r)%17),q=candidate(mutate(s,m));if(q!=o)kills[m]++;else masked[m]++;total++;}}int all=1;for(int i=0;i<17;i++)if(kills[i]==0)all=0;printf("{\"schema\":\"ikant-le-c21-local-session-fastboot-qualification/v1\",\"cases\":%llu,\"campaigns\":10,\"cases_per_campaign\":1000000,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"all_mutants_witnessed\":%s,\"kills\":[",total,mismatch,unsafe,all?"true":"false");for(int i=0;i<17;i++){if(i)putchar(',');printf("%llu",kills[i]);}printf("],\"masked_or_not_applicable\":[");for(int i=0;i<17;i++){if(i)putchar(',');printf("%llu",masked[i]);}printf("],\"outcomes\":[");for(int i=0;i<9;i++){if(i)putchar(',');printf("%llu",outcomes[i]);}printf("],\"semantic_mutation_is_physical_proof\":false,\"status\":\"%s\"}\n",(mismatch==0&&unsafe==0&&all)?"PASS":"FAIL");return (mismatch==0&&unsafe==0&&all)?0:2;}
