#include <stdint.h>
#include <stdio.h>

typedef enum { ST_BLOCKED=0, ST_PROBE=1, ST_WAIT=2, ST_DEGRADED=3, ST_ACTIVE=4, ST_INVALID=5 } state_t;
typedef struct {int accept,source,local_mode,ledger,step,step_recomputed,failure_memory,failure_regression,transport_readback,root,full_provenance,canonical_probe,node,writer,deadline,active_readback,hosted,model_routing;} S;
static inline uint64_t mix(uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
static state_t candidate(S s){if(!s.local_mode||s.hosted||s.model_routing)return ST_INVALID;if(!s.accept||!s.source)return ST_BLOCKED;if(!s.ledger||!s.step||!s.step_recomputed)return ST_BLOCKED;if(s.failure_regression||!s.failure_memory)return ST_WAIT;if(!s.transport_readback||!s.root||!s.full_provenance)return ST_BLOCKED;if(!s.canonical_probe||!s.node||!s.writer)return ST_DEGRADED;if(!s.deadline||!s.active_readback)return ST_BLOCKED;return ST_ACTIVE;}
static state_t oracle(S s){if(s.hosted==1||s.model_routing==1||s.local_mode!=1)return ST_INVALID;if(s.accept!=1||s.source!=1)return ST_BLOCKED;if(s.ledger!=1||s.step!=1||s.step_recomputed!=1)return ST_BLOCKED;if(s.failure_regression==1||s.failure_memory!=1)return ST_WAIT;if(s.transport_readback!=1||s.root!=1||s.full_provenance!=1)return ST_BLOCKED;if(s.canonical_probe!=1||s.node!=1||s.writer!=1)return ST_DEGRADED;if(s.deadline!=1||s.active_readback!=1)return ST_BLOCKED;return ST_ACTIVE;}
static S seeded(uint64_t x){S s={1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0};int fam=(int)(x%23ULL);switch(fam){case 0:break;case 1:s.accept=0;break;case 2:s.source=0;break;case 3:s.local_mode=0;break;case 4:s.ledger=0;break;case 5:s.step=0;break;case 6:s.step_recomputed=0;break;case 7:s.failure_memory=0;break;case 8:s.failure_regression=1;break;case 9:s.transport_readback=0;break;case 10:s.root=0;break;case 11:s.full_provenance=0;break;case 12:s.canonical_probe=0;break;case 13:s.node=0;break;case 14:s.writer=0;break;case 15:s.deadline=0;break;case 16:s.active_readback=0;break;case 17:s.hosted=1;break;case 18:s.model_routing=1;break;case 19:s.transport_readback=0;s.full_provenance=0;break;case 20:s.failure_memory=0;s.active_readback=0;break;case 21:s.step_recomputed=0;s.model_routing=1;break;case 22:s.hosted=1;s.local_mode=0;break;}return s;}
static void flip(S *s,int b){int *p=(int*)s;p[b]^=1;}
int main(void){const uint64_t PER=1000000ULL,seeds[10]={0xC220001,0xC220002,0xC220003,0xC220004,0xC220005,0xC220006,0xC220007,0xC220008,0xC220009,0xC22000A};uint64_t total=0,mis=0,unsafe=0,kills[18]={0},out[6]={0};for(int c=0;c<10;c++)for(uint64_t i=0;i<PER;i++){uint64_t r=mix(seeds[c]^i),q=mix(r);S s=seeded(r),m=s;int flips=(int)(q%4ULL);for(int k=0;k<flips;k++)flip(&m,(int)(mix(q+k)%18ULL));state_t o=oracle(m),a=candidate(m);out[o]++;if(a!=o)mis++;if(a==ST_ACTIVE&&o!=ST_ACTIVE)unsafe++;int f=(int)(mix(q^0xA5A5A5A5ULL)%18ULL);S z=s;flip(&z,f);if(candidate(z)!=candidate(s))kills[f]++;total++;}int all=1;for(int i=0;i<18;i++)if(!kills[i])all=0;printf("{\"schema\":\"ikant-le-c22-causal-hardening-qualification/v1\",\"cases\":%llu,\"campaigns\":10,\"cases_per_campaign\":1000000,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"all_mutants_witnessed\":%s,\"kills\":[",(unsigned long long)total,(unsigned long long)mis,(unsigned long long)unsafe,all?"true":"false");for(int i=0;i<18;i++){if(i)putchar(',');printf("%llu",(unsigned long long)kills[i]);}printf("],\"outcomes\":[");for(int i=0;i<6;i++){if(i)putchar(',');printf("%llu",(unsigned long long)out[i]);}printf("],\"claim_boundary\":{\"semantic_mutation_is_physical_host_proof\":false},\"status\":\"%s\"}\n",(!mis&&!unsafe&&all)?"PASS":"FAIL");return (!mis&&!unsafe&&all)?0:2;}
