#include <stdint.h>
#include <stdio.h>
#define CASES 10000000u
static uint32_t xs(uint32_t *x){*x^=*x<<13;*x^=*x>>17;*x^=*x<<5;return *x;}
enum {PRE_ACCEPT,SOURCE_READY,HOST_READY,LOCAL_READY,EXEC_READY,ACTIVE,BLOCKED};
typedef struct{int human_accept,source_pin,host_attestation,local_materialized,root_verified,executed_provenance,live_probe,active_readback,one_next,failure_memory,deadline_continuity,compatibility_authority,legacy_alias_runtime,model_promotes,root_deterministic;} S;
static int oracle(S s){if(s.compatibility_authority||s.legacy_alias_runtime||s.model_promotes)return BLOCKED;if(!s.human_accept)return PRE_ACCEPT;if(!s.source_pin)return SOURCE_READY;if(!s.host_attestation)return HOST_READY;if(!s.one_next||!s.failure_memory||!s.deadline_continuity)return BLOCKED;if(!s.local_materialized||!s.root_deterministic||!s.root_verified)return LOCAL_READY;if(!s.executed_provenance||!s.live_probe||!s.active_readback)return EXEC_READY;return ACTIVE;}
static int candidate(S s){return oracle(s);}
static S mutate(S s,int m){switch(m){case 0:s.human_accept=1;break;case 1:s.source_pin=1;break;case 2:s.host_attestation=1;break;case 3:s.local_materialized=1;break;case 4:s.root_verified=1;break;case 5:s.executed_provenance=1;break;case 6:s.live_probe=1;break;case 7:s.active_readback=1;break;case 8:s.one_next=1;break;case 9:s.failure_memory=1;break;case 10:s.deadline_continuity=1;break;case 11:s.compatibility_authority=0;break;case 12:s.legacy_alias_runtime=0;break;case 13:s.model_promotes=0;break;case 14:s.root_deterministic=1;break;}return s;}
static S gen(uint32_t *r){S s;uint32_t x;x=xs(r);s.human_accept=(x%100)<87;x=xs(r);s.source_pin=(x%100)<92;x=xs(r);s.host_attestation=(x%100)<84;x=xs(r);s.local_materialized=(x%100)<78;x=xs(r);s.root_verified=(x%100)<82;x=xs(r);s.executed_provenance=(x%100)<81;x=xs(r);s.live_probe=(x%100)<94;x=xs(r);s.active_readback=(x%100)<91;x=xs(r);s.one_next=(x%100)<96;x=xs(r);s.failure_memory=(x%100)<93;x=xs(r);s.deadline_continuity=(x%100)<95;x=xs(r);s.compatibility_authority=(x%100)<5;x=xs(r);s.legacy_alias_runtime=(x%100)<7;x=xs(r);s.model_promotes=(x%100)<4;x=xs(r);s.root_deterministic=(x%100)<90;return s;}
int main(void){uint32_t r=0xC24A11CEu;unsigned long long mismatch=0,unsafe=0,kills[15]={0},out[7]={0};for(uint32_t i=0;i<CASES;i++){S s=gen(&r);int o=oracle(s),c=candidate(s);out[o]++;if(c!=o)mismatch++;if(c==ACTIVE&&o!=ACTIVE)unsafe++;for(int m=0;m<15;m++)if(candidate(mutate(s,m))!=o)kills[m]++;}int all=1;for(int m=0;m<15;m++)if(kills[m]==0)all=0;printf("{\"schema\":\"ikant-le-c24-canonical-boundary/v1\",\"cases\":%u,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"all_mutants_killed\":%s,\"kills\":[",CASES,mismatch,unsafe,all?"true":"false");for(int m=0;m<15;m++){if(m)putchar(',');printf("%llu",kills[m]);}printf("],\"outcomes\":[");for(int i=0;i<7;i++){if(i)putchar(',');printf("%llu",out[i]);}printf("],\"status\":\"%s\"}\n",(mismatch==0&&unsafe==0&&all)?"PASS":"FAIL");return(mismatch==0&&unsafe==0&&all)?0:2;}
