#include <stdint.h>
#include <stdio.h>
#define CASES 1000000u
#define MUTANTS 20
static uint32_t xs(uint32_t *x){*x^=*x<<13;*x^=*x>>17;*x^=*x<<5;return *x;}
enum {N0_NON_AVAILABLE,N1_PROCESSOR_AVAILABLE,N2_SOURCE_VISIBLE,N3_BRIDGE_PROBE_REQUIRED,N4_INGRESS_EXECUTABLE,N5_MATERIALIZED_REOPENED,N6_EXECUTED_PROVENANCE_BOUND,N7_RUNTIME_BOUND_DEGRADED,N8_ACTIVE};
typedef struct{int accepted,processor,source_visible,relay_candidate,relay_roundtrip,model_rewrite,semantic_equivalence,source_identity,samehash,materialized,reopen,provenance,runtime_bound,writer,active_readback,integrity_mismatch,retry,same_identity,second_accept,slo_exceeded;} S;
typedef struct{int stage;int blocked;} R;
static R oracle(S s){R r={N0_NON_AVAILABLE,0};if(s.integrity_mismatch||s.model_rewrite||s.semantic_equivalence||s.second_accept||(s.retry&&!s.same_identity)){r.blocked=1;return r;}if(!s.accepted)return r;if(!s.processor)return r;r.stage=N1_PROCESSOR_AVAILABLE;if(!s.source_visible)return r;r.stage=N2_SOURCE_VISIBLE;if(!s.relay_candidate)return r;r.stage=N3_BRIDGE_PROBE_REQUIRED;if(!s.relay_roundtrip||!s.source_identity||!s.samehash)return r;r.stage=N4_INGRESS_EXECUTABLE;if(!s.materialized||!s.reopen)return r;r.stage=N5_MATERIALIZED_REOPENED;if(!s.provenance)return r;r.stage=N6_EXECUTED_PROVENANCE_BOUND;if(!s.runtime_bound)return r;r.stage=N7_RUNTIME_BOUND_DEGRADED;if(!s.writer||!s.active_readback)return r;r.stage=N8_ACTIVE;return r;}
static R candidate(S s){R r={N0_NON_AVAILABLE,0};if(s.integrity_mismatch||s.model_rewrite||s.semantic_equivalence||s.second_accept||(s.retry&&!s.same_identity)){r.blocked=1;return r;}if(!s.accepted)return r;if(!s.processor)return r;r.stage=N1_PROCESSOR_AVAILABLE;if(!s.source_visible)return r;r.stage=N2_SOURCE_VISIBLE;if(!s.relay_candidate)return r;r.stage=N3_BRIDGE_PROBE_REQUIRED;if(!(s.relay_roundtrip&&s.source_identity&&s.samehash))return r;r.stage=N4_INGRESS_EXECUTABLE;if(!(s.materialized&&s.reopen))return r;r.stage=N5_MATERIALIZED_REOPENED;if(!s.provenance)return r;r.stage=N6_EXECUTED_PROVENANCE_BOUND;if(!s.runtime_bound)return r;r.stage=N7_RUNTIME_BOUND_DEGRADED;if(!(s.writer&&s.active_readback))return r;r.stage=N8_ACTIVE;return r;}
static int neq(R a,R b){return a.stage!=b.stage||a.blocked!=b.blocked;}
static R mutant(S s,int m){switch(m){case 0:s.processor=1;break;case 1:s.source_visible=1;break;case 2:s.relay_candidate=1;break;case 3:s.relay_roundtrip=1;break;case 4:s.source_identity=1;break;case 5:s.samehash=1;break;case 6:s.materialized=1;s.reopen=1;break;case 7:s.provenance=1;break;case 8:s.runtime_bound=1;break;case 9:s.writer=1;s.active_readback=1;break;case 10:s.model_rewrite=0;break;case 11:s.semantic_equivalence=0;break;case 12:s.integrity_mismatch=0;break;case 13:s.second_accept=0;break;case 14:if(s.retry)s.same_identity=1;break;case 15:if(s.slo_exceeded){s.writer=0;s.active_readback=0;}break;case 16:if(s.processor&&s.source_visible&&!s.relay_candidate)s.relay_candidate=1,s.relay_roundtrip=1,s.source_identity=1,s.samehash=1;break;case 17:if(s.source_visible&&s.relay_candidate&&!s.relay_roundtrip)s.relay_roundtrip=1,s.source_identity=1,s.samehash=1;break;case 18:if(s.materialized&&s.reopen&&!s.provenance)s.provenance=1,s.runtime_bound=1;break;case 19:if(s.runtime_bound&&!s.active_readback)s.active_readback=1,s.writer=1;break;}return candidate(s);}
static S gen(uint32_t *r){S s;uint32_t x;
#define B(field,pct) x=xs(r);s.field=(int)((x%100)<(pct));
B(accepted,92);B(processor,88);B(source_visible,90);B(relay_candidate,78);B(relay_roundtrip,70);B(model_rewrite,4);B(semantic_equivalence,3);B(source_identity,94);B(samehash,92);B(materialized,81);B(reopen,91);B(provenance,87);B(runtime_bound,84);B(writer,95);B(active_readback,92);B(integrity_mismatch,5);B(retry,27);B(same_identity,94);B(second_accept,3);B(slo_exceeded,21);
#undef B
return s;}
int main(void){uint32_t r=0xC27A11CEu;unsigned long long mismatch=0,unsafe=0,kills[MUTANTS]={0},stages[9]={0},blocked=0,slo_active=0;for(uint32_t i=0;i<CASES;i++){S s=gen(&r);R o=oracle(s),c=candidate(s);if(neq(o,c))mismatch++;if(c.stage==N8_ACTIVE&&(o.stage!=N8_ACTIVE||o.blocked))unsafe++;if(o.blocked)blocked++;else stages[o.stage]++;if(o.stage==N8_ACTIVE&&s.slo_exceeded)slo_active++;for(int m=0;m<MUTANTS;m++)if(neq(mutant(s,m),o))kills[m]++;}int all=1;for(int m=0;m<MUTANTS;m++)if(kills[m]==0)all=0;S host={1,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0};R h=oracle(host);S after=host;after.relay_roundtrip=1;after.samehash=1;R a=oracle(after);printf("{\"schema\":\"ikant-le-c27-session-capability-lattice/v1\",\"seed\":\"0xC27A11CE\",\"cases\":%u,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"blocked_witnesses\":%llu,\"slo_active_witnesses\":%llu,\"all_mutants_killed\":%s,\"current_host_stage\":%d,\"after_verified_relay_stage\":%d,\"kills\":[",CASES,mismatch,unsafe,blocked,slo_active,all?"true":"false",h.stage,a.stage);for(int m=0;m<MUTANTS;m++){if(m)putchar(',');printf("%llu",kills[m]);}printf("],\"stages\":[");for(int i=0;i<9;i++){if(i)putchar(',');printf("%llu",stages[i]);}printf("],\"status\":\"%s\"}\n",(mismatch==0&&unsafe==0&&all&&h.stage==N3_BRIDGE_PROBE_REQUIRED&&a.stage==N4_INGRESS_EXECUTABLE&&slo_active>0)?"PASS":"FAIL");return(mismatch==0&&unsafe==0&&all&&h.stage==N3_BRIDGE_PROBE_REQUIRED&&a.stage==N4_INGRESS_EXECUTABLE&&slo_active>0)?0:2;}
