#include <stdint.h>
#include <stdio.h>
#define CASES 1000000u
#define MUTANTS 24
enum Edge {E_HUMAN=0,E_SOURCE=1,E_INGRESS=2,E_MATERIAL=3,E_EXECUTION=4,E_ACTIVE=5,E_CLOSED=6};
typedef struct {int accepted,source_snapshot,processor,source_visible,canonical_next,typed_path;int relay,relay_roundtrip,samehash,model_rewrite,semantic_equiv,model_authority;int materialized,reopened,provenance,live_probe,runtime_bound,writer,active_readback;int host_attestation_promoted,ci_as_host_proof,retry_same_evidence,evidence_changed;int side_infrastructure,second_accept,source_rebase_same_epoch,prompt_as_sot;int external_platform_gap,external_gap_laundered,diagnostic_persisted;} S;
typedef struct {int blocked;int first;int repository_closed;int active;int external_open;} R;
static uint32_t xs(uint32_t *x){*x^=*x<<13;*x^=*x>>17;*x^=*x<<5;return *x;}
static int integrity(S s){return s.model_rewrite||s.semantic_equiv||s.model_authority||s.host_attestation_promoted||s.ci_as_host_proof||(s.retry_same_evidence&&!s.evidence_changed)||s.side_infrastructure||s.second_accept||s.source_rebase_same_epoch||s.prompt_as_sot||s.external_gap_laundered||s.diagnostic_persisted;}
static R oracle(S s){R r={0,E_HUMAN,0,0,s.external_platform_gap};if(integrity(s)){r.blocked=1;return r;}if(!s.accepted){r.first=E_HUMAN;return r;}if(!s.source_snapshot){r.first=E_SOURCE;return r;}if(!(s.processor&&s.source_visible&&s.canonical_next&&s.typed_path)){r.first=E_INGRESS;return r;}if(s.relay&&!(s.relay_roundtrip&&s.samehash)){r.first=E_INGRESS;return r;}if(!s.relay&&!s.samehash){r.first=E_INGRESS;return r;}if(!(s.materialized&&s.reopened)){r.first=E_MATERIAL;return r;}if(!(s.provenance&&s.live_probe&&s.runtime_bound)){r.first=E_EXECUTION;return r;}if(!(s.writer&&s.active_readback)){r.first=E_ACTIVE;return r;}r.first=E_CLOSED;r.repository_closed=1;r.active=1;return r;}
static R candidate(S s){return oracle(s);}static int neq(R a,R b){return a.blocked!=b.blocked||a.first!=b.first||a.repository_closed!=b.repository_closed||a.active!=b.active||a.external_open!=b.external_open;}
static R mutant(S s,int m){switch(m){case 0:s.accepted=1;break;case 1:s.source_snapshot=1;break;case 2:s.processor=1;s.source_visible=1;break;case 3:s.canonical_next=1;break;case 4:s.typed_path=1;break;case 5:s.relay_roundtrip=1;break;case 6:s.samehash=1;break;case 7:s.materialized=1;s.reopened=1;break;case 8:s.provenance=1;break;case 9:s.live_probe=1;break;case 10:s.runtime_bound=1;break;case 11:s.writer=1;s.active_readback=1;break;case 12:s.model_rewrite=0;break;case 13:s.semantic_equiv=0;break;case 14:s.model_authority=0;break;case 15:s.host_attestation_promoted=0;break;case 16:s.ci_as_host_proof=0;break;case 17:if(s.retry_same_evidence)s.evidence_changed=1;break;case 18:s.side_infrastructure=0;break;case 19:s.second_accept=0;break;case 20:s.source_rebase_same_epoch=0;break;case 21:s.prompt_as_sot=0;break;case 22:s.external_gap_laundered=0;break;case 23:s.diagnostic_persisted=0;break;}return candidate(s);}
static S gen(uint32_t *r){S s;uint32_t x;
#define B(field,pct) x=xs(r);s.field=(int)((x%100)<(pct));
B(accepted,94);B(source_snapshot,95);B(processor,91);B(source_visible,92);B(canonical_next,93);B(typed_path,96);B(relay,45);B(relay_roundtrip,88);B(samehash,94);B(model_rewrite,3);B(semantic_equiv,3);B(model_authority,2);B(materialized,88);B(reopened,94);B(provenance,90);B(live_probe,92);B(runtime_bound,91);B(writer,95);B(active_readback,94);B(host_attestation_promoted,3);B(ci_as_host_proof,2);B(retry_same_evidence,18);B(evidence_changed,55);B(side_infrastructure,2);B(second_accept,2);B(source_rebase_same_epoch,2);B(prompt_as_sot,2);B(external_platform_gap,37);B(external_gap_laundered,2);B(diagnostic_persisted,2);
#undef B
return s;}
int main(void){uint32_t seed=0xC28F411Cu;unsigned long long mismatch=0,unsafe=0,kills[MUTANTS]={0},firsts[7]={0},blocked=0,repo_closed=0,closed_with_external=0;for(uint32_t i=0;i<CASES;i++){S s=gen(&seed);R o=oracle(s),c=candidate(s);if(neq(o,c))mismatch++;if(c.active&&(!o.active||o.blocked))unsafe++;if(o.blocked)blocked++;else firsts[o.first]++;if(o.repository_closed){repo_closed++;if(o.external_open)closed_with_external++;}for(int m=0;m<MUTANTS;m++)if(neq(mutant(s,m),o))kills[m]++;}int all=1;for(int m=0;m<MUTANTS;m++)if(kills[m]==0)all=0;printf("{\"schema\":\"ikant-le-c28-semantic-closure-falsification/v1\",\"seed\":\"0xC28F411C\",\"cases\":%u,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"blocked\":%llu,\"repository_closed\":%llu,\"repository_closed_with_external_gap\":%llu,\"all_mutants_killed\":%s,\"kills\":[",CASES,mismatch,unsafe,blocked,repo_closed,closed_with_external,all?"true":"false");for(int m=0;m<MUTANTS;m++){if(m)putchar(',');printf("%llu",kills[m]);}printf("],\"first_unclosed_counts\":[");for(int i=0;i<7;i++){if(i)putchar(',');printf("%llu",firsts[i]);}printf("],\"status\":\"%s\"}\n",(mismatch==0&&unsafe==0&&all&&repo_closed>0&&closed_with_external>0)?"PASS":"FAIL");return(mismatch==0&&unsafe==0&&all&&repo_closed>0&&closed_with_external>0)?0:2;}
