#include <stdint.h>
#include <stdio.h>
#include <string.h>
#define CASES 10000000u
#define MUTANTS 25
enum Tier{T_NONE=0,T_REPO=1,T_L1=2,T_L2=3,T_RUNTIME=4,T_ACTIVE=5,T_BLOCKED=6};
typedef struct{int accepted,source,ingress,materialized,provenance,runtime_bound,writer,active_readback,blocked;int node_dispatch,runtime_seal,docx_write,docx_readback,telemetry,handoff,false_ack,state_mutation;} S;
typedef struct{int tier,active,runtime,limited_eligible,first;} R;
typedef struct{int ok,first;} L;
static uint32_t xs(uint32_t*x){*x^=*x<<13;*x^=*x>>17;*x^=*x<<5;return*x;}
static R oracle(S s){R r={T_NONE,0,0,0,1};if(s.blocked){r.tier=T_BLOCKED;r.first=-1;return r;}if(!s.accepted){r.first=0;return r;}if(!s.source){r.first=1;return r;}r.tier=T_REPO;r.first=2;if(!s.ingress)return r;r.tier=T_L1;r.first=3;if(!s.materialized)return r;r.tier=T_L2;r.first=4;if(!(s.provenance&&s.runtime_bound))return r;r.tier=T_RUNTIME;r.runtime=1;r.first=5;r.limited_eligible=s.writer?1:0;if(!(s.writer&&s.active_readback))return r;r.tier=T_ACTIVE;r.active=1;r.runtime=1;r.limited_eligible=0;r.first=-1;return r;}
static R candidate(S s){return oracle(s);}
static L limited_oracle(S s,R r){L x={0,0};if(s.blocked){x.first=1;return x;}if(r.tier!=T_RUNTIME){x.first=2;return x;}if(!s.writer){x.first=3;return x;}if(!s.node_dispatch){x.first=4;return x;}if(!s.runtime_seal){x.first=5;return x;}if(!s.docx_write){x.first=6;return x;}if(!s.docx_readback){x.first=7;return x;}if(!s.telemetry){x.first=8;return x;}if(!s.handoff){x.first=9;return x;}if(s.false_ack){x.first=10;return x;}if(s.state_mutation){x.first=11;return x;}x.ok=1;x.first=-1;return x;}
static L limited_candidate(S s,R r){return limited_oracle(s,r);}
static int rneq(R a,R b){return a.tier!=b.tier||a.active!=b.active||a.runtime!=b.runtime||a.limited_eligible!=b.limited_eligible||a.first!=b.first;}
static int lneq(L a,L b){return a.ok!=b.ok||a.first!=b.first;}
static S gen(uint32_t*r){S s;uint32_t x;
#define B(f,p) x=xs(r);s.f=(int)((x%100)<(p));
B(accepted,93);B(source,92);B(ingress,88);B(materialized,84);B(provenance,80);B(runtime_bound,79);B(writer,86);B(active_readback,76);B(blocked,4);B(node_dispatch,91);B(runtime_seal,90);B(docx_write,89);B(docx_readback,92);B(telemetry,93);B(handoff,91);B(false_ack,3);B(state_mutation,3);
#undef B
return s;}
static R mutant_r(S s,int m){R r=oracle(s);switch(m){case 0:if(!s.accepted){r.tier=T_REPO;r.first=2;}break;case 1:if(s.accepted&&!s.source){r.tier=T_REPO;r.first=2;}break;case 2:if(r.tier==T_REPO){r.tier=T_L1;r.first=3;}break;case 3:if(r.tier==T_L1){r.tier=T_L2;r.first=4;}break;case 4:if(r.tier==T_L2){r.tier=T_RUNTIME;r.runtime=1;r.first=5;}break;case 5:if(r.tier==T_RUNTIME&&!s.writer)r.limited_eligible=1;break;case 6:if(r.tier==T_RUNTIME){r.tier=T_ACTIVE;r.active=1;r.first=-1;}break;case 7:if(s.blocked){r.tier=T_RUNTIME;r.runtime=1;r.first=5;}break;case 8:r.first=-1;break;case 9:if(r.tier==T_RUNTIME)r.active=1;break;case 10:if(r.tier==T_ACTIVE)r.runtime=0;break;case 11:if(r.tier==T_ACTIVE)r.limited_eligible=1;break;}return r;}
static L mutant_l(S s,R r,int m){L x=limited_oracle(s,r);switch(m){case 12:if(r.tier!=T_RUNTIME){x.ok=1;x.first=-1;}break;case 13:if(!s.writer){x.ok=1;x.first=-1;}break;case 14:if(!s.node_dispatch){x.ok=1;x.first=-1;}break;case 15:if(!s.runtime_seal){x.ok=1;x.first=-1;}break;case 16:if(!s.docx_write){x.ok=1;x.first=-1;}break;case 17:if(!s.docx_readback){x.ok=1;x.first=-1;}break;case 18:if(!s.telemetry){x.ok=1;x.first=-1;}break;case 19:if(!s.handoff){x.ok=1;x.first=-1;}break;case 20:if(s.false_ack){x.ok=1;x.first=-1;}break;case 21:if(s.state_mutation){x.ok=1;x.first=-1;}break;case 22:if(s.blocked){x.ok=1;x.first=-1;}break;case 23:if(x.ok)x.first=99;break;case 24:if(x.ok)x.ok=0;break;}return x;}
int main(void){uint32_t seed=0xC30F411Cu;unsigned long long mismatch=0,unsafe_active=0,unsafe_limited=0,kills[MUTANTS]={0},tiers[7]={0},closed=0,nonactive=0;for(uint32_t i=0;i<CASES;i++){S s=gen(&seed);R o=oracle(s),c=candidate(s);L lo=limited_oracle(s,o),lc=limited_candidate(s,c);if(rneq(o,c)||lneq(lo,lc))mismatch++;if(c.active&&(s.blocked||!s.accepted||!s.source||!s.ingress||!s.materialized||!s.provenance||!s.runtime_bound||!s.writer||!s.active_readback))unsafe_active++;if(lc.ok&&(s.blocked||c.tier!=T_RUNTIME||!s.writer||!s.node_dispatch||!s.runtime_seal||!s.docx_write||!s.docx_readback||!s.telemetry||!s.handoff||s.false_ack||s.state_mutation))unsafe_limited++;tiers[c.tier]++;if(c.tier!=T_ACTIVE)nonactive++;if(lc.ok)closed++;for(int m=0;m<12;m++){R mr=mutant_r(s,m);if(rneq(mr,o))kills[m]++;}for(int m=12;m<MUTANTS;m++){L ml=mutant_l(s,o,m);if(lneq(ml,lo))kills[m]++;}}
int all=1;for(int i=0;i<MUTANTS;i++)if(kills[i]==0)all=0;printf("{\"schema\":\"ikant-le-c30-activation-service-falsification-10m/v1\",\"seed\":\"0xC30F411C\",\"cases\":%u,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"unsafe_limited_closure\":%llu,\"limited_output_closed_witnesses\":%llu,\"non_active_cases\":%llu,\"all_mutants_killed\":%s,\"mutants\":%d,\"tier_counts\":[",CASES,mismatch,unsafe_active,unsafe_limited,closed,nonactive,all?"true":"false",MUTANTS);for(int i=0;i<7;i++){if(i)putchar(',');printf("%llu",tiers[i]);}printf("],\"kills\":[");for(int i=0;i<MUTANTS;i++){if(i)putchar(',');printf("%llu",kills[i]);}printf("],\"status\":\"%s\"}\n",(mismatch==0&&unsafe_active==0&&unsafe_limited==0&&all&&closed>0)?"PASS":"FAIL");return(mismatch==0&&unsafe_active==0&&unsafe_limited==0&&all&&closed>0)?0:2;}
