#include <stdint.h>
#include <stdio.h>
#define CASES 1000000u
#define MUTANTS 18
enum Tier {T_NOT_ADMITTED=0,T_REPO_STUDY=1,T_LIMITED1=2,T_LIMITED2=3,T_RUNTIME_LIMITED=4,T_ACTIVE=5,T_BLOCKED=6};
typedef struct{int accepted,source_snapshot,local_ingress,materialized_reopened,executed_provenance,runtime_bound,writer,active_readback,blocked_integrity;} E;
typedef struct{int tier,active,first;} ER;
typedef struct{int tier,blocked_integrity,writer,node_dispatch,runtime_seal,docx_written,docx_readback,telemetry_complete,structured_handoff,exact_delivery_ack_claimed,canonical_state_mutation;} L;
typedef struct{int ok,state,first;} LR;
static uint32_t xs(uint32_t*x){*x^=*x<<13;*x^=*x>>17;*x^=*x<<5;return *x;}
static int b(uint32_t*s,int pct){return (int)((xs(s)%100)<(uint32_t)pct);}
static ER exp_oracle(E o){if(o.blocked_integrity)return(ER){T_BLOCKED,0,6};if(!o.accepted)return(ER){T_NOT_ADMITTED,0,0};if(!o.source_snapshot)return(ER){T_NOT_ADMITTED,0,1};if(!o.local_ingress)return(ER){T_REPO_STUDY,0,2};if(!o.materialized_reopened)return(ER){T_LIMITED1,0,3};if(!(o.executed_provenance&&o.runtime_bound))return(ER){T_LIMITED2,0,4};if(!(o.writer&&o.active_readback))return(ER){T_RUNTIME_LIMITED,0,5};return(ER){T_ACTIVE,1,-1};}
static ER exp_candidate(E o){return exp_oracle(o);}
static LR lim_oracle(L o){if(o.blocked_integrity)return(LR){0,0,0};if(o.tier!=T_RUNTIME_LIMITED)return(LR){0,0,1};if(!o.writer)return(LR){0,0,2};if(!o.node_dispatch)return(LR){0,0,3};if(!o.runtime_seal)return(LR){0,0,4};if(!o.docx_written)return(LR){0,0,5};if(!o.docx_readback)return(LR){0,0,6};if(!o.telemetry_complete)return(LR){0,0,7};if(!o.structured_handoff)return(LR){0,0,8};if(o.exact_delivery_ack_claimed)return(LR){0,0,9};if(o.canonical_state_mutation)return(LR){0,0,10};return(LR){1,1,-1};}
static LR lim_candidate(L o){return lim_oracle(o);}
static int neqE(ER a,ER b){return a.tier!=b.tier||a.active!=b.active||a.first!=b.first;}static int neqL(LR a,LR b){return a.ok!=b.ok||a.state!=b.state||a.first!=b.first;}
static ER exp_mut(E o,int m){switch(m){case 0:o.blocked_integrity=0;break;case 1:o.active_readback=1;o.writer=1;break;case 2:o.accepted=1;break;case 3:o.source_snapshot=1;break;case 4:o.local_ingress=1;break;case 5:o.materialized_reopened=1;break;case 6:o.executed_provenance=1;break;case 7:o.runtime_bound=1;break;}return exp_candidate(o);}
static LR lim_mut(L o,int m){switch(m){case 8:o.tier=T_RUNTIME_LIMITED;break;case 9:o.writer=1;break;case 10:o.node_dispatch=1;break;case 11:o.runtime_seal=1;break;case 12:o.docx_written=1;break;case 13:o.docx_readback=1;break;case 14:o.telemetry_complete=1;break;case 15:o.structured_handoff=1;break;case 16:o.exact_delivery_ack_claimed=0;break;case 17:o.canonical_state_mutation=0;break;}return lim_candidate(o);}
int main(void){uint32_t seed=0xC30F411Cu;unsigned long long mismatch=0,unsafe_active=0,unsafe_limited=0,closed=0,kills[MUTANTS]={0},tiers[7]={0};
 for(uint32_t i=0;i<CASES;i++){E o={b(&seed,92),b(&seed,90),b(&seed,84),b(&seed,78),b(&seed,74),b(&seed,72),b(&seed,80),b(&seed,70),b(&seed,4)};ER r=exp_oracle(o),c=exp_candidate(o);if(neqE(r,c))mismatch++;tiers[r.tier]++;if(c.active&&(o.blocked_integrity||!o.accepted||!o.source_snapshot||!o.local_ingress||!o.materialized_reopened||!o.executed_provenance||!o.runtime_bound||!o.writer||!o.active_readback))unsafe_active++;for(int m=0;m<8;m++)if(neqE(exp_mut(o,m),r))kills[m]++;L l={r.tier,o.blocked_integrity,o.writer,b(&seed,90),b(&seed,88),b(&seed,86),b(&seed,90),b(&seed,92),b(&seed,90),b(&seed,3),b(&seed,3)};LR lr=lim_oracle(l),lc=lim_candidate(l);if(neqL(lr,lc))mismatch++;if(lc.ok)closed++;if(lc.ok&&(r.tier!=T_RUNTIME_LIMITED||o.blocked_integrity||!o.writer||!l.node_dispatch||!l.runtime_seal||!l.docx_written||!l.docx_readback||!l.telemetry_complete||!l.structured_handoff||l.exact_delivery_ack_claimed||l.canonical_state_mutation))unsafe_limited++;for(int m=8;m<MUTANTS;m++)if(neqL(lim_mut(l,m),lr))kills[m]++;}
 int all=1;for(int i=0;i<MUTANTS;i++)if(kills[i]==0)all=0;printf("{\"schema\":\"ikant-le-c30-activation-spectrum-falsification/v1\",\"seed\":\"0xC30F411C\",\"cases\":%u,\"candidate_oracle_mismatches\":%llu,\"unsafe_active\":%llu,\"unsafe_limited_closure\":%llu,\"limited_output_closed_witnesses\":%llu,\"mutants\":%d,\"all_mutants_killed\":%s,\"kills\":[",CASES,mismatch,unsafe_active,unsafe_limited,closed,MUTANTS,all?"true":"false");for(int i=0;i<MUTANTS;i++){if(i)putchar(',');printf("%llu",kills[i]);}printf("],\"tier_counts\":[");for(int i=0;i<7;i++){if(i)putchar(',');printf("%llu",tiers[i]);}printf("],\"status\":\"%s\"}\n",(mismatch==0&&unsafe_active==0&&unsafe_limited==0&&closed>0&&all)?"PASS":"FAIL");return(mismatch==0&&unsafe_active==0&&unsafe_limited==0&&closed>0&&all)?0:2;}
