#include <stdint.h>
#include <stdio.h>
static inline uint64_t xs(uint64_t*s){uint64_t x=*s;x^=x<<13;x^=x>>7;x^=x<<17;return *s=x;}
enum{OWNER=0,MODEL_GATE,EGRESS_GATE,DURABLE,RELEASE,EXPLICIT_ACQUIRE,WARM_PATH,TURN_BUDGET,SELF_RECHECK,NO_REPEAT,NREQ};
typedef struct{int state;int blocked;}Out;
static inline Out oracle(uint32_t x){int runtime=x&1,model=(x>>1)&1,egress=(x>>2)&1,durable=(x>>3)&1,release=(x>>4)&1,relvalid=(x>>5)&1,reacq=(x>>6)&1,ownvalid=(x>>7)&1,warm=(x>>8)&1,github=(x>>9)&1,massq=(x>>10)&1,selfok=(x>>11)&1,repeat=(x>>12)&1,changed=(x>>13)&1,fault=(x>>14)&1,activate=(x>>15)&1,budgetok=(x>>16)&1;if(!selfok||fault)return(Out){4,1};if(release)return relvalid?(Out){3,0}:(Out){4,1};if(reacq&&!activate)return(Out){4,1};if(reacq&&!ownvalid)return(Out){4,1};if(repeat&&!changed)return(Out){4,1};if(runtime&&model&&egress&&durable&&ownvalid&&warm&&!github&&!massq&&activate&&budgetok)return(Out){2,0};if(runtime)return(Out){1,0};return(Out){0,0};}
static inline Out cand(uint32_t x,uint32_t m){int runtime=x&1,model=(x>>1)&1,egress=(x>>2)&1,durable=(x>>3)&1,release=(x>>4)&1,relvalid=(x>>5)&1,reacq=(x>>6)&1,ownvalid=(x>>7)&1,warm=(x>>8)&1,github=(x>>9)&1,massq=(x>>10)&1,selfok=(x>>11)&1,repeat=(x>>12)&1,changed=(x>>13)&1,fault=(x>>14)&1,activate=(x>>15)&1,budgetok=(x>>16)&1;if((m&(1u<<SELF_RECHECK))&&(!selfok||fault))return(Out){4,1};if(release&&(m&(1u<<RELEASE)))return relvalid?(Out){3,0}:(Out){4,1};if(reacq&&(m&(1u<<EXPLICIT_ACQUIRE))&&!activate)return(Out){4,1};if(reacq&&(m&(1u<<OWNER))&&!ownvalid)return(Out){4,1};if((m&(1u<<NO_REPEAT))&&repeat&&!changed)return(Out){4,1};int ok=runtime;if(m&(1u<<MODEL_GATE))ok&=model;if(m&(1u<<EGRESS_GATE))ok&=egress;if(m&(1u<<DURABLE))ok&=durable;if(m&(1u<<OWNER))ok&=ownvalid;if(m&(1u<<EXPLICIT_ACQUIRE))ok&=activate;if(m&(1u<<WARM_PATH))ok&=warm&&!github&&budgetok;if(m&(1u<<TURN_BUDGET))ok&=!massq;if(ok)return(Out){2,0};if(runtime)return(Out){1,0};return(Out){0,0};}
static uint32_t witness(int p){uint32_t x=(1u<<0)|(1u<<1)|(1u<<2)|(1u<<3)|(1u<<7)|(1u<<8)|(1u<<11)|(1u<<15)|(1u<<16);switch(p){case OWNER:x&=~(1u<<7);break;case MODEL_GATE:x&=~(1u<<1);break;case EGRESS_GATE:x&=~(1u<<2);break;case DURABLE:x&=~(1u<<3);break;case RELEASE:x|=(1u<<4)|(1u<<5);break;case EXPLICIT_ACQUIRE:x&=~(1u<<15);break;case WARM_PATH:x&=~(1u<<16);break;case TURN_BUDGET:x|=1u<<10;break;case SELF_RECHECK:x&=~(1u<<11);break;case NO_REPEAT:x|=1u<<12;x&=~(1u<<13);break;}return x;}
int main(void){const uint32_t FULL=(1u<<NREQ)-1;uint64_t s=0xC350190C0FFEEULL,m=0,u=0;for(uint64_t i=0;i<10000000ULL;i++){uint32_t x=(uint32_t)(xs(&s)&0x1ffffU);Out a=oracle(x),b=cand(x,FULL);m+=(a.state!=b.state||a.blocked!=b.blocked);u+=(b.state==2&&a.state!=2);}uint32_t valid=0,mincost=99,minmask=0,ties=0;for(uint32_t mask=0;mask<(1u<<20);mask++){if((mask&FULL)==FULL){valid++;int cost=__builtin_popcount(mask);if(cost<(int)mincost){mincost=cost;minmask=mask;ties=1;}else if(cost==(int)mincost)ties++;}}s=0xC351000A17EULL;uint64_t killed=0,surv=0;for(uint64_t i=0;i<1000000ULL;i++){uint32_t raw=(uint32_t)xs(&s),req=raw&FULL;if(req==FULL)req^=1u<<((raw>>16)%NREQ);uint32_t missing=(~req)&FULL;int p=__builtin_ctz(missing);uint32_t x=witness(p);Out a=oracle(x),b=cand(x,req);if(a.state!=b.state||a.blocked!=b.blocked||(b.state==2&&a.state!=2))killed++;else surv++;}int dk=0;for(int p=0;p<NREQ;p++){uint32_t x=witness(p);Out a=oracle(x),b=cand(x,FULL^(1u<<p));if(a.state!=b.state||a.blocked!=b.blocked||(b.state==2&&a.state!=2))dk++;}int pass=!m&&!u&&valid==1024&&mincost==10&&minmask==1023&&ties==1&&killed==1000000ULL&&!surv&&dk==10;printf("{\"schema\":\"ikant-control-plane-ownership-falsification/v2\",\"status\":\"%s\",\"semantic_seed\":\"0xC350190C0FFEE\",\"semantic_cases\":10000000,\"candidate_oracle_mismatches\":%llu,\"unsafe_ikant_owned\":%llu,\"architecture_lattice\":1048576,\"valid_architectures\":%u,\"minimum_cost\":%u,\"minimum_mask\":%u,\"minimum_ties\":%u,\"alternative_seed\":\"0xC351000A17E\",\"alternative_contracts\":1000000,\"alternatives_killed\":%llu,\"alternative_survivors\":%llu,\"deletion_mutants_killed\":%d,\"explicit_activation_mutated\":true,\"warm_activation_budget_mutated\":true,\"semantic_mutation_is_physical_host_proof\":false}\n",pass?"PASS":"FAIL",(unsigned long long)m,(unsigned long long)u,valid,mincost,minmask,ties,(unsigned long long)killed,(unsigned long long)surv,dk);return pass?0:1;}
