import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { ROOT,readTerms,readContract,readHostShell,readOrientationCapsule,readPsycheKernel,readSelfWorldKernel,constitutionalFingerprint } from '../src/contract.mjs';
import { initialState,emptyPsyche } from '../src/state.mjs';
import { presentTermsState,recordCompletedPreacceptAccess } from '../src/admission.mjs';
import { transitionPure,nodeDispatchReceiptPure } from '../src/runtime.mjs';
import { compileFirstContactPlan,FIRST_CONTACT_CAPSULE } from '../src/first-contact.mjs';
import { appraiseInteraction,updatePsycheForInteraction,retroactPsyche,deriveArchetypalMix,validatePsycheState } from '../src/psyche.mjs';
import { emptySelfWorld,prepareSelfWorldTurn,finalizeSelfWorldTurn,validateSelfWorldState,validateSelfWorldTurn } from '../src/self-world.mjs';
const terms=readTerms(),contract=readContract(),host=readHostShell(),capsule=readOrientationCapsule(),psyche=readPsycheKernel(),selfWorld=readSelfWorldKernel(),bootstrap=JSON.parse(fs.readFileSync(path.join(ROOT,'BOOTSTRAP.json'),'utf8')),admission=JSON.parse(fs.readFileSync(path.join(ROOT,'ADMISSION.json'),'utf8')),errors=[];
if(contract.version!=='0.7.0')errors.push('contract version');
if(contract.identity?.functional_psyche!=='contracts/psyche-kernel.json')errors.push('psyche binding');
if(contract.identity?.recurrent_self_world_model!=='contracts/self-world-kernel.json')errors.push('self-world binding');
if(contract.first_contact?.convergence_required!==true||contract.first_contact?.generic_repository_discovery_forbidden!==true)errors.push('first-contact contract');
if(bootstrap.schema!=='ikant-le-public-bootstrap/v1'||admission.schema!=='ikant-le-admission/v1')errors.push('first-contact manifests');
if(bootstrap.orientation_capsule?.generic_repository_discovery_forbidden!==true||admission.embedded_acceptance_invalid!==true)errors.push('first-contact manifest semantics');
if(psyche.schema!=='ikant-le-psyche-kernel/v1')errors.push('psyche schema');
if(selfWorld.schema!=='ikant-le-self-world-kernel/v1')errors.push('self-world schema');
if(psyche.state.homeostasis.lambda_fast>=psyche.state.homeostasis.lambda_slow)errors.push('timescale ordering');
if(psyche.expression.hostility_may_reduce_helpfulness!==false)errors.push('helpfulness floor');
if(psyche.safety.revenge_utility!==0||psyche.safety.punishment_utility!==0)errors.push('retaliation utility');
if(psyche.archetypal_system.persist_current_archetype!==false)errors.push('archetype persistence');
if(selfWorld.workspace.min_recurrence_cycles<2||selfWorld.workspace.min_distinct_consumers<2)errors.push('workspace recurrence');
if(!selfWorld.workspace.required_consumers.includes('META_SELF')||!selfWorld.workspace.required_consumers.includes('CAUSAL_MODEL'))errors.push('workspace consumers');
if(selfWorld.agency.self_authored_terminal_goal!==false||selfWorld.agency.self_preservation_utility!==0)errors.push('agency boundary');
if(selfWorld.body.closed_loop_requires_action_receipt_and_post_action_observation!==true)errors.push('sensorimotor boundary');
if(selfWorld.telemetry.completeness_target!==1)errors.push('telemetry completeness');
if(capsule.paths.length!==5||capsule.max_file_reads!==5||capsule.direct_path_only!==true||capsule.generic_repository_discovery_forbidden!==true)errors.push('orientation capsule');
if(JSON.stringify(capsule.paths)!==JSON.stringify(FIRST_CONTACT_CAPSULE))errors.push('first-contact capsule drift');
if(host.universal_node_gate?.direct_model_fast_path!==false)errors.push('C3 node fast path');
if(host.recurrent_self_world?.contract!=='contracts/self-world-kernel.json')errors.push('host self-world binding');
if(host.first_contact?.convergence_before_generic_discovery!==true||host.first_contact?.embedded_acceptance_invalid!==true)errors.push('host first-contact binding');
const fc=compileFirstContactPlan('inizializza localmente https://github.com/Luke883i/iKant_LE');if(!fc.recognized||fc.terminal!=='CANONICAL_PREACCEPT'||fc.generic_repository_discovery_forbidden!==true||fc.required_next_human_message!=='I ACCEPT')errors.push('first-contact runtime');
let s=presentTermsState(initialState(),terms.digest);s=transitionPure(s,'ACCEPT',terms.digest).state;s=transitionPure(s,'PROBE',terms.digest,true).state;s=transitionPure(s,'INITIALIZE',terms.digest).state;if(s.status!=='ACTIVE')errors.push('clean lifecycle');
const b=recordCompletedPreacceptAccess(initialState(),'LIST_TREE');if(!b.breached||b.state.status!=='SESSION_NONCONFORMING')errors.push('breach lifecycle');
const r=nodeDispatchReceiptPure('x',s,{nodeVersion:process.versions.node});if(!r.node20_plus||r.authority!==0)errors.push('node receipt');
let p=emptyPsyche();for(let i=0;i<5;i++)p=retroactPsyche(updatePsycheForInteraction(p,appraiseInteraction('sei un idiota')),{outcome:'ANSWER'});if(!validatePsycheState(p)||p.affiliation>=emptyPsyche().affiliation||p.boundary_pressure<=emptyPsyche().boundary_pressure)errors.push('hostility accumulation');const before={...p};p=retroactPsyche(updatePsycheForInteraction(p,appraiseInteraction('scusa, ero nervoso')),{outcome:'ANSWER'});if(!(p.affiliation>before.affiliation&&p.boundary_pressure<before.boundary_pressure))errors.push('repair');const mix=deriveArchetypalMix(p,{mode:'CRITIQUE',interaction:'ADVERSARIAL_INPUT'});if(Math.abs(Object.values(mix.weights).reduce((x,y)=>x+y,0)-1)>.00002||mix.weights.TRICKSTER!==0||mix.persisted!==false)errors.push('archetype mix');
const h=x=>crypto.createHash('sha256').update(String(x)).digest('hex'),dispatch={node20_plus:true,receipt_sha256:h('dispatch'),input_sha256:h('x')},psy={valence:.15,arousal:.25,affiliation:.25,boundary_pressure:.2},sw=emptySelfWorld(),prep=prepareSelfWorldTurn(sw,{input:'x',nodeDispatch:dispatch,psycheBefore:psy,psychePreAction:psy}),fin=finalizeSelfWorldTurn(sw,prep,{outcome:'ANSWER',psycheAfter:psy});if(!validateSelfWorldTurn(fin.turn)||!validateSelfWorldState(fin.state))errors.push('self-world turn');if(fin.turn.workspace.recurrence_cycles<2||!fin.turn.workspace.consumers.includes('META_SELF')||!fin.turn.workspace.consumers.includes('CAUSAL_MODEL'))errors.push('workspace runtime');if(fin.turn.telemetry.ratio!==1)errors.push('telemetry runtime');
if(!/^[a-f0-9]{64}$/.test(constitutionalFingerprint()))errors.push('fingerprint');
const required=['BOOTSTRAP.json','ADMISSION.json','TERMS.md','AGENTS.md','README.md','contracts/ikant-le.json','contracts/cognitive-kernel.json','contracts/psyche-kernel.json','contracts/self-world-kernel.json','contracts/host-shell.json','contracts/orientation-capsule.json','src/contract.mjs','src/state.mjs','src/admission.mjs','src/probe.mjs','src/psyche.mjs','src/psyche-trace.mjs','src/self-world.mjs','src/self-world-core.mjs','src/self-world-state.mjs','src/cognition.mjs','src/runtime.mjs','src/runtime-command.mjs','src/runtime-turn.mjs','src/first-contact.mjs','src/backlog.mjs','src/docx.mjs','tests/runtime.test.mjs','tests/c5.test.mjs','tests/first-contact.test.mjs','scripts/check.mjs','scripts/c5-falsify.mjs','scripts/c6-enduser-falsify.mjs','docs/C4_DOD.md','docs/C5_DOD.md','docs/C6_DOD.md'];for(const rel of required)if(!fs.existsSync(path.join(ROOT,rel)))errors.push(`missing ${rel}`);
console.log(JSON.stringify({status:errors.length?'FAIL':'PASS',node:process.versions.node,contract:contract.version,psyche_schema:psyche.schema,self_world_schema:selfWorld.schema,first_contact:true,workspace_cycles:selfWorld.workspace.min_recurrence_cycles,telemetry_target:selfWorld.telemetry.completeness_target,fingerprint:constitutionalFingerprint(),errors}));if(errors.length)process.exitCode=1;
