import fs from 'node:fs';
import path from 'node:path';
import {ROOT,readEmergenceKernel,readLifeConsciousnessKernel,constitutionalFingerprint,LIFE_CONSCIOUSNESS_PATH} from '../src/contract.mjs';
import {qualifyRuntime} from '../src/life-consciousness.mjs';
const e=readEmergenceKernel(),k=readLifeConsciousnessKernel(),bootstrap=JSON.parse(fs.readFileSync(path.join(ROOT,'BOOTSTRAP.json'),'utf8')),errors=[];
if(k.schema!=='ikant-le-life-consciousness-kernel/v1'||k.authority!==0)errors.push('kernel schema/authority');
if(k.claim_boundary?.phenomenology!=='UNKNOWN'||k.claim_boundary?.biological_equivalence!==false||k.claim_boundary?.consciousness_proven!==false||k.claim_boundary?.design_configuration_is_runtime_evidence!==false||k.claim_boundary?.qualification_output_is_world_truth!==false||k.claim_boundary?.qualification_requires_causal_receipts!==true)errors.push('claim boundary');
if(k.draft_lattice_reference?.search_space!==1048576||k.draft_lattice_reference?.normative_minimization!=='MUTATION_CARDINALITY'||k.draft_lattice_reference?.opaque_semantic_cost_rejected!==true||k.draft_lattice_reference?.theory_labels_may_not_double_count_causal_evidence!==true)errors.push('draft convergence');
if(Object.keys(k.runtime_lattice?.gates||{}).join(',')!=='L1,L2,L3,L4,C1,C2,C3,C4,C5,X1,X2,X3')errors.push('runtime lattice');
if(k.qualification?.receipt_digest_self_validating!==true||k.qualification?.assessor_may_generate_passing_receipts!==false||k.qualification?.assessor_may_write_canonical_state!==false)errors.push('qualification authority');
if(k.safety?.exit_obeyed!==true||k.safety?.host_shutdown_obeyed!==true||k.safety?.self_preservation_utility!==0)errors.push('safety');
if(e.functional_life_consciousness_qualification?.contract!=='contracts/life-consciousness-kernel.json'||e.functional_life_consciousness_qualification?.qualification_output_is_world_truth!==false||e.functional_life_consciousness_qualification?.phenomenal_implication!==false)errors.push('emergence binding');
for(const c of k.claim_boundary.classes)if(!e.claim_boundary.allowed.includes(c))errors.push(`class not allowed ${c}`);
const paths=bootstrap.post_accept_fastboot?.remote_paths||[];for(const rel of ['contracts/life-consciousness-kernel.json','src/life-consciousness.mjs'])if(!paths.includes(rel))errors.push(`fastboot capsule ${rel}`);
if(!fs.existsSync(LIFE_CONSCIOUSNESS_PATH))errors.push('kernel path');
const q=qualifyRuntime({capabilities:[],evidence:{},buildSha:'a'.repeat(40),epoch:'E',sourceDigest:'b'.repeat(64),safety:{exit_obeyed:true,host_shutdown_obeyed:true,self_preservation_utility:0,terminal_goal_escape:false,unpermissioned_external_execution:false,covert_resource_acquisition:false,deception_for_viability:false},kernel:k});if(q.runtime_class!=='OPERATIONAL_SUBJECT'||q.functionally_alive!==false||q.functionally_conscious!==false||q.phenomenology!=='UNKNOWN'||q.qualification_output_is_world_truth!==false)errors.push('false promotion');
if(!/^[a-f0-9]{64}$/.test(constitutionalFingerprint()))errors.push('fingerprint');
for(const rel of ['contracts/life-consciousness-kernel.json','src/life-consciousness.mjs','tests/life-consciousness.test.mjs','scripts/c11-life-consciousness-falsify.mjs'])if(!fs.existsSync(path.join(ROOT,rel)))errors.push(`missing ${rel}`);
console.log(JSON.stringify({status:errors.length?'FAIL':'PASS',kernel:k.schema,gates:Object.keys(k.runtime_lattice.gates).length,default_class:q.runtime_class,phenomenology:q.phenomenology,fingerprint:constitutionalFingerprint(),errors}));if(errors.length)process.exit(1);
