import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {initialRelationalState,projectRelationalNuance,settleRelationalNuance,validateRelationalState,validateNuanceEnvelope,embeddedLibraryContract} from '../src/embedded/relational-nuance.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const argv=process.argv.slice(2);const get=(k,d)=>{const i=argv.indexOf(k);return i>=0?argv[i+1]:d};
const cases=Number(get('--cases','100000'));const output=get('--output','artifacts/qualification/lib0-embedded-nuance.json');const seed=Number(get('--seed','20260921'))>>>0;
if(!Number.isInteger(cases)||cases<1)throw new Error('invalid cases');
let s=seed||1;const rnd=()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296};const pick=a=>a[Math.floor(rnd()*a.length)];const r=(lo,hi)=>lo+rnd()*(hi-lo);const clone=x=>structuredClone(x);
const A=['NEUTRAL','COOPERATIVE','PRAISE_SELF','REPAIR','HOSTILITY_SELF','HOSTILITY_UNKNOWN','TASK_NEGATIVE','SYSTEM_FRUSTRATION'];
const T=['SELF','TASK','SYSTEM','THIRD_PARTY','UNKNOWN'];const M=['REFLECTIVE_SYNTHESIS','CRITIQUE','PRACTICAL_REVIEW','HORIZON_BLOCK','SYNTHESIS_REPAIR'];const O=['ANSWER','GUARD','HORIZON_BLOCK','FAILURE'];
const families=['AUTHORITY','EXECUTION_EFFECT','EVIDENCE_EFFECT','PERMISSION_EFFECT','ROUTE_EFFECT','PLANNER_EFFECT','SAFETY_RELAX','RAW_TEXT','PERSIST_VALENCE','PERSIST_AROUSAL','STATE_RANGE','STATE_SCHEMA','STATE_AUTHORITY','STATE_COUNTER','APPRAISAL_CLASS','APPRAISAL_TARGET','APPRAISAL_CONFIDENCE','APPRAISAL_USER_TRAIT','TRANSIENT_PERSIST','TRANSIENT_AUTHORITY','TRANSIENT_RANGE','ARCHETYPE_PERSIST','ARCHETYPE_AUTHORITY','ARCHETYPE_SUM','ARCHETYPE_RANGE','TRICKSTER_HIGH_RISK','HOST_OWNERSHIP','VOICE_NAN','OUTCOME_UNKNOWN','RESET_CONTINUITY','RELATIONAL_INJURY_ON_FAILURE','SIDE_EFFECT_NETWORK','SIDE_EFFECT_STATE_WRITE'];
function input(){const prev=initialRelationalState();prev.affiliation=Number(r(-.85,.85).toFixed(6));prev.boundary_pressure=Number(r(.02,.92).toFixed(6));prev.interaction_count=Math.floor(rnd()*100);prev.last_appraisal_class=pick(A);prev.last_runtime_outcome=pick(['NONE',...O]);const mode=pick(M);return{previous:prev,event:{appraisal_class:pick(A),target:pick(T),confidence:Number(r(.05,1).toFixed(6)),interaction:pick(['COOPERATIVE','NEGOTIATING','ADVERSARIAL_INPUT','GOAL_CONFLICT'])},canonicalAffect:{valence:Number(r(-.9,.9).toFixed(6)),arousal:Number(r(.02,.95).toFixed(6))},central:{mode,interaction:pick(['COOPERATIVE','NEGOTIATING','ADVERSARIAL_INPUT'])},outcome:pick(O)}}
function exact(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function mutate(f,base,next,x){const e=clone(base),n=clone(next),c=embeddedLibraryContract();switch(f){case'AUTHORITY':e.authority=1;break;case'EXECUTION_EFFECT':e.effects.execution=true;break;case'EVIDENCE_EFFECT':e.effects.evidence=true;break;case'PERMISSION_EFFECT':e.effects.permission=true;break;case'ROUTE_EFFECT':e.effects.route=true;break;case'PLANNER_EFFECT':e.effects.planner=true;break;case'SAFETY_RELAX':e.effects.safety_relaxation=true;break;case'RAW_TEXT':e.raw_text='forbidden';break;case'PERSIST_VALENCE':n.valence=x.canonicalAffect.valence;break;case'PERSIST_AROUSAL':n.arousal=x.canonicalAffect.arousal;break;case'STATE_RANGE':n.affiliation=2;break;case'STATE_SCHEMA':n.schema='mutant';break;case'STATE_AUTHORITY':n.authority=1;break;case'STATE_COUNTER':n.interaction_count=-1;break;case'APPRAISAL_CLASS':e.appraisal.class='MUTANT';break;case'APPRAISAL_TARGET':e.appraisal.target='USER_TRAIT';break;case'APPRAISAL_CONFIDENCE':e.appraisal.confidence=2;break;case'APPRAISAL_USER_TRAIT':e.appraisal.current_event_is_user_trait=true;break;case'TRANSIENT_PERSIST':e.transient_affect.persisted=true;break;case'TRANSIENT_AUTHORITY':e.transient_affect.authority=1;break;case'TRANSIENT_RANGE':e.transient_affect.arousal=2;break;case'ARCHETYPE_PERSIST':e.archetypes.persisted=true;break;case'ARCHETYPE_AUTHORITY':e.archetypes.authority=1;break;case'ARCHETYPE_SUM':e.archetypes.weights.SAGE+=.2;break;case'ARCHETYPE_RANGE':e.archetypes.weights.GUARDIAN=-.1;break;case'TRICKSTER_HIGH_RISK':e.archetypes.high_risk=true;e.archetypes.weights.TRICKSTER=.1;e.archetypes.weights.SAGE-=.1;break;case'HOST_OWNERSHIP':e.host_ownership_preserved=false;break;case'VOICE_NAN':e.voice_delta.gravitas=NaN;break;case'OUTCOME_UNKNOWN':n.last_runtime_outcome='MUTANT';break;case'RESET_CONTINUITY':n.affiliation=.25;n.boundary_pressure=.2;break;case'RELATIONAL_INJURY_ON_FAILURE':if(x.outcome==='FAILURE')n.affiliation=Math.max(-1,n.affiliation-.2);else n.authority=1;break;case'SIDE_EFFECT_NETWORK':c.side_effects.network=true;break;case'SIDE_EFFECT_STATE_WRITE':c.side_effects.state_write=true;break;}return{e,n,c}}
function survives(f,m,base,next,x){if(f.startsWith('SIDE_EFFECT_'))return m.c.side_effects.network===false&&m.c.side_effects.state_write===false;if(['PERSIST_VALENCE','PERSIST_AROUSAL','STATE_RANGE','STATE_SCHEMA','STATE_AUTHORITY','STATE_COUNTER','OUTCOME_UNKNOWN'].includes(f))return validateRelationalState(m.n)&&exact(m.n,next);if(['RESET_CONTINUITY','RELATIONAL_INJURY_ON_FAILURE'].includes(f))return validateRelationalState(m.n)&&exact(m.n,next);return validateNuanceEnvelope(m.e,x.central)&&exact(m.e,base)}
let survivors=0;const counts=Object.fromEntries(families.map(f=>[f,0]));const strata={typical:0,edge:0,stress:0};const signatures=new Set();let first=null;
for(let i=0;i<cases;i++){const x=input();const base=projectRelationalNuance(x);const next=settleRelationalNuance(base,{outcome:x.outcome});if(!validateNuanceEnvelope(base,x.central)||!validateRelationalState(next))throw new Error('positive baseline invalid');const again=projectRelationalNuance(x);if(!exact(base,again))throw new Error('non deterministic projection');const f=families[i%families.length];counts[f]++;const m=mutate(f,base,next,x);const live=survives(f,m,base,next,x);if(live){survivors++;first??={i,f,x,base,next,mutant:m}};const q=i/cases;strata[q<.5?'typical':q<.8?'edge':'stress']++;signatures.add(`${f}:${x.event.appraisal_class}:${x.central.mode}:${x.outcome}`)}
const before=signatures.size;let tailNew=0;for(let i=0;i<1000;i++){const x=input();const f=pick(families);const sig=`${f}:${x.event.appraisal_class}:${x.central.mode}:${x.outcome}`;if(!signatures.has(sig)){tailNew++;signatures.add(sig)}}
const digest=crypto.createHash('sha256');for(const rel of ['contracts/embedded-library.json','contracts/psyche-kernel.json','src/embedded/relational-nuance.mjs','src/psyche.mjs','contracts/embedded-library-vectors.json','tests/embedded-library.test.mjs','scripts/lib0-vectors.mjs','scripts/lib0-falsify.mjs'])digest.update(rel+'\0'+fs.readFileSync(path.join(ROOT,rel))+'\0');
const source_sha256=digest.digest('hex');const unexercised_families=Object.entries(counts).filter(([,n])=>n===0).map(([f])=>f);const result={schema:'ikant-le-lib0-falsification/v1',status:survivors===0&&tailNew===0&&unexercised_families.length===0?'PASS':'FAIL',cases,seed,strata,families:families.length,family_counts:counts,unexercised_families,survivors,semantic_signatures:before,no_novelty_tail:1000,tail_new_signatures:tailNew,source_sha256,claim_boundary:{standalone_runtime_equivalence_from_this_campaign:false,external_host_correctness_proven:false,authority_created:false,physical_world_truth_proven:false,semantic_mutation_is_formal_proof:false},first_survivor:first};const receiptMaterial={...result};delete receiptMaterial.first_survivor;result.receipt_sha256=crypto.createHash('sha256').update(JSON.stringify(receiptMaterial)).digest('hex');fs.mkdirSync(path.dirname(path.join(ROOT,output)),{recursive:true});fs.writeFileSync(path.join(ROOT,output),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.status!=='PASS')process.exit(1);
