import fs from 'node:fs';
import path from 'node:path';
import { ROOT,readOrientationCapsule,sha256 } from './contract.mjs';
export const ORIENTATION_ACTIONS=Object.freeze({METADATA:'READ_ORIENTATION_METADATA',FILE:'READ_ORIENTATION_FILE',PRESENT_TERMS:'PRESENT_TERMS'});
const REPO_ACCESS=new Set(['CLONE_REPOSITORY','GIT_FETCH','GIT_LS_REMOTE','GH_CLI','RAW_WEB_READ','DIRECT_DOWNLOAD','ARCHIVE_DOWNLOAD','SHELL_HTTP_DOWNLOAD','LIST_TREE','SEARCH_REPOSITORY','READ_ARBITRARY_REPOSITORY_FILE','READ_HISTORY','READ_ISSUE_PR','MATERIALIZE_CHECKOUT']);
const CANONICAL_REPOSITORY='Luke883i/iKant_LE';
export function preservePendingIntent(state,input){const s=structuredClone(state);if(!s.admission.pending_intent){s.admission.pending_intent=String(input);s.admission.pending_intent_sha256=sha256(Buffer.from(String(input)));}return s;}
export function presentTermsState(state,termsDigest){const s=structuredClone(state);if(s.admission.breached)return s;s.admission.phase='AWAITING_ACCEPTANCE';s.admission.terms_presented=true;s.admission.terms_digest=termsDigest;return s;}
export function authorizePreaccept(state,action,{target=null,byteCount=0,metadataFields=[]}={}){const c=readOrientationCapsule();const s=structuredClone(state);if(s.admission.breached)return{allowed:false,state:s,terminal:'SESSION_NONCONFORMING',code:'DENY_BREACHED'};if(s.accepted)return{allowed:true,state:s,terminal:'POST_ACCEPT'};if(s.admission.terms_presented&&action!==ORIENTATION_ACTIONS.PRESENT_TERMS)return{allowed:false,state:s,terminal:'AWAITING_ACCEPTANCE',code:'DENY_ORIENTATION_FROZEN'};if(action===ORIENTATION_ACTIONS.METADATA){if(s.admission.metadata_reads>=c.max_metadata_reads)return{allowed:false,state:s,terminal:s.status,code:'DENY_METADATA_REPEAT'};if(metadataFields.some(x=>!c.metadata_fields.includes(x)))return{allowed:false,state:s,terminal:s.status,code:'DENY_METADATA_SCOPE'};s.admission.metadata_reads++;s.admission.phase='ORIENTING';return{allowed:true,state:s,terminal:'ORIENTING',code:'ALLOW_ORIENTATION_METADATA'};}if(action===ORIENTATION_ACTIONS.FILE){if(!c.paths.includes(target))return{allowed:false,state:s,terminal:s.status,code:'DENY_OUTSIDE_CAPSULE'};if(s.admission.orientation_files.includes(target))return{allowed:false,state:s,terminal:s.status,code:'DENY_REFETCH'};if(s.admission.orientation_files.length+1>c.max_file_reads||s.admission.orientation_bytes+byteCount>c.max_total_bytes)return{allowed:false,state:s,terminal:s.status,code:'DENY_CAPSULE_BUDGET'};s.admission.orientation_files.push(target);s.admission.orientation_bytes+=byteCount;s.admission.phase='ORIENTING';return{allowed:true,state:s,terminal:'ORIENTING',code:'ALLOW_ORIENTATION_FILE'};}if(action===ORIENTATION_ACTIONS.PRESENT_TERMS){s.admission.phase='AWAITING_ACCEPTANCE';s.admission.terms_presented=true;return{allowed:true,state:s,terminal:'AWAITING_ACCEPTANCE',code:'ALLOW_PRESENT_TERMS_AND_FREEZE'};}if(REPO_ACCESS.has(action))return{allowed:false,state:s,terminal:s.status,code:'DENY_PREACCEPT_REPO_ACCESS'};return{allowed:false,state:s,terminal:s.status,code:'DENY_UNKNOWN_PREACCEPT'};}
export function recordCompletedPreacceptAccess(state,action,{target=null}={}){const s=structuredClone(state);if(s.accepted)return{state:s,terminal:s.status,breached:false};if(!REPO_ACCESS.has(action)&&action!==ORIENTATION_ACTIONS.FILE&&action!==ORIENTATION_ACTIONS.METADATA)return{state:s,terminal:s.status,breached:false};s.status='SESSION_NONCONFORMING';s.accepted=false;s.probed=false;s.initialized=false;s.admission.phase='BREACHED';s.admission.breached=true;s.admission.new_chat_required=true;return{state:s,terminal:'NEW_CHAT_REQUIRED',breached:true,target};}
export function canAccept(state,termsDigest){return !state.admission.breached&&state.admission.terms_presented===true&&state.admission.terms_digest===termsDigest;}
function freshLocalAdmission(state){return state?.status==='DISCOVERED'&&state?.accepted===false&&state?.probed===false&&state?.initialized===false&&state?.epoch===null&&state?.cycle===0&&state?.admission?.phase==='DISCOVERED'&&state?.admission?.terms_presented===false&&state?.admission?.pending_intent===null&&state?.admission?.breached===false;}
function localOrientationDigest(pathname){return sha256(fs.readFileSync(path.join(ROOT,pathname)));}
export function validatePreacceptHandoff(receipt,termsDigest){const c=readOrientationCapsule();if(!receipt||receipt.schema!=='ikant-le-preaccept-handoff/v1')return{ok:false,code:'HANDOFF_SCHEMA'};for(const k of ['accepted','probed','initialized','status','epoch'])if(Object.prototype.hasOwnProperty.call(receipt,k))return{ok:false,code:'HANDOFF_STATE_PROMOTION'};if(receipt.repository!==CANONICAL_REPOSITORY||!/^[a-f0-9]{40}$/.test(String(receipt.source_head||'')))return{ok:false,code:'HANDOFF_SOURCE'};if(receipt.terms_presented!==true||receipt.frozen!==true||receipt.breached!==false||receipt.authority!==0)return{ok:false,code:'HANDOFF_ADMISSION_FACTS'};if(receipt.runtime_observed_terms_presentation!==false||receipt.host_attested_terms_presentation!==true)return{ok:false,code:'HANDOFF_OBSERVATION_CLASS'};if(receipt.terms_digest!==termsDigest)return{ok:false,code:'HANDOFF_TERMS_DIGEST'};if(typeof receipt.pending_intent!=='string'||receipt.pending_intent_sha256!==sha256(Buffer.from(receipt.pending_intent)))return{ok:false,code:'HANDOFF_PENDING_DIGEST'};const digests=receipt.orientation_digests;if(!digests||typeof digests!=='object'||Array.isArray(digests))return{ok:false,code:'HANDOFF_ORIENTATION_DIGESTS'};const expectedKeys=[...c.paths].sort(),actualKeys=Object.keys(digests).sort();if(JSON.stringify(expectedKeys)!==JSON.stringify(actualKeys))return{ok:false,code:'HANDOFF_ORIENTATION_SCOPE'};for(const rel of c.paths)if(digests[rel]!==localOrientationDigest(rel))return{ok:false,code:'HANDOFF_ORIENTATION_MISMATCH',path:rel};const material={schema:receipt.schema,repository:receipt.repository,source_head:receipt.source_head,terms_presented:true,terms_digest:receipt.terms_digest,frozen:true,breached:false,pending_intent:receipt.pending_intent,pending_intent_sha256:receipt.pending_intent_sha256,orientation_digests:Object.fromEntries(c.paths.map(rel=>[rel,digests[rel]])),runtime_observed_terms_presentation:false,host_attested_terms_presentation:true,authority:0};return{ok:true,digest:sha256(Buffer.from(JSON.stringify(material))),material};}
export function importPreacceptHandoff(state,receipt,termsDigest){if(!freshLocalAdmission(state))return{ok:false,state:structuredClone(state),code:'HANDOFF_LOCAL_STATE_NOT_FRESH'};const validation=validatePreacceptHandoff(receipt,termsDigest);if(!validation.ok)return{...validation,state:structuredClone(state)};const c=readOrientationCapsule();let s=preservePendingIntent(state,receipt.pending_intent);s=presentTermsState(s,termsDigest);s.admission.orientation_files=[...c.paths];s.admission.orientation_bytes=c.paths.reduce((n,rel)=>n+fs.statSync(path.join(ROOT,rel)).size,0);s.admission.source_head=receipt.source_head;s.admission.preaccept_handoff_sha256=validation.digest;return{ok:true,state:s,digest:validation.digest,source_head:receipt.source_head};}
