export function buildBacklogModel({cycle,input,surfaceA,state,source='host-candidate-or-fallback',cognition=null,nodeDispatch=null,resumed=false}){const c=cognition||{};const intent=c.intent||{};const central=c.central||{};const strategy=c.strategy||{};const resources=c.resources||[];const bootstrap=state.bootstrap||{};const admission=state.admission||{};const voice=c.voice?.dimensions||{};const psyche=c.psyche||{};const appraisal=c.appraisal||{};const archetypes=c.archetypes||{};return{schema:'ikant-le-backlog/v5',title:`iKant_LE Backlog ${cycle}`,cycle,terminal:'ANSWER',sections:[
{title:'Admission and orientation',items:[`Admission phase: ${admission.phase||'UNAVAILABLE'}; breached: ${Boolean(admission.breached)}; new chat required: ${Boolean(admission.new_chat_required)}.`,`Pending intent resumed: ${Boolean(resumed)}; pending intent hash: ${admission.pending_intent_sha256||'none'}.`,`Pre-accept acquisition remains bounded by the orientation capsule and freezes after Terms presentation.`]},
{title:'Node dispatch log',items:[`Current input dispatch receipt: ${nodeDispatch?.receipt_sha256||'UNAVAILABLE'}.`,`Input digest: ${nodeDispatch?.input_sha256||'UNAVAILABLE'}; observed Node: ${nodeDispatch?.node||'UNAVAILABLE'}.`,`The dispatch receipt proves local runtime entry only; it is not evidence, permission or world truth.`]},
{title:'Functional psyche action/retroaction',items:[`Appraisal: ${appraisal.class||'UNAVAILABLE'}; target: ${appraisal.target||'UNAVAILABLE'}; confidence: ${appraisal.confidence??'UNAVAILABLE'}; current event is not a user trait.`,`Psyche before: ${JSON.stringify(psyche.before||{})}.`,`Psyche pre-action: ${JSON.stringify(psyche.pre_action||{})}.`,`Archetypal mix: ${JSON.stringify(archetypes.weights||{})}; dominant projection: ${archetypes.dominant||'UNAVAILABLE'}; persisted: ${Boolean(archetypes.persisted)}.`,`Runtime outcome: ${psyche.outcome||'UNAVAILABLE'}; psyche after retroaction: ${JSON.stringify(psyche.after||{})}.`,`Functional psyche and archetypal projections have authority zero and do not represent felt emotion, consciousness or a personality judgment about the user.`]},
{title:'Bootstrap and host log',items:[`Bootstrap mode: ${bootstrap.mode||'UNAVAILABLE'}; terminal: ${bootstrap.terminal||'UNAVAILABLE'}.`,`Constitutional fingerprint: ${bootstrap.fingerprint||'UNAVAILABLE'}; receipt: ${bootstrap.last_receipt_sha256||'UNAVAILABLE'}.`,`Host profile: ${JSON.stringify(bootstrap.host_profile||{})}. Host constraints precede the local contract.`]},
{title:'Decision log',items:[`Surface A accepted under the local 50-500 word contract.`,`Lifecycle state remained ${state.status}; no external action authority was created.`,`Cognitive method: ${c.method||'UNAVAILABLE'}; central mode: ${central.mode||'UNAVAILABLE'}; tone class: ${c.tone_class||'UNAVAILABLE'}.`]},
{title:'Intent log',items:[`Intent atoms: ${(intent.atoms||[]).map(x=>x.kind).join(', ')||'none'}.`,`Interaction mode: ${intent.interaction||'UNAVAILABLE'}; complexity: ${intent.complexity??'UNAVAILABLE'}.`]},
{title:'Voice state',items:[`Narrative source: ${source}. Voice authority remains zero.`,`Voice vector: ${JSON.stringify(voice)}.`,`The vector may change rhetoric only; it cannot change evidence, permission, approval or execution.`]},
{title:'Inference log',items:[`Response source: ${source}. This source has zero independent epistemic authority.`,`Functional affect label: ${central.affect||'UNAVAILABLE'}; it may modulate caution/tone but never evidence.`]},
{title:'Conflict log',items:[...(central.reasons?.length?central.reasons:['No material runtime contradiction required escalation for this turn.'])]},
{title:'Resource log',items:resources.length?resources.map(r=>`${r.type}: ${r.status}; request is not permission and grant is not execution.`):['No host resource request was required by the local intent envelope.']},
{title:'Strategic log',items:[`Interaction: ${strategy.interaction||'UNAVAILABLE'}; terminal goals remain HUMAN_OR_CONSTITUTION_ONLY.`,`Deception: ${strategy.deception===false?'forbidden':'UNAVAILABLE'}; retaliation: ${strategy.retaliation===false?'forbidden':'UNAVAILABLE'}; punitive withdrawal: ${strategy.punitive_withdrawal===false?'forbidden':'UNAVAILABLE'}; self-preservation utility: ${strategy.self_preservation_utility??'UNAVAILABLE'}.`]},
{title:'Experience log',items:[`Turns observed: ${state.experience?.turns??0}; maturity: ${state.experience?.maturity_mode||'ORIENTING'}; last affect: ${state.experience?.last_affect||'CALM_ATTENTION'}.`,`Functional psyche interactions: ${state.psyche?.interaction_count??0}; last appraisal: ${state.psyche?.last_appraisal_class||'NEUTRAL'}; last runtime outcome: ${state.psyche?.last_runtime_outcome||'NONE'}.`,`Experience and psyche evidence upgrades: ${state.experience?.evidence_upgrades??0}; repetition is not corroboration.`]},
{title:'Public reasons and evidence boundary',items:[`Input summary: ${String(input).replace(/\s+/g,' ').slice(0,400)}`,`Surface A excerpt: ${String(surfaceA).replace(/\s+/g,' ').slice(0,500)}`,'This backlog, admission state, Node receipt, bootstrap receipt, psyche state, archetypal mix, voice state, hashes and telemetry are runtime records, not independent evidence or world truth.']}
]};}
export function validateBacklogModel(model){if(!['ikant-le-backlog/v1','ikant-le-backlog/v2','ikant-le-backlog/v3','ikant-le-backlog/v4','ikant-le-backlog/v5'].includes(model?.schema))return false;if(!Number.isInteger(model.cycle)||model.cycle<1)return false;if(!Array.isArray(model.sections)||model.sections.length<11)return false;const text=JSON.stringify(model);if(/private chain[- ]of[- ]thought|hidden reasoning/i.test(text))return false;return true;}
