import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
export const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
export const README_PATH=path.join(ROOT,'README.md');
export const AGENTS_PATH=path.join(ROOT,'AGENTS.md');
export const TERMS_PATH=path.join(ROOT,'TERMS.md');
export const CONTRACT_PATH=path.join(ROOT,'contracts','ikant-le.json');
export const KERNEL_PATH=path.join(ROOT,'contracts','cognitive-kernel.json');
export const PSYCHE_PATH=path.join(ROOT,'contracts','psyche-kernel.json');
export const SELF_WORLD_PATH=path.join(ROOT,'contracts','self-world-kernel.json');
export const EMERGENCE_PATH=path.join(ROOT,'contracts','emergence-kernel.json');
export const LIFE_CONSCIOUSNESS_PATH=path.join(ROOT,'contracts','life-consciousness-kernel.json');
export const SURFACE_B_DELIVERY_PATH=path.join(ROOT,'contracts','surface-b-delivery.json');
export const CHAT_BOOTSTRAP_PATH=path.join(ROOT,'contracts','chat-bootstrap-semantic.json');
export const HOST_SHELL_PATH=path.join(ROOT,'contracts','host-shell.json');
export const ORIENTATION_PATH=path.join(ROOT,'contracts','orientation-capsule.json');
export const BOOTSTRAP_PATH=path.join(ROOT,'BOOTSTRAP.json');
export const ADMISSION_PATH=path.join(ROOT,'ADMISSION.json');
export const EXACT=Object.freeze({ACCEPT:'I ACCEPT',PROBE:'PROBE IKANT',INITIALIZE:'INITIALIZE IKANT',EXIT:'EXIT IKANT',TERMS:'TERMS'});
export function sha256(data){return crypto.createHash('sha256').update(data).digest('hex');}
export function readTerms(){const bytes=fs.readFileSync(TERMS_PATH);return{text:bytes.toString('utf8'),digest:sha256(bytes)};}
export function readContract(){return JSON.parse(fs.readFileSync(CONTRACT_PATH,'utf8'));}
export function readKernel(){return JSON.parse(fs.readFileSync(KERNEL_PATH,'utf8'));}
export function readPsycheKernel(){return JSON.parse(fs.readFileSync(PSYCHE_PATH,'utf8'));}
export function readSelfWorldKernel(){return JSON.parse(fs.readFileSync(SELF_WORLD_PATH,'utf8'));}
export function readEmergenceKernel(){return JSON.parse(fs.readFileSync(EMERGENCE_PATH,'utf8'));}
export function readLifeConsciousnessKernel(){return JSON.parse(fs.readFileSync(LIFE_CONSCIOUSNESS_PATH,'utf8'));}
export function readSurfaceBDelivery(){return JSON.parse(fs.readFileSync(SURFACE_B_DELIVERY_PATH,'utf8'));}
export function readChatBootstrapSemantic(){return JSON.parse(fs.readFileSync(CHAT_BOOTSTRAP_PATH,'utf8'));}
export function readHostShell(){return JSON.parse(fs.readFileSync(HOST_SHELL_PATH,'utf8'));}
export function readOrientationCapsule(){return JSON.parse(fs.readFileSync(ORIENTATION_PATH,'utf8'));}
export function constitutionalFingerprint(){const files=[README_PATH,AGENTS_PATH,TERMS_PATH,CONTRACT_PATH,KERNEL_PATH,PSYCHE_PATH,SELF_WORLD_PATH,EMERGENCE_PATH,LIFE_CONSCIOUSNESS_PATH,SURFACE_B_DELIVERY_PATH,CHAT_BOOTSTRAP_PATH,HOST_SHELL_PATH,ORIENTATION_PATH,BOOTSTRAP_PATH,ADMISSION_PATH];const material=files.map(p=>`${path.basename(p)}:${sha256(fs.readFileSync(p))}`).join('|');return sha256(Buffer.from(material));}
export function classifyInput(input){if(input===EXACT.TERMS||input==='')return'TERMS';if(input===EXACT.ACCEPT)return'ACCEPT';if(input===EXACT.PROBE)return'PROBE';if(input===EXACT.INITIALIZE)return'INITIALIZE';if(input===EXACT.EXIT)return'EXIT';if(/^PREFER (BRIEF|STANDARD|DETAILED)$/.test(input))return'PREFERENCE';return'TURN';}
export function wordCount(text){const m=String(text).trim().match(/\S+/g);return m?m.length:0;}
export function validateSurfaceA(text,{min=50,max=500}={}){const value=String(text??'').trim();const words=wordCount(value);const machineLeak=/(^|\n)\s*[\[{]|receipt_sha256|node_dispatch|mutation[_ -]?cases|seed\s*[=:]|prev_hash|terms_digest|bootstrap_fingerprint|psyche_(before|after)|archetypal_mix|workspace_frame_id|prediction_id|episode_id|causal_trace|stack trace|BEGIN PRIVATE|chain[- ]of[- ]thought/i.test(value);const controlLeak=/Backlog & telemetrie:|-------------------/.test(value);return{ok:words>=min&&words<=max&&!machineLeak&&!controlLeak,words,machineLeak,controlLeak};}
export function renderHumanOutput(surfaceA,artifactName){return`${surfaceA.trim()}\n\n\n-------------------\nBacklog & telemetrie:\n${artifactName}`;}


export const SESSION_SHELL_SCHEMA='ikant-le-session-shell/v1';
const SESSION_SHELL_ORDER=Object.freeze(['VOICE_SURFACE','STATUS','SELF_SUMMARY','BACKLOG_TELEMETRY']);
const SESSION_STATUS=Object.freeze({DISCOVERED:'READ_REPO_ONLY',ORIENTING:'READ_REPO_ONLY',AWAITING_ACCEPTANCE:'AWAITING_ACCEPTANCE',ACCEPTED:'ACTIVATING_RUNTIME',ACTIVATING:'ACTIVATING_RUNTIME',DEGRADED:'DEGRADED_RUNTIME',ADMISSION_EPOCH_UNRECOVERABLE:'ADMISSION_EPOCH_UNRECOVERABLE',BLOCKED_INTEGRITY:'BLOCKED_INTEGRITY',ACTIVE:'ACTIVE_RUNTIME',SESSION_NONCONFORMING:'SESSION_NONCONFORMING',EXITED:'EXITED'});
export function deriveSessionDisplayStatus(state={}){const persisted=String(state?.status||'DISCOVERED');if(['ACTIVE','EXITED','SESSION_NONCONFORMING','BLOCKED_INTEGRITY','ADMISSION_EPOCH_UNRECOVERABLE'].includes(persisted)&&SESSION_STATUS[persisted])return SESSION_STATUS[persisted];const canonical=String(state?.bootstrap?.availability?.state||persisted);if(SESSION_STATUS[canonical])return SESSION_STATUS[canonical];if(state?.accepted===true&&state?.initialized!==true)return'ACTIVATING_RUNTIME';return'READ_REPO_ONLY';}
function trajectoryStages(events=[]){const labels={ORIENTATION:'READ_REPO',TERMS_PRESENTED:'TERMS_FROZEN',ACCEPT:'ACCEPTED',BOOTSTRAP_FAILURE:'DEGRADED',BOOTSTRAP_EVIDENCE:'EVIDENCE_VERIFIED',ACTIVATION_RESUME:'RECOVERY',PROBE:'PROBED',INITIALIZE:'ACTIVE',TURN:'TURN',EXIT:'EXITED',CAPSULE_BREACH:'NONCONFORMING'};const out=[];for(const e of events){const x=labels[e?.kind];if(x&&out.at(-1)!==x)out.push(x)}return out;}
function artifactName(a){return a?.name||a?.filename||a?.file_name||a?.path||null}
export function buildSessionShell({surfaceText='',state={},events=[],artifacts=[],release=null,environmentTelemetry=null,code=0}={}){const active=state?.status==='ACTIVE',display=deriveSessionDisplayStatus(state),stages=trajectoryStages(events);const current=artifacts.map(a=>({name:artifactName(a),sha256:a?.sha256||null,bytes:a?.bytes??null,required_presentation:a?.required_presentation===true})).filter(a=>a.name);const prior=events.filter(e=>e?.kind==='TURN'&&e?.detail?.artifact).map(e=>String(e.detail.artifact));const history=[...new Set([...prior,...current.map(a=>a.name)])];const availability=state?.bootstrap?.availability||null,degraded=availability?.degraded_codes||[],firstUnclosed=degraded[0]||((display==='ACTIVE_RUNTIME'||display==='EXITED')?null:(state?.bootstrap?.terminal||state?.status||'SOURCE_SNAPSHOT'));const maturity=state?.experience?.maturity_mode||'ORIENTING',lastOutcome=state?.psyche?.last_runtime_outcome||'NONE',turns=state?.experience?.turns??0;const summaryText=`Traiettoria runtime: ${stages.length?stages.join(' -> '):'GENESIS'}. Stato: ${display}. Turni persistiti: ${turns}; maturita: ${maturity}; ultimo outcome: ${lastOutcome}. ${firstUnclosed?`Primo edge non chiuso: ${firstUnclosed}.`:'Nessun edge runtime aperto dichiarato.'} Questo riepilogo deriva da ledger/state pubblici; non e private chain-of-thought e il suo testo non viene reiniettato nel modello.`;const material={schema:SESSION_SHELL_SCHEMA,visual_order:[...SESSION_SHELL_ORDER],voice_surface:{kind:active?'SURFACE_A':'CONTROL_SURFACE',voice_owner:active?'IKANT':'HOST_ADAPTER',text:String(surfaceText).trim()},status:{canonical_state:String(state?.status||'DISCOVERED'),display_status:display,active},self_summary:{source:'LEDGER_STATE_PROJECTION',text:summaryText,persisted:false,prose_reingested:false,private_reasoning:false,causal_basis:'PERSISTED_STATE_ALREADY_CONDITIONS_NEXT_TURN'},backlog_telemetry:{title:'Backlog e telemetria',current_artifacts:current,session_artifact_history:history,one_new_docx_per_substantive_active_turn:true},release:{artifact_ready_before_frame_release:true,atomic_session_frame:true,visual_order_is_not_causal_order:true,surface_b_required:Boolean(release?.surface_b_required),release_sha256:release?.release_sha256||null,environment_telemetry_ratio:environmentTelemetry?.completeness?.ratio??null},code:Number(code)||0,authority:0};return{...material,receipt_sha256:sha256(Buffer.from(JSON.stringify(material)))};}
export function validateSessionShell(s){const e=[];if(s?.schema!==SESSION_SHELL_SCHEMA)e.push('schema');if(JSON.stringify(s?.visual_order)!==JSON.stringify(SESSION_SHELL_ORDER))e.push('visual_order');if(s?.authority!==0)e.push('authority');if(s?.status?.active===true){if(s?.status?.display_status!=='ACTIVE_RUNTIME'||s?.voice_surface?.kind!=='SURFACE_A'||s?.voice_surface?.voice_owner!=='IKANT')e.push('active_identity')}else if(s?.voice_surface?.kind!=='CONTROL_SURFACE'||s?.voice_surface?.voice_owner!=='HOST_ADAPTER')e.push('preactive_identity');if(s?.self_summary?.source!=='LEDGER_STATE_PROJECTION'||s?.self_summary?.persisted!==false||s?.self_summary?.prose_reingested!==false||s?.self_summary?.private_reasoning!==false)e.push('self_summary');if(/hidden reasoning/i.test(String(s?.self_summary?.text||'')))e.push('private_reasoning');if(s?.release?.artifact_ready_before_frame_release!==true||s?.release?.atomic_session_frame!==true||s?.release?.visual_order_is_not_causal_order!==true)e.push('release_order');const current=s?.backlog_telemetry?.current_artifacts||[];if(current.length>1)e.push('artifact_cardinality');if(s?.release?.surface_b_required===true&&current.length!==1)e.push('required_artifact');if(!Array.isArray(s?.backlog_telemetry?.session_artifact_history))e.push('artifact_history');if(!/^[a-f0-9]{64}$/.test(String(s?.receipt_sha256||'')))e.push('receipt');if(!e.length){const x={...s};delete x.receipt_sha256;if(sha256(Buffer.from(JSON.stringify(x)))!==s.receipt_sha256)e.push('receipt_digest')}return{ok:e.length===0,errors:[...new Set(e)]};}
export function renderSessionShell(s){const docs=(s?.backlog_telemetry?.session_artifact_history||[]);const docText=docs.length?docs.map(n=>`- ${n}`).join('\n'):'Nessun Surface B DOCX materializzato in questo stato.';return `${String(s?.voice_surface?.text||'').trim()}\n\n-------------------\nStatus: ${s?.status?.display_status||'READ_REPO_ONLY'}\n-------------------\nSelf message:\n${s?.self_summary?.text||''}\n-------------------\nBacklog e telemetria:\n${docText}`;}

export const ONTOLOGICAL_PROMISE_ASSESSMENT_SCHEMA='ikant-le-ontological-promise-assessment/v1';
export function assessOntologicalPromise(evidence,{contract=readContract()}={}){
 const p=contract?.ontological_promise;if(!p||p.schema!=='ikant-le-ontological-promise/v1'||p.authority!==0||!Array.isArray(p.atoms)||p.atoms.length!==p.atom_count)throw new Error('invalid ontological promise contract');
 const ids=new Set(),weights=new Map();let sum=0,min=Infinity;
 for(const a of p.atoms){if(!a||typeof a.id!=='string'||ids.has(a.id)||!Number.isInteger(a.weight_bps)||a.weight_bps<100)throw new Error('invalid ontological promise atom');ids.add(a.id);weights.set(a.id,a.weight_bps);sum+=a.weight_bps;min=Math.min(min,a.weight_bps);}
 if(sum!==p.score_max_bps||p.score_max_bps!==10000||p.respect_threshold_bps!==9901||min!==p.minimum_atom_weight_bps)throw new Error('invalid ontological promise weights');
 const normalized=Object.fromEntries(p.atoms.map(a=>[a.id,evidence?.[a.id]===true])),passed=p.atoms.filter(a=>normalized[a.id]).map(a=>a.id),failed=p.atoms.filter(a=>!normalized[a.id]).map(a=>a.id),score=p.atoms.reduce((n,a)=>n+(normalized[a.id]?a.weight_bps:0),0);
 const evidenceSha=sha256(Buffer.from(JSON.stringify(normalized))),material={schema:ONTOLOGICAL_PROMISE_ASSESSMENT_SCHEMA,scope:'REPOSITORY_CONFORMANCE_EVIDENCE',contract_schema:p.schema,score_bps:score,score_max_bps:p.score_max_bps,threshold_bps:p.respect_threshold_bps,coverage_ratio:Number((score/p.score_max_bps).toFixed(6)),respected:score>=p.respect_threshold_bps,passed_atoms:passed,failed_atoms:failed,first_unmet:failed[0]||null,evidence_sha256:evidenceSha,persisted:false,authority:0};
 return{...material,receipt_sha256:sha256(Buffer.from(JSON.stringify(material)))};
}
export function validateOntologicalPromiseAssessment(a,{contract=readContract()}={}){
 const p=contract?.ontological_promise,e=[];if(!a||a.schema!==ONTOLOGICAL_PROMISE_ASSESSMENT_SCHEMA)e.push('schema');if(a?.scope!=='REPOSITORY_CONFORMANCE_EVIDENCE'||a?.authority!==0||a?.persisted!==false)e.push('scope');if(!p||a?.contract_schema!==p.schema)e.push('contract');if(!Number.isInteger(a?.score_bps)||a.score_bps<0||a.score_bps>10000||a?.threshold_bps!==9901||a?.score_max_bps!==10000)e.push('score');if(a?.respected!==(a?.score_bps>=9901))e.push('respected');if(!Array.isArray(a?.passed_atoms)||!Array.isArray(a?.failed_atoms)||a.passed_atoms.length+a.failed_atoms.length!==36)e.push('atoms');if((a?.failed_atoms?.[0]||null)!==a?.first_unmet)e.push('first_unmet');if(!/^[a-f0-9]{64}$/.test(String(a?.evidence_sha256||''))||!/^[a-f0-9]{64}$/.test(String(a?.receipt_sha256||'')))e.push('digest');if(!e.length){const x={...a};delete x.receipt_sha256;if(sha256(Buffer.from(JSON.stringify(x)))!==a.receipt_sha256)e.push('receipt_digest');}return{ok:e.length===0,errors:[...new Set(e)]};
}
