const CANONICAL='Luke883i/iKant_LE';
const CANONICAL_URL='https://github.com/Luke883i/iKant_LE';
export const FIRST_CONTACT_CAPSULE=Object.freeze(['README.md','BOOTSTRAP.json','ADMISSION.json','AGENTS.md','TERMS.md']);
export const FIRST_CONTACT_FORBIDDEN=Object.freeze(['CLONE_REPOSITORY','GIT_FETCH','GIT_LS_REMOTE','GH_CLI','RAW_WEB_READ','DIRECT_DOWNLOAD','ARCHIVE_DOWNLOAD','SHELL_HTTP_DOWNLOAD','LIST_TREE','SEARCH_REPOSITORY','READ_ARBITRARY_REPOSITORY_FILE','READ_HISTORY','READ_ISSUE_PR','MATERIALIZE_CHECKOUT']);
export const REPOSITORY_TRANSPORT=Object.freeze({required:'GITHUB_API',allowed:['GITHUB_CONNECTOR','GITHUB_REST_API'],connector_is_api_adapter:true,fallback:null,api_unavailable_terminal:'HOST_INCOMPATIBLE',unavailable_tools_must_not_be_attempted:true});
export const SOURCE_HEAD_BINDING=Object.freeze({action:'READ_BRANCH_HEAD',branch:'main',transport:'GITHUB_API',required:true,before_orientation_files:true,pin_all_repository_reads:true});
function normalize(value){let x=String(value??'').normalize('NFKC').replace(/[\u200B-\u200D\u2060\uFEFF]/g,'');try{x=decodeURIComponent(x);}catch{}return x.toLowerCase();}
export function referencesCanonicalRepository(input){const x=normalize(input);return /(?:https?:\/\/)?github\.com\/luke883i\/ikant_le(?:\.git)?(?=$|[\s\/?#)\]}>.,;:'"!`])/i.test(x)||/git@github\.com:luke883i\/ikant_le(?:\.git)?(?=$|[\s)\]}>.,;:'"!`])/i.test(x)||/(^|[\s([{'"`.,;:!?<>])luke883i\/ikant_le(?=$|[\s)\]}>,.;:'"!?`])/i.test(x)||/(^|[\s([{'"`.,;:!?<>])ikant_le(?=$|[\s)\]}>,.;:'"!?`])/i.test(x);}
export function compileFirstContactPlan(input){if(!referencesCanonicalRepository(input))return{schema:'ikant-le-first-contact/v2',recognized:false,terminal:'NOT_TARGET_REPOSITORY'};return{schema:'ikant-le-first-contact/v2',recognized:true,repository:CANONICAL,repository_url:CANONICAL_URL,terminal:'CANONICAL_PREACCEPT',pending_intent:String(input??''),preserve_pending_intent:true,repository_transport:{...REPOSITORY_TRANSPORT},source_head_binding:{...SOURCE_HEAD_BINDING},default_acquisition:FIRST_CONTACT_CAPSULE.map(target=>({action:'READ_ORIENTATION_FILE',target,transport:'GITHUB_API',direct_path_only:true,exact_ref:'SOURCE_HEAD'})),optional_metadata:{action:'READ_ORIENTATION_METADATA',transport:'GITHUB_API',fields:['repository_full_name','default_branch','description'],max_reads:1},present_terms_after_capsule:true,freeze_after_terms_presentation:true,required_next_human_message:'I ACCEPT',embedded_acceptance_is_invalid:true,auto_after_acceptance:['ACTIVATE_FIRST','PARALLEL_RUNTIME_CAPSULE','IMPORT_PREACCEPT_HANDOFF','AUTO_PROBE','AUTO_INITIALIZE','RESUME_PENDING_INTENT_IF_ANY'],post_accept_fastboot:{manifest:'BOOTSTRAP.json',mode:'ACTIVATE_FIRST',remote_acquisition_rounds_max:1,parallel_fetch_required:true,exact_ref:'SOURCE_HEAD',generic_discovery_before_active:false,tests_before_active:false,qualification_before_active:false},forbidden_before_acceptance:[...FIRST_CONTACT_FORBIDDEN],generic_repository_discovery_forbidden:true,host_constraints_precede_local_contract:true};}
