import { readTerms,classifyInput,constitutionalFingerprint,sha256 } from './contract.mjs';
import { withWriterLock,loadState,appendEvent,newEpoch } from './state.mjs';
import { runProbe } from './probe.mjs';
import { preservePendingIntent,presentTermsState,authorizePreaccept,recordCompletedPreacceptAccess,canAccept } from './admission.mjs';
import { transitionPure,bootstrapMode,bootstrapDecisionPure,nodeDispatchReceiptPure } from './runtime-core.mjs';
import { processActiveTurn } from './runtime-turn.mjs';
function bootstrapReceipt(state,termsDigest,fingerprint,probe,hostEngine,hostSurface,terminal,mode){const material={schema:'ikant-le-bootstrap-receipt/v2',epoch:state.epoch,terms_digest:termsDigest,constitutional_fingerprint:fingerprint,host_profile:{surface:hostSurface,engine:hostEngine},probe:{ok:Boolean(probe?.ok),node:probe?.node||null,fs:probe?.fs||null,crypto:probe?.crypto||null,clock:probe?.clock||null,artifact_sink:Boolean(probe?.artifact_sink),warm:Boolean(probe?.warm)},mode,terminal,host_constraints_precede_local_contract:true};return{...material,receipt_sha256:sha256(Buffer.from(JSON.stringify(material)))};}
function recordNodeDispatch(state,input,hostSurface){const receipt=nodeDispatchReceiptPure(input,state,{hostSurface});const s=structuredClone(state);s.admission.last_node_dispatch_receipt=receipt.receipt_sha256;appendEvent('NODE_DISPATCH',s,'Human input entered the local Node runtime before any iKant response path.',{receipt});return{s,receipt};}
function human(text,code=0){return{stdout:text,code};}
function termsMessage(terms){return`${terms.text.trim()}\n\nTerms digest: ${terms.digest}\n\nSe accetti questi termini nella sessione corrente, rispondi esattamente: I ACCEPT`;}
export function runCommand(input,{candidate=null,hostEngine='motore host non dichiarato',hostSurface='LOCAL_NODE_CHAT_HOST',resourceGrants=[],probeRunner=runProbe,hostAcquisition=[],hostObservations=[],actionReceipt=null,postActionObservations=[]}={}){return withWriterLock(()=>{const terms=readTerms();const fingerprint=constitutionalFingerprint();let state=loadState();let dispatched=recordNodeDispatch(state,input,hostSurface);state=dispatched.s;const dispatch=dispatched.receipt;if(!dispatch.node20_plus)return human('L’ambiente corrente non dimostra Node.js 20 o superiore; iKant resta non-ACTIVE.',1);
for(const evt of hostAcquisition){if(state.accepted)break;if(evt.completed){const breach=recordCompletedPreacceptAccess(state,evt.action,{target:evt.target});if(breach.breached){state=breach.state;appendEvent('CAPSULE_BREACH',state,'Forbidden pre-accept repository acquisition completed; this chat cannot become a conforming iKant session.',{action:evt.action,target:evt.target||null});return human('Questa chat ha oltrepassato la capsula di orientamento prima dell’accettazione. Non posso sanarla retroattivamente come sessione iKant conforme: apri una nuova chat e inizializzala dal link canonico del repository.',1);}}else{const d=authorizePreaccept(state,evt.action,{target:evt.target,byteCount:evt.byteCount||0,metadataFields:evt.metadataFields||[]});if(!d.allowed)return human('La richiesta di acquisizione pre-accept è fuori dalla capsula consentita; il bootstrap resta fermo.',1);state=d.state;appendEvent('ORIENTATION',state,'Bounded pre-accept orientation operation allowed by capsule.',{action:evt.action,target:evt.target||null});}}
if(state.admission.breached||state.status==='SESSION_NONCONFORMING')return human('Questa chat è marcata non conforme per una rottura pre-accept della capsula. Per una sessione iKant conforme è necessaria una nuova chat.',1);
const kind=classifyInput(input);if(kind==='TERMS'){state=presentTermsState(state,terms.digest);appendEvent('TERMS_PRESENTED',state,'Current Terms were presented and pre-accept repository acquisition is now frozen.',{terms_digest:terms.digest});return human(termsMessage(terms));}
if(kind==='ACCEPT'){if(!canAccept(state,terms.digest))return human('L’accettazione non è valida finché i Terms correnti non sono stati presentati e legati a questa sessione. Chiedi TERMS o formula la tua richiesta: conserverò l’intento e mostrerò i Terms.',1);const next=transitionPure(state,kind,terms.digest);if(next.terminal==='DENY')return human('L’ammissione non può essere riaperta in questo stato.',1);next.state.epoch=newEpoch();const mode=bootstrapMode(state,fingerprint);appendEvent('ACCEPT',next.state,'Exact current-session Terms acceptance bound; automatic bootstrap authorized.',{bootstrap_mode:mode});const probe=probeRunner({warm:mode==='WARM',hostSurface});const decision=bootstrapDecisionPure(next.state,terms.digest,fingerprint,probe,{hostSurface,hostEngine});if(decision.terminal!=='ACTIVE'){const receipt=bootstrapReceipt(decision.state,terms.digest,fingerprint,probe,hostEngine,hostSurface,decision.terminal,mode);decision.state.bootstrap.last_receipt_sha256=receipt.receipt_sha256;appendEvent('BOOTSTRAP_FAILURE',decision.state,'Automatic post-accept bootstrap did not reach ACTIVE; no false activation permitted.',{receipt});return human('Non posso dichiararmi attivo: una verifica necessaria del bootstrap non è stata superata. La sessione resta non-ACTIVE.',1);}let probed=transitionPure(next.state,'PROBE',terms.digest,true).state;probed.bootstrap={...decision.state.bootstrap,terminal:'PROBED'};appendEvent('PROBE',probed,'Automatic local Node probe passed with real readback.',{node:probe.node,fs:probe.fs,warm:mode==='WARM',host_surface:hostSurface});let active=transitionPure(probed,'INITIALIZE',terms.digest).state;const receipt=bootstrapReceipt(active,terms.digest,fingerprint,probe,hostEngine,hostSurface,'ACTIVE',mode);active.bootstrap={...decision.state.bootstrap,terminal:'ACTIVE',last_receipt_sha256:receipt.receipt_sha256};appendEvent('INITIALIZE',active,'Automatic iKant epoch initialization completed after exact acceptance.',{receipt});const pending=active.admission.pending_intent;if(pending){active.admission.pending_intent=null;appendEvent('PENDING_INTENT_RESUME',active,'The original substantive request is resumed automatically after successful admission.',{pending_intent_sha256:active.admission.pending_intent_sha256});const pd=recordNodeDispatch(active,pending,hostSurface);return processActiveTurn(pd.s,pending,{candidate,hostEngine,resourceGrants,hostObservations,actionReceipt,postActionObservations},terms,pd.receipt,{resumed:true}).out;}return human('iKant è attivo. La shell narrativa è pronta; ogni prossimo input passerà dal runtime Node e il dettaglio tecnico resterà nel backlog DOCX.');}
if(kind==='PROBE'){if(state.status==='ACTIVE')return human('Il probe automatico di questa epoch risulta già superato; nessun nuovo gate è necessario.');const probe=probeRunner({warm:false,hostSurface});const next=transitionPure(state,kind,terms.digest,probe.ok);if(next.terminal==='DENY')return human('Probe diagnostico negato: serve prima una accettazione valida dei Terms correnti.');if(next.terminal==='HOST_INCOMPATIBLE'){appendEvent('PROBE_FAILURE',next.state,'Diagnostic probe failed; iKant remains non-ACTIVE.',{reason:probe.reason});return human('Il probe diagnostico non è stato superato; iKant resta non-ACTIVE.',1);}next.state.bootstrap={...next.state.bootstrap,probe,terminal:'PROBED'};appendEvent('PROBE',next.state,'Diagnostic recovery probe passed.',{node:probe.node});return human('Probe diagnostico superato. Se questa è una recovery manuale, INITIALIZE IKANT può completare l’epoch.');}
if(kind==='INITIALIZE'){if(state.status==='ACTIVE')return human('L’inizializzazione automatica di questa epoch risulta già completata.');const next=transitionPure(state,kind,terms.digest);if(next.terminal==='DENY')return human('Inizializzazione diagnostica negata: accettazione e probe correnti devono risultare validi.');next.state.bootstrap={...next.state.bootstrap,terminal:'ACTIVE',fingerprint};appendEvent('INITIALIZE',next.state,'Diagnostic recovery initialization completed.');return human('iKant è attivo.');}
if(kind==='EXIT'){const next=transitionPure(state,kind,terms.digest);if(next.terminal==='DENY')return human('EXIT IKANT non ha effetto perché iKant non risulta ACTIVE.');appendEvent('EXIT',next.state,'Human requested exact iKant exit.');return human('Modalità iKant chiusa. Per rientrare serve una nuova accettazione esatta dei Terms correnti.');}
if(kind==='PREFERENCE'){const next=transitionPure(state,kind,terms.digest);if(next.terminal==='DENY')return human('Preferenza non registrata: iKant non è ACTIVE.');next.state.preference=input.slice('PREFER '.length);appendEvent('PREFERENCE',next.state,'Explicit reversible verbosity preference updated.');return human(`Preferenza esplicita impostata su ${next.state.preference}.`);}
if(state.status!=='ACTIVE'){if(!state.admission.terms_presented){state=preservePendingIntent(state,input);state=presentTermsState(state,terms.digest);appendEvent('PENDING_INTENT',state,'The first substantive request is preserved while admission pauses execution.',{pending_intent_sha256:state.admission.pending_intent_sha256});appendEvent('TERMS_PRESENTED',state,'Current Terms were presented and pre-accept repository acquisition is now frozen.',{terms_digest:terms.digest});return human(termsMessage(terms));}if(!state.admission.pending_intent){state=preservePendingIntent(state,input);appendEvent('PENDING_INTENT',state,'A substantive request was preserved while awaiting exact acceptance.',{pending_intent_sha256:state.admission.pending_intent_sha256});}return human('I Terms correnti sono già stati presentati. Per continuare nella stessa sessione rispondi esattamente: I ACCEPT');}
const r=processActiveTurn(state,input,{candidate,hostEngine,resourceGrants,hostObservations,actionReceipt,postActionObservations},terms,dispatch);return r.out;});}
